- scripts/generate_kernel_header.py
- test/conformance/device_code/CMakeLists.txt
The icpx (and other similar Intel binaries) don't allow the generation of IR output, so instead generate the list of kernel names using the integration header instead.
For reference, the IH contains the following:
```c++
// names of all kernels defined in the corresponding source
static constexpr
const char* const kernel_names[] = {
"_ZTSZZ4mainENKUlRN4sycl3_V17handlerEE_clES2_E8indexers"
};
```
which we can just search for.
> [CMake] Parse kernel names using integration header rather than IR

- source/adapters/opencl/usm.cpp
Direct assignment of pNext is all that's required here
> [NFC] Remove redundant ternary operation

- .github/scripts/compute_benchmarks.py
- .github/workflows/benchmarks_core.yml
- .github/workflows/benchmarks_level_zero.yml
This patch adds a script for running compute-benchmarks, https://github.com/intel/compute-benchmarks/, and a corresponding GH Actions workflow that runs those benchmarks when prompted to do so with a comment, like so:
/benchmarks-level-zero --env UR_L0_IMMEDIATE_COMMANDLISTS_BATCH_EVENT_COMPLETIONS=1
Additional arguments can be appended to the end of the line. After the build if finished, the results will be presented through a comment.
For now, this runs only a single scenario, api_overhead_benchmark_sycl with SubmitKernel test, but will expand over time to cover more.
> add compute benchmark workflow for L0

- include/ur_api.h
- scripts/core/exp-enqueue-timestamp-recording.yml
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
This was failing with the HIP adapter when the pointer is null and the event wait list is not 0.
> Fix validation for urEnqueueTimestampRecordingExpTest

- CMakeLists.txt
This allows tracing to be enabled when UR is built from intel-llvm which already builds the XPTI targets
> Add option to control building XPTI libraries

- test/conformance/enqueue/enqueue_adapter_hip.match
- test/conformance/enqueue/urEnqueueKernelLaunch.cpp
CUDA and HIP have limited introspection capabilities so we can't check kernel arguments.
> [CTS][CUDA][HIP] Skip invalid kernel argument test

- test/conformance/CMakeLists.txt
When configured without match files, the CTS was trying to run a command and its arguments as a single command, as it was represented by a single string variable. It needs to be a single string in the default case - when building with UR_CONFORMANCE_ENABLE_MATCH_FILES=ON - as that command string is passed off to another command via a flag, so it must be seen by the shell as one item.
While definitely not *nice*, this is the simplest fix I could think of which preserves the behaviour of the (more important, tested) 'default' case.
> [CTS] Fix UR_CONFORMANCE_ENABLE_MATCH_FILES=OFF

- scripts/core/INTRO.rst
- scripts/templates/trcddi.cpp.mako
- source/common/logger/ur_logger.hpp
- source/common/logger/ur_logger_details.hpp
- source/common/logger/ur_sinks.hpp
- source/loader/layers/tracing/ur_tracing_layer.cpp
- source/loader/layers/tracing/ur_tracing_layer.hpp
- source/loader/layers/tracing/ur_trcddi.cpp
- test/layers/tracing/CMakeLists.txt
- test/layers/tracing/hello_world.out.logged.match
This adds the ability to use the tracing layer with a logger rather than relying on XPTI. The motivation for this is to provide an equivalent to `SYCL_PI_TRACE` when we remove PI from the SYCL runtime. `urtrace` and `sycl-trace` will still be supported.
> Add ability to log from the tracing layer directly rather than use XPTI

- test/conformance/program/program_adapter_hip.match
- test/conformance/program/urProgramSetSpecializationConstants.cpp
The HIP adapter doesn't support UR spec constants, just like the CUDA adapter.
> [CTS] Skip spec constants tests for HIP

- test/adapters/level_zero/CMakeLists.txt
- test/adapters/level_zero/event_cache_tests.cpp
Replace if(LINUX) with if(NOT WIN32) as the former wasn't working on some distros.
Also, there was a rebase conflict which resulted with having two tests with the same name. Rename one of them.
> Fix level zero specific test

- source/adapters/level_zero/event.cpp
- test/adapters/level_zero/CMakeLists.txt
- test/adapters/level_zero/multi_device_event_cache_tests.cpp
- Fix the creation of the multi device event to occur only when the root devices of the event and the executing queue do not match.
> [UR] Fix Multi Device Event Cache for shared Root Device

- source/adapters/hip/device.cpp
- test/conformance/kernel/kernel_adapter_hip.match
Handle the `UR_DEVICE_INFO_KERNEL_SET_SPECIALIZATION_CONSTANTS` device query to report the feature is not supported. This also causes the `urKernelSetSpecializationConstants` tests to be skipped.
https://github.com/intel/llvm/pull/13809
> [HIP] Implement kernel set spec constant query

- source/adapters/opencl/usm.cpp
This is a follow-up of https://github.com/oneapi-src/unified-runtime/pull/1412 which added the `isPowerOf2` condition to the OpenCL fill function. This is correct since `clEnqueueMemFillINTEL_fn` only accepts such patterns.
What was not correct was the later logic for emulating filling on the host and copying it to the destination ptr. It assumed that the pattern is greater than **128 bytes** but after adding the above `isPowerOf2` condition, it could also execute for smaller patterns which are simply not powers of 2. 
So this PR fixes my introduced bugs, **intel/llvm CI:** https://github.com/intel/llvm/pull/13779
> [OpenCL] Modify fill emulation to work for patterns which are not powers of 2

- source/adapters/level_zero/command_buffer.cpp
Add debug logging to the Level Zero structs used when a command-buffer kernel command is updated.
DPC++ PR https://github.com/intel/llvm/pull/13892
> Debug logging in Level Zero command-buffer update

- test/adapters/level_zero/urKernelCreateWithNativeHandle.cpp
Use the include path for `ze_api.h` which points to the Level Zero loader in the build dependencies, which does not have reside in the `level_zero` subdirectory, in Level Zero adapter test suite.
I believe this passed GHA because of the presence of a system install of Level Zero, rather than relying on the header acquired via fetch content.
> [L0] Fix local build without system install

- test/conformance/testing/include/uur/utils.h
Without having a device index or UUID added to the device name, tests were failing in multi GPU systems as tests would instantiate the same testnames for separate GPUs of the same model. This makes each GPU name unique, which in turn makes test names unique.
> [Test] Add UUID to device name

- cmake/match.py
- test/conformance/enqueue/enqueue_adapter_hip.match
- test/conformance/program/program_adapter_hip.match
These have a variety of uses. For example, by documenting the reasons for known failures inside the match files themselves, we can keep all relevant information in one place and help direct developers towards known reproducers, areas of code to investigate, etc.
The comment character is '#' which is fairly common and intuitive, especially in conf-style file types. Also no GTest tests should ever be named with that character.
> Add support for comments in match files

- source/adapters/cuda/enqueue.cpp
This PR changes the returned error code for exiting the kernel launch entry point in CUDA when exceeding the maximum available registers for execution on the SM. Previously we were returning a misleading error code.
This change requires DPC++ to adapt the specific-error handling, see PR: https://github.com/intel/llvm/pull/12604.
> [CUDA] Use appropriate return code for out of registers kernel launch

- test/conformance/program/program_adapter_hip.match
Despite passing CI at the time, and passing locally, it has subsequently failed in another CI run.
> [HIP] Add an eagerly-removed program_adapter match line

- source/adapters/cuda/enqueue.cpp
The DPC++ `root_group` test already passes (and still does with this patch), but it doesn't actually enable `root_group` sync in reality. However I think the only thing missing is this small patch. With this patch the the custom kernel launch is called with the cooperative attribute. 
I've tested this locally, but will link up a dpc++ ci test for completeness.
> [CUDA] wire up cooperative kernel launch

- source/adapters/cuda/device.cpp
Addresses the removal of `UR_DEVICE_USM_ACCESS_CAPABILITY_FLAG_ATOMIC_CONCURRENT_ACCESS` from the supported features of host memory. This change is prompted by the incompatibility of CUDA with concurrent atomic access between host and device to pinned memory.
The CUDA adapter uses `cuMemAllocHost` for host memory allocation, which allocates page-locked host memory. However, this type of memory does not support concurrent atomic access, as detailed in this [related discussion](https://stackoverflow.com/questions/23193151/atomic-operations-in-cuda-kernels-on-mapped-pinned-host-memory-to-do-or-not-to).
Furthermore, this issue shows in [SYCL-CTS-USM](https://github.com/KhronosGroup/SYCL-CTS/blob/9ea1b1cdda5689a14e42e83050637428298b838b/tests/usm/usm_atomic_access.h#L164) when …
> [CUDA] Remove the support of concurrent atomic access to host allocated pinned memory.

- source/adapters/hip/context.cpp
- test/conformance/context/context_adapter_hip.match
This showed up in the UR CTS, it was returning a vector instead of the expected C array.
> [HIP] Fix context devices property return value

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/device.cpp
In order to support all the ways a kernel command in a command-buffer can be updated in Unified Runtime, the following capabilities need to be available from the device:
* `ZE_MUTABLE_COMMAND_EXP_FLAG_KERNEL_ARGUMENTS`
* `ZE_MUTABLE_COMMAND_EXP_FLAG_GROUP_COUNT`
* `ZE_MUTABLE_COMMAND_EXP_FLAG_GROUP_SIZE`
* `ZE_MUTABLE_COMMAND_EXP_FLAG_GLOBAL_OFFSET`
Only supporting kernel argument update is not sufficient, as is currently the case. There is also no way in the UR API currently to take advantage of the `ZE_MUTABLE_COMMAND_EXP_FLAG_SIGNAL_EVENT` and `ZE_MUTABLE_COMMAND_EXP_FLAG_WAIT_EVENTS` capabilities, so these can be omitted.
Also fix debug printing of `pGroupCount` in command update, as we want to show the values it contains rather than pointer value.
DPC++ PR …
> Set minimum L0 device support to support UR kernel update

- .github/workflows/cmake.yml
- .github/workflows/e2e_core.yml
- .github/workflows/e2e_cuda.yml
- .github/workflows/e2e_level_zero.yml
- .github/workflows/e2e_opencl.yml
We don't want to treat these workflows as blockers though, so we enable continue-on-error for step with tests.
Add comment with actual test status to the PR.
// I've tested the flow on my fork: https://github.com/lukaszstolarczuk/unified-runtime/pull/7
// comment is added; flow only works if prev. (dependent) jobs are done (e.g. "cuda" required for "e2e_cuda")
> [CI] Run E2E on PR

- source/adapters/cuda/event.cpp
- source/adapters/cuda/event.hpp
- source/adapters/cuda/queue.cpp
- source/adapters/cuda/queue.hpp
- source/adapters/hip/context.cpp
- source/adapters/hip/device.cpp
- source/adapters/hip/device.hpp
- source/adapters/hip/event.cpp
- source/adapters/hip/event.hpp
- source/adapters/hip/platform.cpp
- source/adapters/hip/platform.hpp
- source/adapters/hip/queue.cpp
- source/adapters/hip/queue.hpp
HIP changes:
- To match with the current behaviour of CUDA adapter, `EvBase` in HIP was moved to `device` and                                                      `getElapsedTime` function now handles the profiling events' synchronization. Also, we were using `hipStreamDefault` flag as default, but in CUDA, we use `CU_STREAM_NON_BLOCKING`, this was also changed to match with cuda, **commits 1-3**
- Added an extra profiling stream to `Queue` which is only created when profiling is enabled and it is used to record `EvQueued`. This was necessary because before we were recording it on the `NULL` stream and this might not be the best solution for HIP, see https://github.com/intel/llvm/issues/12904, **commit 4**
CUDA changes:
- Also added the extra profiling stream for consistency, **commit 5** …
> [HIP][CUDA] Refactor using profiling events 

- source/adapters/cuda/usm.cpp
- source/adapters/hip/usm.cpp
Now all devices are in a single platform for both cuda and hip, this needs updating.
Fixes https://github.com/intel/llvm/issues/6749#issuecomment-1971875971
> [CUDA][HIP] Fix urUSMGetMemAllocInfo impl to use single platform.

- source/loader/windows/adapter_search.cpp
The loader mistakenly searched for adapters in the directory of the executable that linked it, instead of its own directory.
> [UR] Fix adapter search on Windows

- test/conformance/exp_command_buffer/buffer_fill_kernel_update.cpp
- test/conformance/exp_command_buffer/fixtures.h
- test/conformance/exp_command_buffer/ndrange_update.cpp
- test/conformance/exp_command_buffer/usm_fill_kernel_update.cpp
The command-buffer kernel update CTS tests currently assume that L0 doesn't support updating the ND-Range configuration of kernels in a command-buffer.
This is no longer the case, and the skips in these situations can be removed. This patch also contains tweaks to the tests to address issues hidden while the tests were skipped on Level Zero.
> Remove L0 limitation from command-buffer update CTS tests

- .github/workflows/cmake.yml
As noted in #1715 testing on Windows Server 2022 in Release mode has become flaky in the last couple of days. The root cause of this has so far been elusive and the issue is not reproducible on a local Windows 11 machine. This patch temporarily disables this axis from the job matrix while investigation continues.
> [GHA] Temporarily disable testing on windows-2022

- cmake/FindCUDACupti.cmake
- source/adapters/cuda/CMakeLists.txt
Previously, CUDA tracing only worked when the UR sources were built as part of the CUDA PI plugin. FindCUDACupti.cmake is copied verbatim from intel/llvm.
> Fix CUDA tracing when UR is built standalone

- source/adapters/level_zero/command_buffer.cpp
When we initialize our `ze_mutable_group_count_exp_desc_t` struct that's used in a pointer chain passed to
`zexCommandListUpdateMutableCommandsExp` we set the `pGroupCount` member to `&ZeThreadGroupDimensions`.
However, `ZeThreadGroupDimensions` is declared on the stack in the scope of the if statement. Resulting in this pointer becoming invalid after the scope of the if statement, when the L0 update API is called.
Fixed by moving the `ZeThreadGroupDimensions` variable outside the scope of the if statement, into the scope of the function, so that the address is valid when `zexCommandListUpdateMutableCommandsExp` is called.
DPC++ PR https://github.com/intel/llvm/pull/14076
> Fix lifetime of pointer used in L0 update

- include/ur_api.h
- scripts/core/exp-command-buffer.yml
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/command_buffer.hpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/exp_command_buffer/exp_command_buffer_adapter_native_cpu.match
- test/conformance/exp_command_buffer/usm_fill_kernel_update.cpp
- test/conformance/exp_command_buffer/usm_saxpy_kernel_update.cpp
The Level Zero adapter implementing `urCommandBufferUpdateKernelLaunchExp` is doing a blocking host wait with `zeEventHostSynchronize` on the executing of the command-buffer.
However, there is no guarantee that the command-buffer has been enqueued before update has been called. Resulting in a hang if this is not the case. Even if a command-buffer has been enqueued before, the L0 event primitive can't guarantee that the command-list has finished executing, only a specific command.
Instead, replace the blocking wait on a L0 event with a blocking wait on a L0 fence from the last submission of the command-buffer. This is because fences are the only safe way to track when a command-buffer execution has completed.
DPC++ PR https://github.com/intel/llvm/pull/13832
> Use fence rather than event for sync in L0 command-buffer update 

- source/adapters/cuda/device.cpp
- source/adapters/hip/device.cpp
- source/adapters/level_zero/device.cpp
- source/adapters/opencl/device.cpp
- `UR_DEVICE_INFO_SUB_GROUP_SIZES_INTEL`: The spec says it's an array of uint32_t, but CUDA, HIP, OpenCL, and LevelZero adapters were returning arrays of size_t. As a result, we had extra dummy zeroes in the output. Native CPU adapter was correct.
- `UR_DEVICE_INFO_ATOMIC_*_CAPABILITIES`: Should be `ur_memory_scope_capability_flags_t`, was `uint64_t` in CUDA/HIP.
> Fix size confusion for several device property queries

- source/adapters/cuda/enqueue.cpp
In https://github.com/oneapi-src/unified-runtime/pull/1674/files I made a check for nullptr after already dereferencing the pointer. This swaps the order around.
> [CUDA] Check for nullptr before dereference.

- source/adapters/hip/enqueue.cpp
- test/conformance/enqueue/enqueue_adapter_hip.match
As noted in CUDA adapter commit 00761dc4, the validation for this entry point was changed in commit 2c533e6a and hoisted into the validation layer. The restriction on the pattern size being at most 128 was removed in 00761dc4, and I can't see a reason for it being in the HIP adapter save for the fact that it was copied from the CUDA adapter.
> [HIP] Remove overly restrictive urEnqueueMemBufferFill validation

- source/adapters/hip/device.cpp
DPCPP - some fence libclc refator plus CI testing: 
- https://github.com/intel/llvm/pull/12872
> [HIP] Enable more ordering and scope capabilities for atomic fences

- source/adapters/hip/device.cpp
DPCPP changes: 
- https://github.com/intel/llvm/pull/12938
(enables `sycl::memory_order::seq_cst` in `sycl::atomic_ref`)
> [HIP] Enable more ordering and scope capabilities for atomic memory ops

- test/conformance/device_code/cpy_and_mult.cpp
- test/conformance/device_code/cpy_and_mult_usm.cpp
> [NFC] Use sycl/sycl.hpp instead of CL/sycl.hpp

- source/adapters/level_zero/queue.cpp
- To avoid usecases where the LastcommandEvent could be updated in another thread and a thread can be expecting the Queue Wait to include this event, then hold the queue lock such that the last command event remains unchanged during synchronization.
> [L0] Maintain Lock of Queue while syncing the Last Command Event and update Last Command Event only if matching

- CMakeLists.txt
- source/adapters/level_zero/queue.cpp
- #1749
- Bump version to v0.9.6
> Candidate for the v0.9.6 release tag

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/command_buffer.hpp
- Out-of-order command-buffers now use copy-engine in some cases where available
- Also respect existing L0 env vars for using copy-engine with fill and d2d copies
> [CMDBUF][L0] Use copy engine to optimize cmd-buffer usage

- test/conformance/context/urContextGetInfo.cpp
These tests are only used for single device ctxs. Test was failing on multi GPU system.
Also remove unused header
> Don't assume a multi dev ctx is being used

- source/adapters/hip/device.cpp
Reverts oneapi-src/unified-runtime#1415 - We found last minute instability with seq_cst ordering tests for AMD gfx10-11 architectures, so needs further investigation before we can reconsider this.
> Revert "[HIP] Enable more ordering and scope capabilities for atomic memory ops"

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.hpp
- scripts/core/platform.yml
- scripts/templates/helper.py
- scripts/templates/ldrddi.cpp.mako
- source/adapters/cuda/platform.cpp
- source/adapters/hip/platform.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/native_cpu/platform.cpp
- source/adapters/null/ur_nullddi.cpp
- source/adapters/opencl/platform.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_ldrddi.hpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/platform/urPlatformCreateWithNativeHandle.cpp
Other CreateWithNative entry points need a UR handle primarily so the loader has something to obtain a ddi table from. This new adapter parameter fulfils that purpose for PlatformCreateWithNative, allowing us to remove a weird hack that saw the loader getting (apparently succesfully somehow??) a loader object out of the native handle itself.
fixes https://github.com/oneapi-src/unified-runtime/issues/1068
> Add hAdapter parameter to urPlatformCreateWithNativeHandle

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.h
- include/ur_print.hpp
- scripts/core/EXP-BINDLESS-IMAGES.rst
- scripts/core/exp-bindless-images.yml
- scripts/core/registry.yml
- source/adapters/cuda/image.cpp
- source/adapters/cuda/ur_interface_loader.cpp
- source/adapters/hip/image.cpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/ur_interface_loader.cpp
- source/adapters/native_cpu/image.cpp
- source/adapters/native_cpu/ur_interface_loader.cpp
- source/adapters/null/ur_nullddi.cpp
- source/adapters/opencl/image.cpp
- source/adapters/opencl/ur_interface_loader.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/loader.def.in
- source/loader/loader.map.in
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/loader/ur_print.cpp
- source/ur_api.cpp
The interop import API has been adapted to cater to multiple external memory and semaphore handle types.
This enables memory and semaphores to be imported by single functions irregardless of what the underlying handle type is.
The following APIs have been removed:
- `ImportExternalOpaqueFDExp`
- `ImportExternalSemaphoreOpaqueFDExp`
The following APIs have been added:
- `ImportExternalMemoryExp`
- `ImportExternalSemaphoreExp`
The following enums have been added:
- `exp_external_mem_type_t`
- `exp_external_semaphore_type_t`
Support has also been added to import DirectX 12 memory and fences.
Semaphore operations (wait/signal) can now take values which set the semaphore state to the value passed by the user.
> [Bindless][Exp] Windows & DX12 interop. Semaphore ops can take values.

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/event.hpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/kernel.hpp
- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/memory.hpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/queue.hpp
This change moves all legacy queue code to a seprate class: ur_queue_handle_legacy_t_. and uses pointer to this class as a parameter in all internal functions (instead of using ur_queue_handle_t). ur_queue_handle_t is now a variant over this legacy class and a new queue dispatcher (not implemented yet). All API functions still take ur_queue_handle_t and convert it to ur_queue_handle_legacy_t using a helper function.
Once dispatcher is implemented there will be a seprate code path for each (affected) API function for legacy and new logic.
> [L0] Create initial structure for supporting queue dispatcher

- test/conformance/program/program_adapter_cuda.match
Two urProgramGetInfoTest match entries were recently accidentally changed to allow *any* test to optionally fail, rather than the two we know about.
Another - urProgramGetInfoSingleTest.NumDevicesMatchesDeviceArray - was added in 4c0476cc and we can't account for it, so optimistically remove it from the match file.
Also add a few comments to match the equivalent HIP match file.
> [CUDA][CTS] Update program match file

- source/common/logger/ur_logger.hpp
avoid creating a temporary string.
`logger::debug` is visible as a hostspot for `doCall` for certain benchmarks on `-Og`.  It's hard to estimate the actual benefit of this but on a simple microbenchmark (calling `logger::debug` in a loop) this change brings ~40% improvement.
> Optimize get_logger function

- source/adapters/native_cpu/device.cpp
Reports `cl_khr_fp16` as supported on Native CPU.
Corresponding UR PR: https://github.com/intel/llvm/pull/13829
> [NATIVECPU] Report cl_khr_fp16 on native cpu

- source/adapters/cuda/adapter.cpp
- source/adapters/hip/adapter.cpp
- source/common/logger/ur_level.hpp
- source/common/logger/ur_logger.hpp
The HIP and CUDA adapaters would like a more verbose logging level by default. This patch allows customization per logger.
If the default log level is unsupplied, the old default continues to be used. Users can also continue to override the logging level via the various environment variables.
> [HIP][CUDA] Allow customization of the default logging level

- source/adapters/cuda/program.cpp
- source/adapters/hip/program.cpp
- test/conformance/program/program_adapter_cuda.match
- test/conformance/program/program_adapter_hip.match
- test/conformance/program/urProgramGetBuildInfo.cpp
We were always returning the maximum log size (of 8192) even when the actual log was much shorter. Strictly speaking, we should be returning the log only up to the first null terminator. Doing otherwise could cause strange behaviour, and may account for the flaky fails we've seen in this test on both adapters.
> [CUDA][HIP] Fix build info log reporting

- source/adapters/cuda/memory.cpp
- source/adapters/cuda/memory.hpp
- source/adapters/cuda/physical_mem.cpp
- source/adapters/cuda/program.cpp
- source/adapters/cuda/queue.cpp
- source/adapters/cuda/sampler.cpp
- source/adapters/hip/context.cpp
- source/adapters/hip/kernel.cpp
- source/adapters/hip/memory.cpp
- source/adapters/hip/memory.hpp
- source/adapters/hip/program.cpp
- source/adapters/hip/queue.cpp
- source/adapters/hip/sampler.cpp
Use unique ptrs, and have the destructor call clear(), instead of calling it manually. Also add a case for a std::bad_alloc.
> [CUDA][HIP] Make calls to `new` failsafe

- source/adapters/cuda/event.cpp
- source/adapters/cuda/event.hpp
- source/adapters/hip/event.cpp
- source/adapters/hip/event.hpp
We can't make assumptions about interop events being on the same stream as other interop events, since in UR we don't track the streams that native events are recorded on.
> [CUDA][HIP] Always wait on interop events

- source/adapters/cuda/context.cpp
- source/adapters/hip/context.cpp
- test/conformance/context/context_adapter_hip.match
Mirrors a similar change made to the CUDA adapater in 00761dc4.
> [HIP] Fix error code for urContextCreateWithNativeHandle

- source/adapters/hip/kernel.hpp
- test/conformance/kernel/kernel_adapter_hip.match
The property should be of type size_t.
Note that we're removing a bunch of match lines for seemingly unrelated properties, but in fact the CTS tests do not make use of the parameter they claim, and in fact hard-code the UR_KERNEL_INFO_NUM_ARGS property.
> [HIP] Fix return type for urKernelGetInfo UR_KERNEL_INFO_NUM_ARGS

- include/ur_api.h
- scripts/core/kernel.yml
- source/adapters/cuda/kernel.cpp
- source/adapters/hip/kernel.cpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/native_cpu/kernel.cpp
- source/adapters/null/ur_nullddi.cpp
- source/adapters/opencl/kernel.cpp
- source/loader/layers/sanitizer/asan_interceptor.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/enqueue/urEnqueueKernelLaunch.cpp
- test/conformance/exp_command_buffer/invalid_update.cpp
- test/conformance/exp_command_buffer/ndrange_update.cpp
- test/conformance/exp_command_buffer/usm_fill_kernel_update.cpp
- test/conformance/exp_command_buffer/usm_saxpy_kernel_update.cpp
- test/conformance/integration/QueueEmptyStatus.cpp
- test/conformance/integration/QueueUSM.cpp
- test/conformance/kernel/urKernelSetArgPointer.cpp
Also attempt to clarify the wording around this a bit.
fixes #558
LLVM testing https://github.com/intel/llvm/pull/12270
> Correct level of indirection used in KernelSetArgPointer calls.

- source/adapters/cuda/image.cpp
Address incorrect execution of device to host and device to device subregion copies:
- CUDA_MEMCPY3D's srcXInBytes and dstXInBytes fields were not being set in bytes
- CUDA_MEMCPY3D's dstPitch and dstHeight fields were not being set
> [CUDA][Bindless][Exp] Fix subregion copies

- CMakeLists.txt
- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/adapter.hpp
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/command_buffer.hpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/platform.hpp
- source/adapters/level_zero/ur_level_zero.hpp
- source/adapters/level_zero/usm.cpp
- https://github.com/oneapi-src/unified-runtime/pull/1778
- Bump version to v0.9.7
> Candidate for the v0.9.7 release tag

- .github/workflows/e2e_core.yml
- .github/workflows/e2e_level_zero.yml
This adds additional xfail supressions for known failing tests and forcibly adds gpu-intel-pvc-1T to lit config.
> Fix L0 E2E workflow

- test/adapters/level_zero/v2/command_list_cache_test.cpp
older driver versions might not implement zeCommandListGet* functions.
> [L0] skip checks in test if L0 function is not supported

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/exp-launch-properties.yml
- scripts/core/memory.yml
- source/adapters/cuda/device.cpp
- source/adapters/cuda/enqueue.cpp
- source/adapters/cuda/event.cpp
- source/adapters/cuda/kernel.cpp
- source/adapters/cuda/kernel.hpp
- source/adapters/cuda/memory.cpp
- source/adapters/hip/enqueue.cpp
- source/adapters/hip/memory.cpp
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/null/ur_nullddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/enqueue/enqueue_adapter_hip.match
- test/conformance/exp_launch_properties/launch_properties.cpp
- test/conformance/memory/urMemGetNativeHandle.cpp
- tools/urinfo/urinfo.hpp
Batch merge of PRs:
https://github.com/oneapi-src/unified-runtime/pull/1792
https://github.com/oneapi-src/unified-runtime/pull/1787
https://github.com/oneapi-src/unified-runtime/pull/1782
https://github.com/oneapi-src/unified-runtime/pull/1783
https://github.com/oneapi-src/unified-runtime/pull/1781
https://github.com/oneapi-src/unified-runtime/pull/1773
https://github.com/oneapi-src/unified-runtime/pull/1765
https://github.com/oneapi-src/unified-runtime/pull/1763
> [UR] Master merge

- source/adapters/level_zero/CMakeLists.txt
In v1.17.0 L0 loader started to fetch spdlog repo to get the headers and this causes issues in some scenarios. v1.17.6 removes that dependency from third party repo.
> [UR] Update L0 loader to v1.17.6

- scripts/core/CONTRIB.rst
Correcting out of date links in the contribution guide to exact lines in the UR CMakeLists.txt in intel/llvm.
> Update contribution guide links to intel/llvm UR CMakeLists.txt

- CMakeLists.txt
Setting `CMAKE_RUNTIME_OUTPUT_DIRECTORY` to `${CMAKE_BINARY_DIR}/bin/$<CONFIG>` breaks intel/llvm on Windows when using `ur_loader.dll` because the loader library does not exist beside `sycl8.dll` or the various `.exe` tools which depend on it.
> Don't use $<CONFIG> in runtime output dir

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/queue.hpp
- Keep track of all immediate command lists ensuring that they are not used in regular queues after they are placed back into the command list map.
> [L0] Fix immediate command list use in Command Queues

- .github/workflows/cmake.yml
Release builds are fixed on Windows runner images, now.
> [CI] Re-enable windows Release build

- source/adapters/level_zero/kernel.cpp
This fixes urEnqueueKernelLaunchTest.InvalidWorkDimension.
There might be more failing tests in enqueue. Right now this test seems to crash (in the driver) on Arcs so I'm not sure if we even run all the tests from enqueue.cpp I found this on PVC where the error was reported differently and didn't match with the matchfile.
I'm not sure what the best approach is here, but maybe we should just filter out the tests we know fail in the driver so that we can run all of them?
> [L0] Add missing check for WorkDim to KernelLaunch funcs

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/command_buffer.hpp
intel/llvm PR: https://github.com/intel/llvm/pull/14240
General:
- The idea is to make the code more readable and avoid code duplication when possible.
- There was a lot of branching in some entrypoints. Some of that functionality was moved into separate functions.
- The checks for InOrder/OutOfOrder and ComputeEngine/CopyEngine were also moved to separate common functions where possible.
`enqueueCommandBufferMemCopyHelper()`:
`enqueueCommandBufferMemCopyRectHelper()`:
`enqueueCommandBufferFillHelper()`:
- Use common function to create the sync point: `createSyncPointIfNeeded()`
- Use common function to choose the command-list: `ur_exp_command_buffer_handle_t_::chooseCommandList()`
- Move conditions to check if the queue is in order or not to the common functions: …
> Refactor Level Zero Command-Buffer implementation

- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/device.hpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/queue.cpp
Shifting more than number of bits in the type is undefined behavior. Current code results in incorrect TimestampMaxValue calculation when valid bits >= 64 for the device. This PR is fixing this.
intel/llvm PR: https://github.com/intel/llvm/pull/14360
> [UR][L0] Fix undefined behavior caused by shifting more than bits count

- include/ur_api.h
- scripts/core/enqueue.yml
- scripts/core/exp-command-buffer.yml
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
All adapters have sufficiently robust workarounds that this is no longer necessary, and the sycl runtime is now using USMFill in such a way that if we enable the validation layer this case will get hit and break stuff.
> Remove the power of 2 pattern size requirement from USMFill

- test/conformance/exp_enqueue_native/CMakeLists.txt
This was tripping up the CTS parsing script and the `adapter-cuda` part of the name is added automatically.
> [CTS] Fix naming of exp_enqueue_native test

- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/common.hpp
- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
- Given zeIntelGetDriverVersionString is available, then use the new driver extension to read the driver runtime version string.
> [L0] Use Intel Level Zero Driver String extension

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.hpp
- scripts/core/EXP-BINDLESS-IMAGES.rst
- scripts/core/exp-bindless-images.yml
- scripts/parse_specs.py
- scripts/templates/print.hpp.mako
- source/adapters/cuda/image.cpp
- source/adapters/cuda/image.hpp
- source/adapters/hip/image.cpp
- source/adapters/level_zero/image.cpp
- source/adapters/native_cpu/image.cpp
- source/adapters/null/ur_nullddi.cpp
- source/adapters/opencl/image.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_ldrddi.hpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
The bindless image extension added new handle types, however some of them are used in the SYCL Runtime in ways that contradict how handles are expected to be implemented, by casting them directly between other types. This breaks when UR is used with the UR loader, which transparently wraps handles to allow dispatching to specific adapters. This usage implies they are more like native handles, so they should be implemented like native handles.
Rename the image and image_mem types - if they end in `native_handle_t`, they are treated as native handles. Also update ImageGetInfoExp to take a context handle so it still possible for the loader to dispatch to the adapters.
Also fix incorrect return condition for `UR_RESULT_ERROR_INVALID_IMAGE_FORMAT_DESCRIPTOR` in bindless image functions
> Treat bindless images handle types as native handles

- cmake/helpers.cmake
This is to address potential DLL planting security issue, see: https://msrc.microsoft.com/blog/2018/04/triaging-a-dll-planting-vulnerability/#current-working-directory-cwd-dll-planting
> add DEPENDENTLOADFLAG linker flag on Windows

- source/adapters/opencl/device.cpp
- source/adapters/opencl/program.cpp
- source/adapters/opencl/sampler.cpp
The macro `CL_RETURN_ON_FAILURE` was being used on functions that return ur_result_t, which results in the CL code -> UR code mapping to happen twice. This updates those cases to use UR_RETURN_ON_FAILURE instead.
> [UR] Update some incorrect CL_RETURN_ON_FAILURE

- scripts/templates/ldrddi.cpp.mako
- source/loader/ur_ldrddi.cpp
This is a temporarily fix for a problem with `urEnqueue` entries in `ldrddi` loader. The problem is that these entries could return a valid `Event` handle while in the same time the entry is returning `UR_RESULT_ADAPTER_SPECIFIC_ERROR` like in [here](https://github.com/oneapi-src/unified-runtime/blob/01af5602345ac3289cc084eb19bf266c054da075/source/adapters/hip/enqueue.cpp#L1395C14-L1395C46). This would cause a seg-fault where the loader wrapper would not be called on this event handle like in [here](https://github.com/oneapi-src/unified-runtime/blob/01af5602345ac3289cc084eb19bf266c054da075/source/loader/ur_ldrddi.cpp#L5298) and later when `urEventRelease` is called on this valid event handle, it will pass by the loader to extract the dditable from the handle like in …
> Add a workaround for urEnqueue loader problems with ADAPTER_SPECIFIC

- source/adapters/level_zero/program.cpp
- test/conformance/kernel/urKernelCreate.cpp
- test/conformance/testing/include/uur/fixtures.h
Using just the first device makes creating a kernel from that program for any other devices impossible. urEnqueueKernelLaunch fails with UR_RESULT_ERROR_INVALID_QUEUE.
I don't know if using only the first device was intentional or not (perhaps an optimization?) but the test that I added passes for opencl so I think it would make sense to make L0 behave similarly.
> [L0] Use all devices from a context in urProgramBuild

- source/loader/layers/sanitizer/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan_interceptor.hpp
- source/loader/layers/sanitizer/asan_options.hpp
- source/loader/layers/sanitizer/asan_report.cpp
- source/loader/layers/sanitizer/ur_sanitizer_layer.cpp
The AsanOptions class, a singleton, was being instantiated inside of the sanitizer context constructor, but, inside of its contructor, it was using the logger from inside of the context. This only worked before because the context variable was a global and the logger just so happened to be initialized prior to the AsanOptions.
Now that the layer contexts are not globals, this was causing a deadlock on trying to retrieve a context while it was being initialized. The fix is to pass the logger manually to the AsanOptions class.
A better fix might be to refactor AsanOptions to no longer be a singleton, but I was trying to minimize changes since this is blocking intel/llvm update.
> [ASAN] fix recursive initialization of sanitizer context

- source/adapters/opencl/device.cpp
This reverts commit a4a5b086ce2f185c3e9e915310a2dada6f9b2ab2, reversing changes made to 53d4433fa1a1b9ed9a7627488e544deea857e802.
Unfortunately #1849 has caused regressions of the following tests on GEN12 as seen [here](https://github.com/intel/llvm/actions/runs/9939578717/job/27455389339?pr=14552).
```
Failed Tests (3):
SYCL :: Plugin/sycl-ls-gpu-default-any.cpp
SYCL :: Plugin/sycl-ls-gpu-opencl.cpp
SYCL :: Plugin/sycl-ls.cpp
```
> Revert "Merge pull request #1849 from ayylol/cl-subgroupsizes"

- source/adapters/cuda/platform.cpp
During testing of https://github.com/intel/llvm/pull/14145 the CUDA adapter was returning a hard error when being initialized on a system with no NVIDIA GPU. This corner case should not be an error condition so this patch specially handles `CUDA_ERROR_NO_DEVICE` being returned from `cuInit()` (which is an undocumented error code) to exit early from the CUDA adapter initialization.
> Handle CUDA_ERROR_NO_DEVICE returned from cuInit()

- source/adapters/mock/ur_mock.cpp
- source/common/windows/ur_lib_loader.cpp
- source/loader/ur_adapter_registry.hpp
- test/loader/platforms/null_platform.match
Change the value of the `mock_platform_name` to avoid mismatches in string size when using replacement entry points in mock tests.
Also add logging of adapter load and unload as this proved useful in tracking down this issue & will enable fixes of other tests.
> Fix mock on Windows, add logging of adapter load/unload

- include/ur_api.h
- include/ur_ddi.h
- scripts/core/exp-bindless-images.yml
- source/adapters/cuda/image.cpp
- source/adapters/hip/image.cpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/queue.hpp
- source/adapters/level_zero/queue_api.cpp
- source/adapters/level_zero/queue_api.hpp
- source/adapters/level_zero/v2/queue_immediate_in_order.cpp
- source/adapters/level_zero/v2/queue_immediate_in_order.hpp
- source/adapters/mock/ur_mockddi.cpp
- source/adapters/native_cpu/image.cpp
- source/adapters/opencl/image.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
Add const-qualifier to `Src` parameter in `urBindlessImagesImageCopyExp`.
Corresponding DPC++ PR: https://github.com/intel/llvm/pull/14140
> [Bindless][Exp] Add const-qualifier to Src param in urBindlessImagesImageCopyExp

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.h
- include/ur_print.hpp
- scripts/core/EXP-BINDLESS-IMAGES.rst
- scripts/core/exp-bindless-images.yml
- scripts/core/registry.yml
- source/adapters/cuda/image.cpp
- source/adapters/cuda/ur_interface_loader.cpp
- source/adapters/hip/image.cpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/ur_interface_loader.cpp
- source/adapters/mock/ur_mockddi.cpp
- source/adapters/native_cpu/image.cpp
- source/adapters/native_cpu/ur_interface_loader.cpp
- source/adapters/opencl/image.cpp
- source/adapters/opencl/ur_interface_loader.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/loader.def.in
- source/loader/loader.map.in
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/loader/ur_print.cpp
- source/ur_api.cpp
Rename function urBindlessImagesDestroyExternalSemaphoreExp to urBindlessImagesReleaseExternalSemaphoreExp.
This name change is to clarify exactly what is happening to the external semaphore. That is, it is being released not destroyed.
Corresponding DPC++ PR: https://github.com/intel/llvm/pull/14535
> [Bindless][Exp] Rename external semaphore destroy func to release

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.h
- include/ur_print.hpp
- scripts/core/EXP-BINDLESS-IMAGES.rst
- scripts/core/exp-bindless-images.yml
- source/adapters/cuda/image.cpp
- source/adapters/hip/image.cpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/queue.hpp
- source/adapters/level_zero/queue_api.cpp
- source/adapters/level_zero/queue_api.hpp
- source/adapters/level_zero/v2/queue_immediate_in_order.cpp
- source/adapters/level_zero/v2/queue_immediate_in_order.hpp
- source/adapters/mock/ur_mockddi.cpp
- source/adapters/native_cpu/image.cpp
- source/adapters/opencl/image.cpp
- source/common/stype_map_helpers.def
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/loader.def.in
- source/loader/loader.map.in
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/loader/ur_print.cpp
- source/ur_api.cpp
The new design, proposed through this patch, addresses the current problems/limitations for urBindlessImagesImageCopyExp:
- unused or redundant arguments.
- lack of support for new features such as subregion layered image copies.
- host versus device instead of source versus destination.
The API accepts two image descriptors and two image formats which accommodate for copying between two different image types and possible formats.
The copy information is captured by a new struct, namely `ur_exp_image_copy_region_t`. It enables subregion copy for layered images and mipmaps.
> [CUDA][L0][Bindless] update design of urBindlessImagesImageCopyExp

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/EXP-BINDLESS-IMAGES.rst
- scripts/core/exp-bindless-images.yml
- source/adapters/cuda/device.cpp
- source/adapters/level_zero/device.cpp
- tools/urinfo/urinfo.hpp
Add support to query if a device supports image arrays, unique addressing per dimension and support for sampling 1D/2D usm images.
Remove export semaphore, export image memory and fetch 3D usm image aspects as they are not supported on any backend.
Update Level Zero and CUDA backend device_info supported features.
> [Bindless][Exp] Update device_info enum elements and update Level Zero and CUDA backend device_info supported features

- include/ur_api.h
- scripts/core/kernel.yml
- source/adapters/level_zero/kernel.cpp
- source/adapters/mock/ur_mockddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/adapters/level_zero/urKernelCreateWithNativeHandle.cpp
- test/conformance/kernel/kernel_adapter_native_cpu.match
- test/conformance/kernel/urKernelCreateWithNativeHandle.cpp
Not all backends requires this parameter so sycl doesn't always provide it. This prevents those cases from getting caught in the validation layer.
> Make urKernelCreateWithNativeHandle's program param optional.

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.hpp
- scripts/core/context.yml
- scripts/core/queue.yml
- source/adapters/cuda/context.cpp
- source/adapters/hip/context.cpp
- source/adapters/level_zero/context.cpp
- source/adapters/mock/ur_mockddi.cpp
- source/adapters/native_cpu/context.cpp
- source/adapters/opencl/context.cpp
- source/loader/layers/sanitizer/ur_sanddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/context/context_adapter_native_cpu.match
- test/conformance/context/urContextCreateWithNativeHandle.cpp
- test/conformance/source/environment.cpp
- test/conformance/testing/include/uur/environment.h
- test/conformance/testing/include/uur/fixtures.h
The public sycl interface allows you to create a context from a native context handle without passing in anything else, to match this we need the device parameter to be optional. Allowing the device to be null has the potential to break the loader since it no longer has a loader handle to get function pointers from, so we also need to add a handle parameter that the sycl RT is guaranteed to have access to when it needs to call `ContextCreateWithNative`.
This PR also makes the device param in `QueueCreateWithNative` optional for similar reasons.
> Make urContextCreateWithNativeHandle work for SYCL use with loader

- source/common/linux/ur_lib_loader.cpp
- source/loader/ur_lib.cpp
Helps with fixing SYCL e2e tests which expect an ordered shutdown of libraries.
> Introduce more loader logging

- source/common/CMakeLists.txt
UMF compile options caused errors on some SYCL runners. Bump UMF to a version that should resolve these errors.
Logs: https://github.com/intel/llvm/actions/runs/10106492701/job/27948711538
> Bump UMF version

- source/common/CMakeLists.txt
This fixes CI errors on SYCL Windows runners.
Logs: https://github.com/intel/llvm/actions/runs/10111807383/job/27964511692?pr=14145
> Bump UMF version again

- source/adapters/level_zero/queue.cpp
- Remove the PVC limitation for enabling counter based events.
> [L0] Enable Counter Based Events by default for immediate command lists

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/command_buffer.hpp
Coverity has reported that there is the possibility of the command-buffer destructor throwing an exception from its calls
to `CleanupCompletedEvent`.
This is from an underlying `throw` in [GetQueue](https://github.com/oneapi-src/unified-runtime/blob/main/source/adapters/level_zero/queue.hpp#L890) when a `dynamic_cast` doesn't behave as expected. I initially tried
changing this to an assert but the V2 Level Zero adapter is triggering this case while in it's developmental state, so an assert brings down the whole test suite rather than just being reported as a fail (the UR loader catches exceptions and returns them as error codes).
Therefore this PR addresses the Coverity report by moving the calls to `CleanupCompletedEvent()` outside of the command-buffer destructor. This allows us to …
> Refactor L0 command-buffer cleanup.

- source/adapters/level_zero/usm.cpp
- source/adapters/level_zero/usm.hpp
- source/common/umf_helpers.hpp
- source/common/ur_util.cpp
- source/common/ur_util.hpp
- test/adapters/level_zero/CMakeLists.txt
- test/adapters/level_zero/ipc.cpp
Depends on: https://github.com/oneapi-src/unified-runtime/pull/1430.
Those changes are based on the changes in L0 provider on UMF repo https://github.com/oneapi-src/unified-memory-framework/pull/558.
> [L0] Implement IPC ops for L0 adapter

- source/adapters/cuda/event.cpp
- source/adapters/hip/event.cpp
- test/adapters/cuda/CMakeLists.txt
- test/adapters/cuda/event_tests.cpp
- test/adapters/cuda/raii.h
- test/adapters/cuda/urEventCreateWithNativeHandle.cpp
- test/adapters/hip/CMakeLists.txt
- test/adapters/hip/test_event.cpp
This PR addresses https://github.com/oneapi-src/unified-runtime/issues/1235 by returning an error on event queries, specifically `UR_EVENT_INFO_COMMAND_QUEUE`, that cannot be supported for the CUDA and HIP adapters. This is an effect of creating the ur_event from a native event which leads to not being able to fully initialize the UR object.
intel/llvm CI: https://github.com/intel/llvm/pull/12958
> [CUDA][HIP] Return error on silently failing urEventGetInfo queries for interop created events

- .github/docker/README.md
- .github/docker/fedora-40.Dockerfile
- .github/docker/install_dpcpp.sh
- .github/docker/opensuse-leap-15.Dockerfile
- .github/docker/rockylinux-8.Dockerfile
- .github/docker/rockylinux-9.Dockerfile
- .github/docker/ubuntu-20.04.Dockerfile
- .github/docker/ubuntu-24.04.Dockerfile
Add new docker images and update the existing ones with proper dependencies. I've added pip requirements into the docker, hence updated README with proper usage.
These images should be ready to use in CI.
// I've tested these dockers on a sep. branch (`test-dockers`) on my fork, results are all green (except for clang build in Ubuntu 20.04 - but this will be fixed separately):
https://github.com/lukaszstolarczuk/unified-runtime/actions/runs/10073401444
\+ Fedora build: https://github.com/lukaszstolarczuk/unified-runtime/actions/runs/10073471475
> Update and extend dockers

- source/ur/ur.cpp
This will allow `PrintTrace` to keep working after https://github.com/intel/llvm/pull/14145 is merged
> Enable PrintTrace when SYCL UR tracing is enabled

- source/common/CMakeLists.txt
bump UMF tag to switch to 0.9.0-rc3 release - this branch contains all latest fixes
> bump UMF tag to switch to rc3 release

- source/loader/layers/sanitizer/asan_interceptor.hpp
Also use uint32_t for Debug value.
> Don't retain device handle references in sanitizer layer.

- README.md
E2E workflows run now as part of "Build and test" workflow.
Add missing other workflows, to track if they are green or not.
// Preview: https://github.com/lukaszstolarczuk/unified-runtime/tree/update-badges?tab=readme-ov-file#unified-runtime
> Update badges (for active workflows) in README

- source/mock/ur_mock_helpers.cpp
Avoid use after static destruction in sycl unittests by moving the initialization of `mock::callbacks` from static function scope to static global scope.
> Initalize mock callbacks earlier

- source/adapters/opencl/sampler.cpp
[INTEL/llvm](https://github.com/intel/llvm/pull/14769)
> Map ur_bool_t to cl_bool in sampler getinfo for opencl adapter

- CMakeLists.txt
The UR_FORCE_LIBSTDCXX option defaults to OFF can be used in situations where the build is configured to use libc++ but the libstdc++ ABI is required for stability reasons.
> Add option to force use of libstdc++ on Linux

- .github/workflows/scorecard.yml
The scorecard action must run on the official GitHub-hosted ubuntu runners...
This fixes:
```
2024/08/05 13:35:24 error sending scorecard results to webapp: http response 400, status: 400 Bad Request, error: {"code":400,"message":"workflow verification failed: scorecard job should have exactly 1 'Ubuntu' virtual environment, see https://github.com/ossf/scorecard-action#workflow-restrictions for details."}
```
currently happening on [main](https://github.com/oneapi-src/unified-runtime/actions/runs/10249788286/job/28353963030).
> fix scorecard job

- source/adapters/level_zero/v2/common.hpp
- source/adapters/level_zero/v2/event_provider_counter.cpp
- source/adapters/level_zero/v2/event_provider_counter.hpp
- source/adapters/level_zero/v2/event_provider_normal.cpp
- source/adapters/level_zero/v2/event_provider_normal.hpp
that encapsulate lifetime management logic (including support for ownZeHandle).
> [L0 v2] Add raii wrapper for L0 handles

- .github/workflows/cmake.yml
- CMakeLists.txt
- source/adapters/level_zero/v2/command_list_cache.cpp
- source/adapters/level_zero/v2/command_list_cache.hpp
- source/adapters/level_zero/v2/event_provider_normal.cpp
- source/common/CMakeLists.txt
- source/common/latency_tracker.hpp
This uses HdrHistrogram which is part of the public domain: https://github.com/HdrHistogram/HdrHistogram_c/blob/main/LICENSE.txt
The overhead of hdr_histogram seems to be acceptable: ~10ns for adding the value to histogram and few microseconds for creating the histogram (which happens once for every thread and for every measured scope). The creation overhead can be even smaller (a few hundred ns) if we tweak the configuration options for the histogram (at the cost of lower precision).
Sample output (run on https://github.com/oneapi-src/unified-runtime/pull/1894):
```
Latency histogram:
name,min,max,mean,stdev,p50,p90,p99,p99.9,p99.99,p99.999,p99.9999,unit
command_list_cache_t::getImmediateCommandList,88320,289791,189008,100656,88383,289791,289791,289791,289791,289791,289791,ns …
```
> [common] Histogram-based latency tracker

- source/adapters/cuda/memory.hpp
- source/adapters/mock/ur_mock.cpp
- source/common/ur_util.hpp
- source/loader/layers/sanitizer/asan_options.hpp
- source/loader/layers/sanitizer/asan_report.cpp
- source/loader/layers/validation/ur_leak_check.hpp
- test/adapters/level_zero/v2/command_list_cache_test.cpp
- test/conformance/memory/urMemImageCreate.cpp
- Fix 1574354 Uninitialized scalar field
- Fix 1594027 Uncaught exception
- Fix 1595568, 1595570 Use of auto that causes a copy
- Fix 1595594 Copy instead of move
- Fix 1595785 Use of auto that causes a copy
- Fix 1594597 Dereference after null check
- Fix 1595225 Data race condition
- Fix 1598473 Resource leak
- Fix 14 instances of Resource leak
- 1594026, 1594028, 1594029, 1594030, 1594031, 1594032, 1594033, 1594034,
1594035, 1594036, 1594037, 1595372, 1595373, and 1598546
> Fix various Coverity defects

- .github/workflows/e2e_level_zero.yml
- .github/workflows/e2e_opencl.yml
This should make the e2e jobs green for the time being.
> Suppress e2e test failures in L0 and OpenCL

- source/adapters/native_cpu/context.hpp
- source/adapters/native_cpu/usm.cpp
Implements `urUSMGetMemAllocInfo` and handles alignment requests in allocation functions.
Corresponding intel/llvm PR: https://github.com/intel/llvm/pull/14010
> [NATIVECPU] Implement urUSMGetMemAllocInfo and aligned alloc

- scripts/core/EXP-NATIVE-ENQUEUE.rst
Pedantic things I noticed while reading spec.
> Cosmetic tweaks to native enqueue spec

- include/ur_api.h
- scripts/templates/api.h.mako
On Windows the region name `usm import release (experimental)` cause compile errors in certain situations which look like this:
```
error C7586: a 'import' directive must end with a ';' on the same line
```
This patch replaces spaces with `_` in the region names to avoid this compile error.
> Make pragma region names joined by _

- source/adapters/cuda/CMakeLists.txt
All other uses of XPTI also use the static library. This fixes compilation issues with `dllimport/dllexport` on Windows.
> [CUDA] Don't import XPTI symbols in the plugin library

- source/adapters/level_zero/program.cpp
Right now we never return the build log for L0 on build failure because we only add `ZeBuildLog` to `ZeBuildLogMap` if `ZeResult` is `ZE_RESULT_SUCCESS`.
I was running a SYCL program that didn't build and noticed the the log was printed for OCL but not L0, so I debugged into why L0 wasn't and found this.
I manually confirmed this fixes it.
> [L0] Return the build log on compilation failure

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/common.cpp
- source/adapters/level_zero/common.hpp
- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
- Fixed the isDriverVersionNewerOrSimilar to use the new intel driver version string if it exists and use a tuple to compare the minimum and existing versions.
- Moved version check within the platform handle.
> [L0] Fix Driver Version check to use extension and tuple check

- source/adapters/level_zero/command_buffer.cpp
As discovered in https://github.com/oneapi-src/unified-runtime/pull/1951#issuecomment-2278519730 there is an issue running the command-buffer CTS tests on L0 with command-lists enabled.
After investigating, this was because the CTS tests we're not using the output event parameter to command-buffer enqueue. In the L0 adapter code a path for registering an event with the queue to waiting on the workload was guarded by this event being set. Therefore `urQueueFinish` was not working as expected, as the queue was not aware of this work to wait on.
Fixed by always registering the work to wait on with the queue, and miss out on propagation of the created event when user doesn't pass an output event, rather than not creating it at all.
DPC++ PR https://github.com/intel/llvm/pull/15035
> Command-buffer immediate command-list CTS fix

- scripts/core/INTRO.rst
- scripts/templates/valddi.cpp.mako
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/layers/validation/ur_validation_layer.hpp
Bounds checking can be an expensive operation to perform, especially for applications with heavy use of commands operating on USM allocations.
This patch adds a new layer specifically for USM bounds checking called UR_LAYER_BOUNDS_CHECKING. This was previously part of UR_LAYER_PARAMETER_VALIDATION.
By removing USM bounds checking from the default parameter validation the overhead of using parameter validation greatly decreases allowing it to be enabled in more situations.
> Make USM parameter bounds checking configurable

- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/usm.cpp
- Fixed recast of Queue object vs usage of variable.
- fixed usm alignment check such that == 0 is correctly skipped from buffer overrun checks.
- fixed cast to show no need to check the return from decrement and test in queue finish.
- fixed release of resources for bindless import on error.
> [L0] fix Coverity issues for L0 Adapter

- test/CMakeLists.txt
Default is enabled; this should not be a visible change without changing your cmake configuration.
> [CMake] Add flag to disable fuzztesting

- source/adapters/level_zero/CMakeLists.txt
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/helpers/kernel_helpers.cpp
- source/adapters/level_zero/helpers/kernel_helpers.hpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/kernel.hpp
to avoid code duplication between kernel.cpp and command_buffer.cpp and to enable code reuse with v2 adapter.
> [L0] move kernel helper functions to a separate file

- .github/workflows/coverity.yml
we can't install anything on the self-hosted runner, it's sudoless.
All required dependencies should be already there.
// Preview of this workflow on my fork - CMake configured properly
https://github.com/lukaszstolarczuk/unified-runtime/actions/runs/10386076621/job/28756560507
> [CI] Fix coverity workflow

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.hpp
- scripts/core/device.yml
- source/adapters/cuda/device.cpp
- source/adapters/hip/device.cpp
- source/adapters/level_zero/device.cpp
- source/adapters/mock/ur_mockddi.cpp
- source/adapters/native_cpu/device.cpp
- source/adapters/opencl/device.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/adapters/cuda/urDeviceCreateWithNativeHandle.cpp
- test/conformance/device/urDeviceCreateWithNativeHandle.cpp
It currently takes a platform handle, which is problematic for the sycl RT because its make_device api only takes a native handle, so to figure out the correct platform handle to pass at best we'd need to do some backend specific querying of the native object, but even then that isn't always possible as not all backends have a platform equivalent.
The platform handle does currently enable an optional (slightly) faster path to return the correct device in some adapter implementations but this isn't essential for them to work, so really its primary purpose is to serve as the wrapped UR handle for the loader to work. This purpose is equally well served by an adapter handle, which will also be a lot easier for the sycl rt to correctly provide.
> Change urDeviceCreateWithNativeHandle to take an adapter handle.

- include/ur_api.h
- scripts/core/kernel.yml
- source/adapters/mock/ur_mockddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
This identifies that the data pointed to needs to be copied, similar to clSetKerneLArg when it is by value.
> Improved wording of setKernelArgValue

- source/adapters/level_zero/device.hpp
Since device id is initialized later (not in ctor), make it optional to avoid using uninitialized value.
> [L0] make device id an optional

- source/adapters/level_zero/event.cpp
This change corresponds to the fix made in LLVM https://github.com/intel/llvm/pull/14123
With this change, the SYCL E2E test located at sycl/test-e2e/Regression/in_order_barrier_profiling.cpp will now pass.
> [L0] Fix incorrect profiling values for in-order queue barriers

- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/common.hpp
- Change zeInit usage to optionally init all driver types with all flags set, then
filter the drivers currently supported.
- Enables for L0 application to init all driver types which unblocks
other libraries using L0 drivers and enables for future use of other
driver types.
- Added Environment Variable UR_L0_INIT_ALL_DRIVERS which will set all
driver type flags when enabled.
> [L0] Enable L0 Driver Init to init all device types with filtering

- source/loader/layers/sanitizer/asan_interceptor.hpp
- source/loader/layers/sanitizer/stacktrace.cpp
- test/layers/validation/fixtures.hpp
- test/layers/validation/leaks.cpp
- test/loader/handles/fixtures.hpp
[DPC++ testing](https://github.com/intel/llvm/pull/15108)
> Fix some coverity issues

- source/adapters/level_zero/queue.cpp
this generates warning on clang
> [L0] remove unused capture from lambda

- source/adapters/level_zero/v2/event_provider_normal.cpp
ze_event_pool_counter_based_exp_desc_t was being used outside of the scope it was created in.
> [L0 v2] fix use-after-free

- source/adapters/level_zero/v2/event_pool.hpp
- test/adapters/level_zero/v2/event_pool_test.cpp
Fix compilation issue for L0 v2
> [L0 v2] fix use of device->Id

- source/common/linux/ur_lib_loader.cpp
Failing to load an adapter is not an error in most cases the adapter is just not present.
However there's a lot of other reasons why an adapter may fail to load, such as a missing driver library or an unsupported driver. In these cases `dlerror` output is crucial to troubleshoot the issue.
> Add dlerror output to loader logs

- source/adapters/cuda/image.cpp
- source/adapters/cuda/memory.cpp
- source/adapters/hip/memory.cpp
Ensure that handles are default initialised and checked before attempting to destroy.
DPC++ PR: [ [Bindless] Fix unintended crash in catch blocks #14966 ](https://github.com/intel/llvm/pull/14966)
> Fix unintended crash in catch blocks.

- source/adapters/cuda/queue.cpp
Do not increment `NumComputeStreams` / `NumTransferStreams` before `cuStreamCreateWithPriority` returns. Too early increment caused other threads to read the incremented count before a CUDA stream was created and try to use an invalid stream handle, causing crashes.
The construction:
```
if (condition) {
lock_this_scope
if (condition) {
create_object
update_condition
}
}
use_object
```
is only thread-safe if `update_condition` happens after `create_object` is completed. This PR ensures the ordering.
intel/llvm PR: https://github.com/intel/llvm/pull/15100
> Fix race condition in CUDA stream creation

- source/adapters/native_cpu/context.hpp
There was no mutex despite access the allocation details. This adds it (and remove const due to use of mutex).
> Fix missing mutex on get_alloc_info_entry

- source/adapters/native_cpu/threadpool.hpp
The lack of synchronization when closing threads in the Native CPU threadpool lead to sporadic hangs in some tests, this PR addresses it.
intel/llvm PR: https://github.com/intel/llvm/pull/15046
> [NATIVECPU] Add lock_guard when stopping threads

- .github/workflows/benchmarks_compute.yml
- .github/workflows/e2e_core.yml
These jobs were not properly setting `SYCL_UR_USE_FETCH_CONTENT`, and so were fetching UR when they should have been using the UR under test.
> In build jobs, properly disable UR downloads

- source/adapters/native_cpu/device.cpp
- source/adapters/native_cpu/device.hpp
Adds support for `UR_DEVICE_INFO_MAX_MEM_ALLOC_SIZE` on Native CPU.
intel/llvm PR https://github.com/intel/llvm/pull/14617
> [NATIVECPU] Support UR_DEVICE_INFO_MAX_MEM_ALLOC_SIZE

- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/kernel.hpp
getSuggestedLocalWorkSize is implemented in kernel_helpers.cpp
This should have been removed in https://github.com/oneapi-src/unified-runtime/pull/1958
> [L0] remove leftover, duplicated getSuggestedLocalWorkSize implementation

- source/loader/layers/tracing/ur_tracing_layer.cpp
- source/loader/layers/tracing/ur_tracing_layer.hpp
Global xptiContext was beeing (sometimes) destroyed before the tracing context (as both were global variables, their order of destruction was not guaranteed). This resulted in lost notifications as xptiFinalize was being called after xptiFrameworkFinalize.
Fix this by creating a global shared_ptr to the xptiContext. Bump the refcount of that pointer every time a context is created and decrease when it is destroyed to make sure that xptiFrameworkInitialize() is not beeing called before the last context is destroyed.
> [Loader] Fix xpti finalization order

- scripts/templates/valddi.cpp.mako
- source/loader/layers/sanitizer/asan_options.hpp
- source/loader/layers/validation/ur_leak_check.hpp
- source/loader/layers/validation/ur_valddi.cpp
These changes fix the coverity issue with possible race condition in `ur_leak_check.hpp` and use of copy in `asan_options.hpp`.
> Coverity fixes

- source/common/CMakeLists.txt
includes coverity fix for hwloc (https://github.com/oneapi-src/unified-memory-framework/pull/696).
> [UMF] Bump version to include coverity fix

- source/loader/CMakeLists.txt
- source/loader/layers/sanitizer/linux/symbolizer.cpp
- source/loader/layers/sanitizer/stacktrace.cpp
UR will force link with libstdc++, but in in-tree build, if LLVM is built with libc++, this will cause mismatch problem. So, in such case, we need to build symbolizer.cpp with libc++ abi and link libc++ in.
> [DeviceSanitizer] Fix libstdc++ and libc++ mismatch problem

- source/adapters/cuda/image.cpp
This patch fixes a crash due to urBindlessImagesImageGetInfoExp expecting a CUarray instead of a CUmipmappedArray.
> [Bindless][Exp] Fix urBindlessImagesImageGetInfoExp failing with mipmap images

- source/adapters/level_zero/device.cpp
- test/conformance/enqueue/enqueue_adapter_level_zero.match
- Enabled Immediate Command list usage per queue given Intel DG2 HW.
- Removed default setting of false on windows.
> [L0] Enable Immediate Command List by default given Intel DG2

- source/adapters/opencl/usm.cpp
- USM calls to alloc must return a nullptr and error given invalid alignment. This cannot be relied upon in the validation layer.
> [OpenCL] Fix USM alignment error check to occur always and return nulllptr

- source/adapters/level_zero/adapter.cpp
- source/common/logger/ur_sinks.hpp
As windows order of unloading dlls is reversed from linux, windows will call umfTearDown before it could release umf objects in level_zero, so we call umfInit on urAdapterGet and umfAdapterTearDown to enforce the teardown of umf
after umf objects are destructed.
[Intel/llvm PR](https://github.com/intel/llvm/pull/15182)
> Add umfInit/umfTearDown to urAdapterGet/urAdapterRelease

- source/adapters/level_zero/v2/common.hpp
- source/adapters/level_zero/v2/kernel.cpp
- source/adapters/level_zero/v2/kernel.hpp
- test/conformance/kernel/kernel_adapter_native_cpu.match
- test/conformance/kernel/urKernelRelease.cpp
as it's error prone to use - similarly to shared_ptr we should not create multiple instances of shared_handle from a single raw pointer.
Also, fix error in kernel.cpp: program handle was not being retained, leading to segfaults.
> [L0 v2] Remove ur_shared_handle

- third_party/deps.yml
While zlib is not linked into UR libraries, only one of the example applications, we should still avoid using versions with known CVEs.
> Bump to zlib version 1.3.1 used in examples

- .github/workflows/benchmarks_compute.yml
- scripts/benchmarks/benches/base.py
- scripts/benchmarks/benches/compute.py
to enable testing L0 v2 adapter which cannot be selected by ONEAPI_SELECTOR
> [Benchmark] use UR_ADAPTERS_FORCE_LOAD in benchmarks

- include/ur_api.h
- scripts/core/device.yml
- source/adapters/opencl/device.cpp
Previously, non-standard device queries (e.g., USM) were submitted to OpenCL devices without checking whether the device supports the extension. As a result, an exception was thrown from sycl::get_info.
Now, we more gracefully handle the case when OpenCL device does not have the extension needed:
- `UR_DEVICE_INFO_USM_*_SUPPORT`: Return all-false when the device does not support USM at all.
- `UR_DEVICE_INFO_SUB_GROUP_SIZES_INTEL`: Return `{1}`, like for the host device which also has no sub-groups.
- `UR_DEVICE_INFO_IP_VERSION`: Return `UR_RESULT_ERROR_UNSUPPORTED_ENUMERATION` instead of `UR_RESULT_ERROR_INVALID_VALUE`.
Also, fix the description of `SUB_GROUP_SIZES_INTEL` info query, since UR supports it on NVIDIA and AMD GPUs too.
> [CL] Make device queries more robust

- test/conformance/exp_command_buffer/fixtures.h
The CTS code for command-buffers on the L0 backend has a workaround that forces batched submission to be used rather than immediate submission.
However, both batch and immediate submission L0 command-lists are now supported, so this workaround is no longer required.
Tested by running on PVC which uses immediate command-lists by default. Also by manually setting env var `UR_L0_USE_IMMEDIATE_COMMANDLISTS` to both `1` and `0` when running the CTS tests.
> Remove command-buffer CTS L0 workaround

- source/adapters/level_zero/context.cpp
- Fix to the emplace call in the context such that the in order list property is not lost from the cache.
> [L0] Fix Command List Cache to correctly set In order List property

- source/adapters/opencl/CMakeLists.txt
Build in DPCPP is broken because of the below error caused by the upstream headers change.
Just use the previous commit from the one that breaks the build until the adapter code can be updated.
```
In file included from /__w/llvm/llvm/build/_deps/unified-runtime-src/source/adapters/opencl/adapter.cpp:11:
/__w/llvm/llvm/build/_deps/unified-runtime-src/source/adapters/opencl/common.hpp:317:29: error: 'cl_mutable_base_config_khr' does not name a type; did you mean 'cl_mutable_dispatch_config_khr'?
317 |                       const cl_mutable_base_config_khr *mutable_config);
```
> [OpenCL] Use older OpenCL-Headers commit to fix build

- scripts/core/INTRO.rst
- source/loader/ur_adapter_registry.hpp
- test/loader/adapter_registry/CMakeLists.txt
- test/loader/adapter_registry/fixtures.hpp
- test/loader/adapter_registry/prefilter.cpp
- Added Prefilter which uses ONEAPI_DEVICE_SELECTOR to remove backends that the user has not requested.
- this handles both the "Accept" or "Discard" filters that can be set in the ONEAPI_DEVICE_SELECTOR.
- Added tests verify the Accept/Discard use cases on Linux.
- Added UR_LOADER_PRELOAD_FILTER to toggle the prefilter on and off.
> [LOADER] Added Prefilter using ONEAPI_DEVICE_SELECTOR to remove backends

- source/common/latency_tracker.hpp
- source/common/ur_util.hpp
- test/unit/utils/CMakeLists.txt
- test/unit/utils/helpers.cpp
to the latency tracker.
Also show min, max and stdev value at the end - it makes it easier to quickly compare different outputs.
> [Common] Add total count and sum of latency measurements

- scripts/core/INTRO.rst
- source/adapters/level_zero/context.cpp
- source/loader/CMakeLists.txt
- source/loader/layers/sanitizer/linux/symbolizer.cpp
- source/loader/layers/sanitizer/stacktrace.cpp
- source/loader/ur_adapter_registry.hpp
- test/loader/adapter_registry/CMakeLists.txt
- test/loader/adapter_registry/fixtures.hpp
- test/loader/adapter_registry/prefilter.cpp
Includes the following PR:
* https://github.com/oneapi-src/unified-runtime/pull/2006
* https://github.com/oneapi-src/unified-runtime/pull/2062
* https://github.com/oneapi-src/unified-runtime/pull/2053
> Candidate for the v0.10.3 release tag

- source/adapters/cuda/device.cpp
- source/adapters/cuda/device.hpp
- source/adapters/cuda/kernel.cpp
This commit implements the experimental `urKernelSuggestMaxCooperativeGroupCountExp`, for the Cuda adapter, to retrieve the maximum number of cooperative groups that can be launched on the device.
Additionally, the changes also cache the result of the `CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT` Cuda driver query which is used to calculate the device wide maximum cooperative groups, because the Cuda occupancy query used has per SM (Multiprocessor) semantics.
Testing and related changes enabling querying this from SYCL: https://github.com/intel/llvm/pull/14333
> [CUDA] Implement urKernelSuggestMaxCooperativeGroupCountExp for Cuda

- source/adapters/opencl/device.cpp
The OpenCL driver doesn't report support for these extensions, but it does support them (at least to the extent that UR and SYCL require)
> Add workaround for silently supported OpenCL extensions on Intel FPGA

- source/adapters/level_zero/event.cpp
SYCL RT may sometimes ignore errors and call release on returned handles from failing functions. This patch makes sure that the OutEvent remains unmodified when the urEnqueueEventsWaitWithBarrier function returns an error.
> fix urEnqueueEventsWaitWithBarrier returning events on failures

- include/ur_print.hpp
- scripts/templates/print.hpp.mako
- test/unit/utils/params.cpp
Bool values were printed as ascii characters with code 0 or 1, leading to artifacts. This patch fixes this by printing either 'false' or 'true', depending on the bool's value.
This has been annoying me a while when analyzing logs from SYCL apps.
> fix ur_bool_t printing

- source/loader/layers/tracing/ur_tracing_layer.cpp
Due to a possible race between constructor and a global variable initialization, the ur.call XPTI stream would not be visible to components linking with UR.
> Fix XPTI initialization bug

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/v2/event_provider_normal.cpp
- source/adapters/level_zero/v2/queue_immediate_in_order.cpp
- source/loader/ur_lib.cpp
- test/adapters/level_zero/urKernelCreateWithNativeHandle.cpp
- test/conformance/context/urContextCreate.cpp
- test/conformance/device_code/indexers_usm.cpp
- test/conformance/device_code/linker_error.cpp
- test/conformance/exp_command_buffer/fixtures.h
- test/conformance/program/urProgramCreateWithIL.cpp
This fixes some warnings picked up by GCC 11 and Clang 20 when -Wextra is set. Note that -Wextra is not currently set on any command line - I'll do that separately as part of a more general "hardening" commit.
> [NFC] Warning squishing

- source/loader/ur_loader.cpp
@aarongreig 
Disables system errors when loading adapters on Windows, and re-enables them after.
> [Loader] Suppress system errors when loading adapters on Windows

- CMakeLists.txt
- source/adapters/opencl/usm.cpp
- source/common/CMakeLists.txt
- source/loader/layers/tracing/ur_tracing_layer.cpp
- source/loader/ur_loader.cpp
Includes the following PR:
* https://github.com/oneapi-src/unified-runtime/pull/2009
* https://github.com/oneapi-src/unified-runtime/pull/2011
* https://github.com/oneapi-src/unified-runtime/pull/2083
* https://github.com/oneapi-src/unified-runtime/pull/2086 (0.10.x only PR, not exist in main)
* https://github.com/oneapi-src/unified-runtime/pull/2060
> Candidate for the v0.10.4 release tag

- source/adapters/level_zero/event.cpp
- When a counter based event is created and is expected to be already signalled, then those events either need to be labelled as Completed==true or they need to be signalled on the device vs the host.
- Now, all places where host signal was skipped, those events are marked "Completed" such that those events will be skipped in the waitlist and in the case of the multi device, the event will be signalled on the device as part of the execute with the previous waitlist.
> [L0] Fix Counter Based Event Default signal given placeholder

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/queue.cpp
- Fix urEnqueueEventsWaitWithBarrier to avoid appending a wait on events given a waitlist, but driver in order lists.
- Driver in order lists gurantees this implicitly and is not needed.
> [L0] Fix urEnqueueEventsWaitWithBarrier for driver in order lists

- source/adapters/native_cpu/device.cpp
Adds support to `UR_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES` and `UR_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES` on Native CPU.
intel/llvm PR https://github.com/intel/llvm/pull/14619
> [NATIVECPU] Support atomic fence queries

- source/adapters/opencl/device.cpp
- source/adapters/opencl/kernel.cpp
- test/conformance/enqueue/urEnqueueKernelLaunch.cpp
- test/conformance/exp_command_buffer/buffer_saxpy_kernel_update.cpp
- test/conformance/exp_command_buffer/commands.cpp
- test/conformance/exp_command_buffer/ndrange_update.cpp
- test/conformance/exp_command_buffer/usm_fill_kernel_update.cpp
- test/conformance/exp_command_buffer/usm_saxpy_kernel_update.cpp
- test/conformance/kernel/urKernelGetGroupInfo.cpp
- Include array header when using std::array
- Make potentially lossy implicit conversions explicit
> Fix Windows CTS with kernels build

- CMakeLists.txt
- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/queue.cpp
> Candidate for the v0.10.5 release tag

- source/adapters/level_zero/image.cpp
- add support for UR_IMAGE_CHANNEL_ORDER_RGB and UR_IMAGE_CHANNEL_ORDER_RGX
> [L0] Add 3-channel image support

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/queue.cpp
-enable counter-based events for regular commandlist 
-counter-based events may be reused even though they are not done 
-when ref count goes to not used by external clients value it means that event may be reused by subsequent calls -move events that are no longer externally visible to re-usable pool and reuse those more aggressively
intel/llvm PR: https://github.com/intel/llvm/pull/14754
> [L0] Phase 2 of Counter-Based Event Implementation

- source/adapters/level_zero/kernel.cpp
Follow up to #2096 to update urEnqueueDeviceGlobalVariableRead as well.
> [L0] Fix urEnqueueDeviceGlobalVariableRead to use device specific modules

- scripts/templates/trcddi.cpp.mako
- source/common/logger/ur_logger_details.hpp
- source/loader/layers/tracing/ur_trcddi.cpp
In the current tracing layer, the parameters of the function being called are always printed to a string stream that may be used for logging. However, if logs are disabled, this just unnecessarily wastes times.
> fix perf regression in tracing layer

- CMakeLists.txt
- scripts/templates/trcddi.cpp.mako
- source/adapters/level_zero/kernel.cpp
- source/common/logger/ur_logger_details.hpp
- source/loader/layers/tracing/ur_trcddi.cpp
> Candidate for the v0.10.6 release tag

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/queue.cpp
Reverts oneapi-src/unified-runtime#1698
> Revert "[L0] Phase 2 of Counter-Based Event Implementation"

- source/adapters/opencl/CMakeLists.txt
- source/adapters/opencl/command_buffer.cpp
- source/adapters/opencl/common.hpp
Update OpenCL adapter code to reflect the 2 API breaking changes to the command-buffer family of extensions that have been made upstream:
* [Add properties parameter to all command-buffer commands](https://github.com/KhronosGroup/OpenCL-Headers/pull/260)
* [Use array for clUpdateMutableCommandsKHR](https://github.com/KhronosGroup/OpenCL-Headers/pull/245)
PR also contains fixes for CTS tests that have been added recently:
* Test passing a null handle to `urCommandBufferAppendKernelLaunchExp` checks for nullptr
* Test `urCommandBufferAppendMemBufferWriteExp` doesn't die (other unsupported commands in the adapter don't do this)
DPC++ PR https://github.com/intel/llvm/pull/15410
> Reflect upstream OpenCL command-buffer API changes

- source/adapters/level_zero/event.cpp
- test/adapters/level_zero/CMakeLists.txt
- test/adapters/level_zero/urEventCreateWithNativeHandle.cpp
This patch makes sure that only events from the exact same
cmdlists are filtered out when appending events to wait.
> Fix urEnqueueEventsWaitWithBarrier when used with interop events

- source/adapters/level_zero/event.cpp
This patch makes sure that only events from the exact same cmdlists are filtered out when appending events to wait.
> Fix urEnqueueEventsWaitWithBarrier when used with interop events (0.10.x)

- CMakeLists.txt
- source/adapters/level_zero/event.cpp
> Candidate for the v0.10.7 release tag

- source/adapters/cuda/event.cpp
Reintroduces the changes from commit https://github.com/oneapi-src/unified-runtime/commit/c4ae460f779021aa6840ea47a373f6ac336bc589, which were reverted in related merged commit https://github.com/oneapi-src/unified-runtime/commit/1b4a8b852c6b86545b42a71927f88c4fed107217 due to being mistakenly deleted and omitted on rebasing.
This happened because the former changes got split out from PR https://github.com/oneapi-src/unified-runtime/pull/1399 to independent changes in PR https://github.com/oneapi-src/unified-runtime/pull/1397.
> [Cuda] Reintroduce catching and reporting of bad_alloc for event object creation

- source/adapters/cuda/device.cpp
- source/adapters/hip/device.cpp
This PR closes https://github.com/oneapi-src/unified-runtime/issues/1660
> Update the bool return type for Cuda and HIP bool info queries

- source/adapters/level_zero/event.cpp
- fix multi device event creation to be enqueued as a barrier waiting on the original event keeping the multi device event valid.
- Avoid wait on events on a multi device event given driver in order due to p2p errors for driver in order lists. Barrier from multi device event creation will guarantee in order execution.
> [L0] Fix Multi Device Event handling and remove unhandled events from in order wait list

- source/adapters/level_zero/event.cpp
Includes the following PR:
* https://github.com/oneapi-src/unified-runtime/pull/2134
> Candidate for the v0.10.8 release tag

- include/ur_api.h
- scripts/core/INTRO.rst
- scripts/core/loader.yml
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/loader/loader_config/CMakeLists.txt
- test/loader/loader_config/urLoaderConfigCreate.cpp
- test/loader/loader_config/urLoaderConfigGetInfo.cpp
- test/loader/loader_config/urLoaderConfigSetCodeLocationCallback.cpp
- Add a null pointer check for urLoaderConfigCreate
- Add a null pointer and invalid size check for urLoaderConfigGetinfo
- Add invalid size test for urLoaderConfigGetInfo
- Add reference count test for urLoaderConfigGetInfo
- Add new test for urLoaderConfigSetCodeLocationCallback
- Add new test for UR_LOADER_CONFIG_INFO_AVAILABLE_LAYERS to test the list is valid (empty or valid values)
- Updated doc wording to say no layers are enabled by default
> Improvements to align CTS and Spec for Loader

- test/conformance/CMakeLists.txt
- test/conformance/cts_exe.py
This patch removes any empty ".match" files, and instructs ctest to
run the tests verbatim if there is no match file available.
As well as providing more useful output, this also handles the case
where the test startup and/or teardown causes the test runner to fail.
Previously, this would be ignored (as it produced no output).
> Don't use empty match test files

- include/ur_api.h
- scripts/core/adapter.yml
- source/adapters/mock/ur_mockddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/adapter/urAdapterGet.cpp
- test/conformance/adapter/urAdapterGetInfo.cpp
- test/conformance/adapter/urAdapterRelease.cpp
- test/conformance/adapter/urAdapterRetain.cpp
https://github.com/intel/llvm/pull/15513
- Add missing error condition to urAdapterGet which is mentioned in its description.
- Return UR_RESULT_ERROR_INVALID_SIZE when NumEntries == 0 and phAdapters != NULL.
- Check adapter reference count is updated accordingly after calls to urAdapterRetain/Release.
- Update urAdapterGetInfo tests
- ReferenceCountNotZero to check adapter reference count is not 0.
- ValidAdapterBackend to check UR_ADAPTER_INFO_BACKEND returns a value enumerated in ur_adapter_backend_t.
> Improvements to align CTS and Spec for Adapter

- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/adapter.hpp
- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/platform.hpp
- test/conformance/device/device_adapter_level_zero.match
- Change to using zesInit and zes data structures for accessing L0
SysMan functionality.
- Updated Platform & Devices to store zes handles if sysman support is
available.
- Given Legacy Environment Variable from user, then fallback to
old functionality.
- Fixed Return code on error to be consistently unsupported enumeration.
> [L0] Use zesInit for SysMan API usage

- source/adapters/cuda/command_buffer.cpp
- source/adapters/hip/command_buffer.cpp
`UR_CHECK_ERROR` will throw an exception if an error is found, so it should only be used within a try/catch block, otherwise the exception may leak out of the adapter.
> [CUDA][HIP] Fix exceptions throwing from adapter

- .github/workflows/multi_device.yml
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/memory.hpp
- test/conformance/memory-migrate/urMemBufferMigrateAcrossDevices.cpp
- To ensure buffers are always updated with the correct buffer values, track the dependencies as a prerequisite before performing the memory copy.
> [L0] Pass and track event dependencies required before executing Memory Copy buffer inits

- test/conformance/enqueue/enqueue_adapter_opencl.match
- test/conformance/enqueue/urEnqueueKernelLaunch.cpp
- test/conformance/integration/QueueEmptyStatus.cpp
- test/conformance/integration/integration_adapter_opencl.match
- test/conformance/testing/include/uur/fixtures.h
Turns out this was just a minor error in fixture usage and not allowing for an optional query to be unsupported.
Also remove an unneeded entry in the enqueue match file.
> Fix integration tests for CL.

- .github/workflows/cmake.yml
- .github/workflows/source-checks.yml
The "Build - Ubuntu" job has a stage that checks the source generated
from the spec matches the version stored in the repo. This is the
part of the job that takes the longest, and is ran multiple times.
Since it doesn't require a build, it has been brought out into its own
workflow which is only ran once. This should hopefully speed up builds.
> Split source checks into a seperate workflow

- test/loader/loader_config/urLoaderConfigGetInfo.cpp
This file uses `std::find` which is part of `<algorithm>` but it wasn't including it. This causes build failures with gcc 14.
> Fix missing include in loader config test

- source/adapters/cuda/image.cpp
- source/adapters/cuda/image.hpp
The specialised formats, CU_AD_FORMAT_{U|S}NORM_INT{8|16}X{1|2|4}, used to specify a format that is normalized, cannot be applied to images backed by USM memory, causing a failure. This commit addresses that issue by using the standard integer formats and making sure the CU_TRSF_READ_AS_INTEGER flag is set appropriately.
Another issue fixed here is that users with CUDA toolkits pre 11.5 are unable to enable normalized types due to the specialised formats being introduced in CUDA 11.5.
Associated DPC++ PR which tests for this: https://github.com/intel/llvm/pull/15299
> [CUDA][Bindless] Address USM normalized type image creation failure and functionality

- CMakeLists.txt
- source/adapters/cuda/command_buffer.cpp
- source/adapters/hip/command_buffer.cpp
- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/adapter.hpp
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/memory.hpp
- source/adapters/level_zero/platform.hpp
- test/conformance/device/device_adapter_level_zero.match
- test/conformance/memory-migrate/urMemBufferMigrateAcrossDevices.cpp
> Candidate for the v0.10.9 release tag

- scripts/templates/trcddi.cpp.mako
- source/loader/layers/tracing/ur_trcddi.cpp
- test/layers/tracing/hello_world.out.logged.match
Fix https://github.com/oneapi-src/unified-runtime/issues/2002 issue.
When merged this PR will make regular UR calls tracing being printed calls in two separate lines like PI does.
> Fix mixed output of adapter and regular traces

- test/conformance/sampler/urSamplerCreate.cpp
- test/conformance/sampler/urSamplerCreateWithNativeHandle.cpp
- Add test for checking UR_RESULT_ERROR_INVALID_NULL_POINTER return conditions for urSamplerCreate
- Add test for checking UR_RESULT_ERROR_INVALID_NULL_HANDLE/POINTER return conditions for urSamplerCreateWithNativeHandle
- Add tests for owned/unowned native handles when using urSamplerCreateWithNativeHandle
> Improvements to align CTS and Spec for Sampler

- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/memory.hpp
- Refcnt the Parent Buffer on Sub Buffer Creation to avoid free until
after all sub buffers are released.
- Avoid use after free of buffers by tracking if a buffer has already
been called with free() and verify that the parent of a sub buffer has
not already been released before attempting to get ze handles from the
parent.
- In either use after free case, die aborts before the memory is accessed.
> [L0] Refcnt Parent Buffer on Sub Buffer Create and die on use of buffer after free

- source/common/umf_helpers.hpp
- test/conformance/cts_exe.py
- test/layers/validation/fixtures.hpp
- excessive semicolons
- unused variables
- use python3.6 friendly "universal_newlines" alias instead of "text" param
> [common] fixed some compilation warnings

- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/memory.hpp
> Candidate 2 for the v0.10.9 release tag

- source/adapters/level_zero/device.cpp
Bindless image support is only supported on intel DG2 or newer GPU. In addition, it also requires basic image support queried from ZeDeviceImageProperties.
SYCL PR: https://github.com/intel/llvm/pull/15211
> [L0] Fix device query of bindless image support

- .github/workflows/build-hw-reusable.yml
- cmake/helpers.cmake
- source/adapters/cuda/CMakeLists.txt
- source/adapters/hip/CMakeLists.txt
- source/adapters/level_zero/CMakeLists.txt
- source/adapters/native_cpu/CMakeLists.txt
- source/adapters/opencl/CMakeLists.txt
- source/loader/CMakeLists.txt
- test/CMakeLists.txt
- test/adapters/level_zero/CMakeLists.txt
Add installing adapters. It is needed by https://github.com/oneapi-src/unified-runtime/pull/2146 and was already reviewed there and was just extracted to this separate PR (with some kind of test added).
> Install adapters by cmake

- .github/workflows/benchmarks_compute.yml
- scripts/benchmarks/benches/base.py
- scripts/benchmarks/benches/compute.py
- scripts/benchmarks/main.py
- scripts/benchmarks/utils/utils.py
Utilize support for using UR binary through find_package added in  https://github.com/intel/compute-benchmarks/pull/21
Before this change compute-benchmarks always builds UR from sources which is unnecessary since we already build UR as part of SYCL on UR CI.
Add installing adapters by "cmake --install" which is needed by new benchmarks code.
> Compute-benchmarks use already compiled UR

- source/adapters/hip/enqueue.cpp
LLVM testing https://github.com/intel/llvm/pull/12481
> [HIP] Refactor error handling in enqueue.cpp

- source/adapters/cuda/device.cpp
- source/adapters/hip/device.cpp
It seems that the extension string SYCL RT checks for was changed by this commit https://github.com/intel/llvm/commit/0939f39818225ce3e469e08f6a45711b449a8ad4 in PI, but the change never made it to the UR adapters.
> Report correct extension string for devicelib assert in cuda + hip.

- source/adapters/hip/kernel.cpp
- source/adapters/opencl/kernel.cpp
intel/llvm: https://github.com/intel/llvm/pull/15369
> [UR][hip][opencl] Mark urKernelSuggestMaxCooperativeGroupCountExp as unsupported instead of returning misleading default value

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/program.yml
- source/adapters/cuda/program.cpp
- source/adapters/hip/program.cpp
- source/adapters/level_zero/program.cpp
- source/adapters/native_cpu/program.cpp
- source/adapters/opencl/program.cpp
- test/conformance/program/program_adapter_cuda.match
- test/conformance/program/program_adapter_native_cpu.match
- test/conformance/program/program_adapter_opencl.match
- test/conformance/program/urProgramGetInfo.cpp
Also make returns for this consistent across adapter implementations (i.e. actual IL if that's supported, otherwise return UNSUPPORTED_ENUMERATION).
resolves #1138
LLVM testing https://github.com/intel/llvm/pull/12265
> Replace PROGRAM_INFO_SOURCE with PROGRAM_INFO_IL.

- source/loader/layers/sanitizer/asan_report.cpp
LLVM: https://github.com/intel/llvm/pull/15469
I forgot to increase "ArgIndex" on some types of invalid argument error.
This patch fix this.
> [DeviceSanitizer] Fix invalid-argument lit tests failure

- source/adapters/cuda/program.cpp
This patch fixes the following build error on Windows:
```
source\adapters\cuda\program.cpp(73): error C2079: 'WorkGroupElements' uses undefined class 'std::array<uint32_t,3>'
```
Technically only `<array>` was sufficient for resolving it, but it's better to include everything that the file relies on.
> [NFC][CUDA] Include STL headers in program.cpp

- test/conformance/context/context_adapter_level_zero.match
- test/conformance/context/urContextCreateWithNativeHandle.cpp
- test/conformance/device/device_adapter_cuda.match
- test/conformance/device/device_adapter_hip.match
- test/conformance/device/device_adapter_level_zero.match
- test/conformance/device/device_adapter_level_zero_v2.match
- test/conformance/device/device_adapter_opencl.match
- test/conformance/device/urDeviceCreateWithNativeHandle.cpp
This would fix the successWithUnOwnedNativeHandle tests as the reference count returned should be related to the UR object not the native handle so it should be tested to be `1` not `2`.
> Fix successWithUnOwnedNativeHandle tests

- test/conformance/cts_exe.py
Lines read already have newlines, so don't need the implicit newline added by calling `print` in a loop over the lines. One call to print with one newline is cheaper and doesn't add the double newlines.
> Don't double-space captured output in test wrapper

- .github/workflows/cmake.yml
- CMakeLists.txt
- README.md
- cmake/helpers.cmake
- scripts/check-hardening.sh
- source/adapters/level_zero/CMakeLists.txt
- source/loader/layers/tracing/ur_tracing_layer.cpp
- test/adapters/level_zero/zeCallMap.cpp
- test/conformance/exp_command_buffer/fixtures.h
UR_DEVELOPER_MODE has also been changed to only set Werror. The
previous other flags set by this variable either have no effect
(-fno-omit-frame-pointer) or are now always enabled
(-fstack-protector-strong).
Some smaller warnings have also been fixed.
> Hardening flags

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/common.yml
- scripts/core/kernel.yml
- scripts/core/program.yml
- source/adapters/cuda/kernel.cpp
- source/adapters/cuda/ur_interface_loader.cpp
- source/adapters/native_cpu/kernel.cpp
- source/adapters/opencl/common.cpp
- source/adapters/opencl/kernel.cpp
- source/adapters/opencl/ur_interface_loader.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/kernel/kernel_adapter_native_cpu.match
- test/conformance/kernel/urKernelSetSpecializationConstants.cpp
- test/conformance/program/program_adapter_cuda.match
- test/conformance/program/program_adapter_hip.match
- test/conformance/program/program_adapter_level_zero.match
- test/conformance/program/program_adapter_level_zero_v2.match
- test/conformance/program/program_adapter_native_cpu.match
- test/conformance/program/urProgramSetSpecializationConstants.cpp
Two main changes to how `Kernel/ProgramSetSpecializationConstants` are handled:
* They may now output either `INVALID_VALUE` or the new `INVALID_SPEC_ID` when the provided list is invalid.
* The OpenCL and level 0 adapters now respond to `UR_DEVICE_INFO_KERNEL_SET_SPECIALIZATION_CONSTANTS` with `false` rather than erroring out. This fixes some tests that were incorrectly not being skipped.
* `urKernelSetSpecializationConstants` now "implemented" (as a function that returns `UNSUPPORTED_FEATURE` for opencl and cuda.
> [Spec Constants] Improved handling of invalid spec. constants

- include/ur_api.h
- scripts/core/enqueue.yml
- scripts/core/exp-bindless-images.yml
- scripts/core/exp-command-buffer.yml
- scripts/core/exp-cooperative-kernels.yml
- scripts/core/exp-enqueue-timestamp-recording.yml
- scripts/core/exp-launch-properties.yml
- scripts/core/exp-native-enqueue.yml
- source/adapters/mock/ur_mockddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
Updated the spec to state that "If phEventWaitList and phEvent
are not NULL, phEvent must not refer to an element of
the phEventWaitList array."
This is required for OpenCL, and probably makes sense for other
backends as well.
> Update spec to clarify event list contents

- test/conformance/CMakeLists.txt
This was incorrectly using TEST_NAME rather than tname.
> Properly set up test environment for CTS

- cmake/helpers.cmake
Cross-compilation toolchains may not support `-fcf-protection=full` which can cause build failures. This patch fixes the issue by checking if the compiler emits an error when the option is uses instead of using compiler version ranges.
Fixes #2201
> Check if compiler supports -fcf-protection=full

- source/adapters/native_cpu/usm.cpp
It only contained `static` functions so it just made uses within the same TU more cumbersome.
> Remove superfluous namespace

- source/adapters/native_cpu/usm.cpp
It's plausible that a user will pass a non-null `ur_usm_desc_t` argument that itself has a zero `align` member. We need to gracefully accept such a case.
> Fix unspecified alignment

- source/adapters/native_cpu/program.cpp
Currently `urProgramCompile` and `urProgramLink` are basically no-ops on Native CPU.
intel/llvm PR: https://github.com/intel/llvm/pull/15616
> [NATIVECPU] Report success for urProgramCompile and urProgramLink

- .github/workflows/cmake.yml
I noticed in the Actions page of a PR that the macos-12 build job would be deprecated soon (seen in #2149) and have just seen a further notice (under Annotations in [this PR](https://github.com/oneapi-src/unified-runtime/actions/runs/11365211313/job/31619043571) with a link to a [Github announcement](https://github.com/actions/runner-images/issues/10721) that the job will start to get deprecated from November:
> GitHub Actions is starting the deprecation process for macOS 12. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 10/7/24 and the image will be fully unsupported by 12/3/24
> 
> To raise awareness of the upcoming removal, we will temporarily fail jobs using macOS 12. Builds that are scheduled to run …
> Remove soon to be deprecated macos-12 job

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/event.hpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/queue.hpp
- Remove all the default constructor inits to address error prone code changes and force setting of options and flags individually.
> [L0] Refactor to remove default constructor inits

- CMakeLists.txt
- test/conformance/CMakeLists.txt
- test/conformance/source/environment.cpp
> [NFC] Don't run conformance tests on mock adapter

- README.md
- test/adapters/CMakeLists.txt
- test/conformance/CMakeLists.txt
- test/layers/tracing/CMakeLists.txt
- test/loader/CMakeLists.txt
- test/loader/platforms/CMakeLists.txt
- test/tools/urtrace/CMakeLists.txt
CMake's `add_test` doesn't actually support a `DEPENDS` parameter, so
removed it. Also updated the README with instructionts on running the
tests which explicitly calls out that you should run `make` before the
tests.
> [NFC] Remove "dependencies" on tests

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/event.hpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/queue.hpp
Reverts oneapi-src/unified-runtime#2063 due to [this issue](https://github.com/intel/llvm/pull/15309#issuecomment-2422204809).
> Revert "[L0] Refactor to remove default constructor inits"

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/EXP-COMMAND-BUFFER.rst
- scripts/core/exp-command-buffer.yml
- source/adapters/cuda/command_buffer.cpp
- source/adapters/hip/command_buffer.cpp
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/mock/ur_mockddi.cpp
- source/adapters/opencl/command_buffer.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/exp_command_buffer/update/invalid_update.cpp
- Attempting to obtain a command handle when the command buffer is not updatable is now an error across all adapters
- command-buffer spec and adapter code updated to reflect this
- invalid_update CTS test updated to reflect new behaviour
> [EXP][CMDBUF] Make command handle behaviour consistent

- source/loader/layers/sanitizer/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan_libdevice.hpp
- source/loader/layers/sanitizer/common.hpp
intel/llvm part: https://github.com/intel/llvm/pull/15773
> [DeviceASAN] Move GlobalShadowOffset, DeviceType, Debug into LaunchInfo

- .github/codeql/codeql-config.yml
- .github/workflows/codeql.yml
- .github/workflows/trivy.yml
- cmake/FetchLevelZero.cmake
Reverts oneapi-src/unified-runtime#2208
> Revert "update to L0 loader version v1.18.3 and don't scan _deps with Trivy or CodeQL"

- source/adapters/opencl/CMakeLists.txt
- source/adapters/opencl/usm.cpp
- source/adapters/opencl/usm.hpp
- test/conformance/enqueue/urEnqueueUSMMemcpy.cpp
https://github.com/intel/llvm/pull/15189
> Support device to device USM copies with the CL adapter.

- source/adapters/opencl/program.cpp
- test/conformance/program/program_adapter_opencl.match
clCreateProgramWithIL only returns CL_INVALID_VALUE in three specific cirumstances, based on this we can deduce a more informative error code when we get that return.
Fixes the urProgramCreateWithILTest.BuildInvalidProgram cts test.
> Return more accurate errors from CL's ProgramCreateWithIL

- source/adapters/opencl/enqueue.cpp
- test/conformance/enqueue/enqueue_adapter_opencl.match
The CL spec wording on this is kind of fuzzy but every CL driver I tested (across intel, amd, nvidia cpu + gpu) returns an error when you have a local size set in the program source/IL and you don't specify any local size in your clEnqueueNDRangeKernel call (i.e. you leave it as NULL).
Our spec does allow you to leave local size as null if you have a size specified in your program, so this change adds some logic to query out the size set in the program and passes it to the enqueue call.
Initially I was concerned this might impact performance of current users but it looks like SYCL always passes a local size when calling urEnqueueKernelLaunch so it won't hit the path with the extra query.
> Query out and use local size set in program IL in CL adapter.

- test/conformance/platform/platform_adapter_cuda.match
- test/conformance/platform/platform_adapter_hip.match
- test/conformance/platform/platform_adapter_native_cpu.match
- test/conformance/platform/urPlatformCreateWithNativeHandle.cpp
This test calls `urPlatformGetNativeHandle`, which may report that the
feature is unsupported. Skip this test if the feature is unavailable.
> Add guards to InvalidNullPointerPlatform

- source/adapters/level_zero/kernel.cpp
- test/conformance/kernel/urKernelGetInfo.cpp
Currently L0 adapter returns garbage value for that property because string is incorrectly copied to the output buffer. Probably ur::getInfo implementation should be fixed to handle such cases properly.
> [L0] Fix UR_KERNEL_INFO_ATTRIBUTES returned value

- source/loader/layers/sanitizer/asan_report.cpp
- source/loader/layers/sanitizer/asan_shadow.cpp
- source/loader/layers/sanitizer/asan_shadow.hpp
Also, print out the triggering address in the error report.
> [DeviceAsan] Enlarge nullpointer redzone to better detect problem

- source/adapters/level_zero/adapter.cpp
- Enable ZES_ENABLE_SYSMAN=1 by default unless
UR_L0_ENABLE_SYSMAN_ENV_DEFAULT==0.
- Allows for Sysman support thru zeInit() without user input.
- Added UR_L0_ENABLE_ZESINIT_DEFAULT to allow for a customer to enable
zesInit over sysman env init if the env allows it.
- NOTE: UR_L0_ENABLE_ZESINIT_DEFAULT=1 requires
UR_L0_ENABLE_SYSMAN_ENV_DEFAULT==0 due to the env overwriting the
zesInit support.
> [L0] Enable Sysman Thru Env by default and have zesInit be optional

- source/adapters/cuda/command_buffer.cpp
- source/adapters/hip/command_buffer.cpp
- test/conformance/exp_command_buffer/update/kernel_handle_update.cpp
The command-buffer binary update implementation wasn't handling passing nullptr to hNewKernel properly. This PR fixes this issue.
intel/llvm PR: https://github.com/intel/llvm/pull/15569
> Fix command-buffer binary update implementation

- CMakeLists.txt
- source/adapters/level_zero/adapter.cpp
- Add changes from https://github.com/oneapi-src/unified-runtime/pull/2242
> Update v0.10.x to v0.10.10

- cmake/helpers.cmake
Similar to #2202, check if the host compiler supports the `-fstack-clash-protection` flag rather than using version ranges.
> Check if compiler supports -fstack-clash-protection

- include/ur_api.h
- scripts/core/platform.yml
- source/adapters/opencl/platform.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/platform/urPlatformGet.cpp
The OpenCL function clGetPlatformIDs may return CL_INVALID_VALUE, which
needs to be converted into appropriate UR returns as follows:
* If a non-null platforms list is provided, but the number of elements
in it is 0, then return UR_RESULT_ERROR_INVALID_SIZE.
* If neither platform or sizes outputs are provided, then return
UR_RESULT_ERROR_INVALID_VALUE.
This required a spec change.
This fixes a bug Intel are tracking internally as URT-831.
> Handle INVALID_VALUE in OCL urPlatformGet

- CMakeLists.txt
- examples/collector/collector.cpp
- source/loader/layers/tracing/ur_tracing_layer.cpp
- test/layers/tracing/test_collector.cpp
This avoids the overhead of preparing data for xpti, and the cost of the xpti call itself, if nothing is subscribed to the ur.call xpti call stream.
> don't call xpti if there are no subscribers

- CMakeLists.txt
- examples/collector/collector.cpp
- source/loader/layers/tracing/ur_tracing_layer.cpp
- test/layers/tracing/test_collector.cpp
Includes:
- https://github.com/oneapi-src/unified-runtime/pull/2230
> Candidate for the v0.10.11 release tag

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/memory.hpp
- Only use copy engines given discrete devices for Memory Copy.
- Given non D2D memory copy, then copy engines are preferred only when the device has both copy and link copy engine ordinals active.
- The above logic changes provide for the best performance when using copy engines in memory copy across device types.
> [L0] Refactor Copy Engine Usage checks for Performance

- source/adapters/opencl/device.cpp
As per [OpenCL docs](https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clGetDeviceInfo.html), `CL_DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS` is missing in OpenCL versions prior to 2.1. This change adds a check to the OpenCL version to ensure it is newer than 2.1, otherwise returning a default value for independent forward progress.
> [OpenCL] Add OpenCL version check for independent forward progress query

- test/conformance/cts_exe.py
It now shows the error code and a sampler of the output on CI.
> Improve cts_exe.py formatting

- include/ur_api.h
- scripts/core/exp-command-buffer.yml
- source/adapters/cuda/command_buffer.cpp
- source/adapters/hip/command_buffer.cpp
- test/conformance/device_code/CMakeLists.txt
- test/conformance/device_code/saxpy_usm_local_mem.cpp
- test/conformance/exp_command_buffer/CMakeLists.txt
- test/conformance/exp_command_buffer/exp_command_buffer_adapter_native_cpu.match
- test/conformance/exp_command_buffer/update/local_memory_update.cpp
- Fix handling of local mem args in CUDA/HIP for command buffer update
- Add conformance tests which check updating local memory args and work size
> [CMDBUF] Fix incorrect handling of shared local mem args in CUDA/HIP

- .github/workflows/build-hw-reusable.yml
- .github/workflows/cmake.yml
- test/conformance/adapter/adapter_adapter_native_cpu.match
- test/conformance/event/event_adapter_native_cpu.match
- test/conformance/event/event_adapter_opencl.match
This expands our CI to test the loader; the dispatcher that is
used when multiple adapters are available.
The old "run on hardware" jobs should behave the same (they have
the loader tests disabled), but there are new "combined" jobs
with OpenCL/Level Zero + Native CPU.
Closes: #2081
> [CI] Add "loader" support to conformance testing

- source/adapters/hip/platform.cpp
Without any default device in the current thread, all base events were associated with device 0, causing failures when used on other devices. Fix this by calling `hipSetDevice` before recording the event.
This issue was [reported by a user](https://support.codeplay.com/t/amd-gpu-sycl-plugin-urdevicegetglobaltimestamps-error/743) who was running on a system with two AMD GPUs and tried to do the following:
```cpp
#include <sycl/sycl.hpp>
int main() {
auto Devs = sycl::device::get_devices(sycl::info::device_type::gpu);
std::vector<sycl::queue> Queues;
for (auto D : Devs) {
Queues.push_back(sycl::queue{D,sycl::property::queue::enable_profiling{}});
}
}
```
Resulting in
```
UR HIP ERROR:
Value:           400
Name:            hipErrorInvalidHandle
Description:     invalid resource handle …
```
> Set the right HIP device before creating base event counter

- .github/workflows/benchmarks-reusable.yml
The benchmarks script is now run with its working directory set to ur-repo so that the scripts can figure out the commit hash. This means that the output markdown is now stored in a different location.
> fix path to markdown results in benchmarks workflow

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/opencl/command_buffer.cpp
- test/conformance/exp_command_buffer/exp_command_buffer_adapter_native_cpu.match
- test/conformance/exp_command_buffer/update/usm_saxpy_kernel_update.cpp
Fixes bug where passing nullptr to hNewKernel results on UR_RESULT_ERROR_UNSUPPORTED_FEATURE being returned.
intel/llvm: https://github.com/intel/llvm/pull/15998/files
> [Command-Buffer] Fix update validation for L0 and OpenCL

- source/ur/ur.hpp
If UrReturnHelper's `operator()` is explicitly called as `operator()<T>(...)`, there is a potential for ambiguity when the specified `RetType` and the inferred `T` are the same: this is ambiguous with the version of `operator()` where only `T` is a template parameter, and `T` is specified explicitly. We already have code that explicitly calls `operator()<T>(...)`, so prevent this from becoming a problem.
I saw this in an unsupported DPC++ build configuration, 32-bit x86, but expect it to come up in future supported DPC++ build configurations as well.
Note: IMHO, the fact that this is so awkward to call suggests to me that this possibly should not be an overload of `operator()` in the first place, but changing that does have the potential to break things, so I just left that as it is now.
> Avoid potential ambiguity in UrReturnHelper

- scripts/benchmarks/benches/compute.py
Add more MemcpyExecute cases - with src/dst buffers on USM to decrease run-to-run variance.
> [Benchmarks] update compute-benchmarks

- test/conformance/exp_command_buffer/exp_command_buffer_adapter_native_cpu.match
- test/conformance/exp_command_buffer/update/usm_fill_kernel_update.cpp
No matching DPC++ PR as this only touches the UR CTS
> Command-Buffer CTS test for updating kernel pointer argument to a nullptr

- test/conformance/context/urContextCreateWithNativeHandle.cpp
- test/conformance/device/urDeviceCreateWithNativeHandle.cpp
- test/conformance/event/urEventCreateWithNativeHandle.cpp
- test/conformance/kernel/urKernelCreateWithNativeHandle.cpp
- test/conformance/platform/urPlatformCreateWithNativeHandle.cpp
- test/conformance/queue/urQueueCreateWithNativeHandle.cpp
- test/conformance/sampler/urSamplerCreateWithNativeHandle.cpp
- test/conformance/testing/include/uur/fixtures.h
`UUR_ASSERT_SUCCESS_OR_UNSUPPORTED` previously leaked a `status`
variable to the calling scope. This change makes it no longer do that.
> [NFC] Make macro in conf. test no longer leak

- source/adapters/level_zero/v2/queue_immediate_in_order.cpp
urKernelSuggestMaxCooperativeGroupCountExp  will be implemented after https://github.com/oneapi-src/unified-runtime/pull/2277 is merged.
> [L0 v2] implement enqueueCooperativeKernelLaunchExp

- source/adapters/cuda/enqueue.cpp
- source/adapters/hip/enqueue.cpp
Change the implementation of `commonMemSetLargePattern` to use the largest pattern word size supported by the backend into which the pattern can be divided. That is, use 4-byte words if the pattern size is a multiple of 4, otherwise use 2-byte words for even sizes and 1-byte words for odd sizes.
Keep the idea of filling the entire destination region with the first word, and only start strided fill from the second, but implement it correctly. The previous implementation produced incorrect results for any pattern size which wasn't a multiple of 4. For example, a pattern of `std::array<uint8_t,5>{{1,2,3,4,5}}` produced `1 2 3 4 5 2 3 4 1 5 3 4 1 2 5 ...` instead of `1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 ...`. 
For HIP, the strided fill remains to be always in 1-byte increments because HIP API …
> Fix incorrect outputs and improve performance of commonMemSetLargePattern

- source/adapters/opencl/adapter.cpp
It should have been using the stringizing operator like the linux path.
> Fix the CL_CORE_FUNCTION macro on windows.

- .github/workflows/cmake.yml
They currently break in our CI (#2348).
> Temporarily disable clang-cl builds on Windows

- CMakeLists.txt
Previously we defined options after including `helpers.cmake`. However,
on the first cmake invocation, this means that it doesn't have
visibility of the default values.
This defines the options before the import, so they are visible to
`helpers.cmake`.
> Set cmake options before including helpers

- source/adapters/level_zero/v2/event.cpp
This is a regression after recent refactoring of events to use flags instead of boolean args.
> [L0 v2] don't reset counter-based events

- include/ur_print.hpp
Recent API change required a regeneration that https://github.com/oneapi-src/unified-runtime/pull/2240 didn't include (but wasn't conflicting).
This patch just runs the generate target.
> fix UR build, re-generate print API

- source/common/CMakeLists.txt
We don't need it, and this saves a repo fetch and some compile time.
> Don't build level zero provider in non-l0 builds

- source/adapters/opencl/device.cpp
- test/conformance/device/urDevicePartition.cpp
In `urDevicePartition` in the OpenCL adapter we loop through the array of properties but were not actually indexing into the array, only using the first element of the array.
Also added a new CTS test to verify this behaviour.
https://github.com/intel/llvm/pull/16083
> Index into property array in urDevicePartition for OpenCL

- source/adapters/level_zero/program.cpp
- test/conformance/program/program_adapter_native_cpu.match
- test/conformance/program/urProgramGetGlobalVariablePointer.cpp
I.e. make behavior similar to urProgramGetFunctionPointer. 
intel/llvm PR: https://github.com/intel/llvm/pull/16156
> [L0] Check that program is in exe state in urProgramGetGlobalVariablePointer

- source/common/windows/ur_lib_loader.cpp
This primarily improves the logging when loading an adapter fails on Windows by printing out the result of `GetLastError()` when `LoadLibrarExA()` returns null for cross-reference with https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes.
> Improve logging of loading adapters on Windows

- .github/workflows/build-fuzz-reusable.yml
- cmake/FetchLevelZero.cmake
- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/adapter.hpp
- test/loader/platforms/CMakeLists.txt
- As of v1.10 of the L0 spec, zeInit and zeDriverGet is the old init pathway and the desired init api is zeInitDrivers. This new api allows for multi heterogenous drivers to coexist in a single L0 Process.
> [L0] Implement Support for zeInitDrivers

- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/adapter.hpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
- Use the MCL 1.1 spec extensions instead of the driver experimental extensions when available.
> [L0] Add support for the MCL 1.1 apis thru the spec extensions

- .github/workflows/build-hw-reusable.yml
This was previously broken, but a CI node configuration update fixes it.
Closes: #2309
> [NFC] Enable CFI sanitation on CUDA CI nodes

- scripts/core/EXP-COMMAND-BUFFER.rst
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/command_buffer.hpp
- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
- Implement kernel binary update in L0 adapter
- Platform and driver query support for new extension functions
- Update command buffer documentation to specify arg requirements for binary update
> [CMDBUF] Implement kernel binary update for L0 adapter

- source/common/CMakeLists.txt
In comparison to the previous version it contains only a few extra UMF PRs. This version is not taken from UMF's main branch, but rather from special '[umf-fixes-nov-pulldown](https://github.com/oneapi-src/unified-memory-framework/tree/umf-fixes-nov-pulldown)'.
// Testing in sycl repo: https://github.com/intel/llvm/pull/16170
> [common] Bump UMF version

- .github/workflows/cmake.yml
They seem to cause hangs in our CI.
Relates to: #2398
> Disable CUDA sycl e2e tests

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.hpp
- scripts/core/exp-launch-properties.yml
- source/adapters/cuda/enqueue.cpp
- source/adapters/cuda/kernel.hpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/ur_interface_loader.hpp
- source/adapters/level_zero/v2/queue_api.cpp
- source/adapters/level_zero/v2/queue_api.hpp
- source/adapters/level_zero/v2/queue_immediate_in_order.cpp
- source/adapters/level_zero/v2/queue_immediate_in_order.hpp
- source/adapters/mock/ur_mockddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/exp_launch_properties/launch_properties.cpp
https://github.com/intel/llvm/pull/15061 introduce a new property `work_group_scratch_size` which allow the user to set a given amount of local memory to be used.
In order to pass this information to the adaptor, the patch adds a new launch property to `urEnqueueKernelLaunchCustomExp`.
The patch also changes the signature of `urEnqueueKernelLaunchCustomExp` to add `global offset` in order to maintain features when using this extension.
> Add new launch property to support work_group_scratch_memory

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.hpp
- scripts/core/exp-launch-properties.yml
- source/adapters/cuda/enqueue.cpp
- source/adapters/cuda/kernel.hpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/ur_interface_loader.hpp
- source/adapters/level_zero/v2/queue_api.cpp
- source/adapters/level_zero/v2/queue_api.hpp
- source/adapters/level_zero/v2/queue_immediate_in_order.cpp
- source/adapters/level_zero/v2/queue_immediate_in_order.hpp
- source/adapters/mock/ur_mockddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/exp_launch_properties/launch_properties.cpp
This reverts commit 7222f79b160681434250bac74f3aae0e4abc46f0.
#1968 introduced intel/llvm build failures
> Revert "Add new launch property to support work_group_scratch_memory"

- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/adapter.hpp
ZeInitResult and ZeInitDriversResult could potentially be uninitialized, causing undefined behavior when accessed.
Fixes: https://github.com/oneapi-src/unified-runtime/issues/2393.
> [L0] Add nullopt check before init results access

- source/common/umf_pools/disjoint_pool_config_parser.cpp
returning {} when EnableBuffers is false means
returning a defult-constructed DisjointPoolAllConfigs struct which has EnableBuffers set to 1. Fix this by always returning properly constructed DisjointPoolAllConfigs.
> [Common] fix parseDisjointPoolConfig

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/adapter.yml
- source/adapters/cuda/adapter.cpp
- source/adapters/hip/adapter.cpp
- source/adapters/level_zero/adapter.cpp
- source/adapters/native_cpu/adapter.cpp
- source/adapters/opencl/adapter.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/adapter/urAdapterGetInfo.cpp
- tools/urinfo/urinfo.hpp
In order to support in-code management of known failures we need a query to differentiate between the two versions of the Level Zero adapter. This patch adds the `UR_ADAPTER_INFO_VERSION` query which returns a `uint32_t` which is set to return `1` for all adapters except the Level Zero adapter when being compiled in V2 mode.
> Add UR_ADAPTER_INFO_VERSION query

- source/adapters/level_zero/adapter.cpp
- If the user has not overwritten the sysman init type, then the adapter will check the device ip version to determine if zesInit should be used and the env disabled.
> [L0] Enable zesInit by default given newer L0 IP version

- cmake/FetchLevelZero.cmake
Problem appeared in downstream testing where full paths to some files become too long (hits Windows path limit of 260 characters) because of the way how FetchContent repeats provided name multiple times. 
So, shorten the name provided to FetchContent to avoid this issue.
intel/llvm PR: https://github.com/intel/llvm/pull/16253
> [L0] Shorten the dir name for the fecthed repo to avoid hitting Windows max limit

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/device.cpp
- Due to L0 Driver issues related to performance using driver in order lists, the feature is being disabled for the time being.
- Once issues with the L0 Drivers implementing this feature are resolved, then this feature will be re-enabled.
> [L0] Disabling Driver In Order Lists by default

- source/adapters/level_zero/common.hpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
- Added support for using the Intel L0 driver experimental extension for
external sempahores.
- This implementation enables support for external semaphores that will
exist in a future L0 Intel GPU Driver implementation.
- The functionality outlined in this commit mirrors the planned
functionality that will be published in the next offical L0 spec release 1.12.
Once the L0 1.12 spec is released, then the usage of the header definitions
of this functionality will be updated to match the official spec while
supporting the previous driver implementation.
> [L0] Add Support for External Semaphores

- cmake/FindRocmAgentEnumerator.cmake
When installed via deb, rocm is installed into `/opt/rocm` and wasn't
included in $PATH. Include this directory as a possible location to
find `ROCM_AGENT_ENUMERATOR`.
> Add rocm path to find_package

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/event.hpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/queue.hpp
To expose this functionality in UR, we want two ways of enabling low-power events:
1. Queue-wide enabling so all events created on the queue are low-powered.
2. As a property passed to urEnqueueEventsWaitWithBarrier making the resulting event a low-power event. This will require the existing interface to be extended with properties, potentially through a new experimental function.
SYCL/LLVM: https://github.com/intel/llvm/pull/16252
> [L0] Interrupt-based event implementation

- scripts/benchmarks/benches/base.py
- scripts/benchmarks/benches/llamacpp.py
- scripts/benchmarks/benches/options.py
- scripts/benchmarks/benches/result.py
- scripts/benchmarks/main.py
We now run benchmarks until the result is stabilized below a threshold stddev value or until we reach max number of iterations. Outlier results are eliminated each time we calculate stddev, this is to help stddev stabilize quicker and minimize the number of repeat runs.
> [benchmarks] add stddev calculation and outlier elimination

- scripts/benchmarks/benches/compute.py
A few becnhmarks were showing 'unknow' as unit
> [Benchmarks] Fix unit parsing for compute-benchmarks

- include/ur_api.h
- scripts/core/usm.yml
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/CMakeLists.txt
- test/conformance/usm/CMakeLists.txt
- test/conformance/usm/urUSMFree.cpp
- test/conformance/usm/usm_adapter_native_cpu.match
Also add test to enforce this.
This is basically just codifying behaviour that sycl already relies on, see this e2e [test](https://github.com/intel/llvm/blob/10044a3a7536e688e471db40fedb743d8d39ae32/sycl/test-e2e/USM/free_during_kernel_execution.cpp)
> Explicitly specify USMFree as a blocking operation.

- source/adapters/hip/kernel.cpp
- test/conformance/kernel/kernel_adapter_hip.match
This patch adds the num regs query implementation for the HIP adapter.
> [HIP] Implement num regs kernel query

- source/adapters/cuda/program.cpp
- source/adapters/hip/program.cpp
- test/conformance/program/program_adapter_hip.match
Unsupported program info should return unsupported enumeration instead of unsupported feature.
This aligns with the CUDA adapter and makes the CTS understand that these properties aren't failing but just unsupported.
> [HIP] Fix error code for unsupported program info

- scripts/benchmarks/benches/compute.py
- scripts/benchmarks/benches/result.py
- scripts/benchmarks/main.py
- scripts/benchmarks/output_html.py
This makes use of the recently added stddev calculations to display errorbars on the html output timeline chart.
> [benchmarks] add support for stddev

- source/adapters/cuda/command_buffer.cpp
- source/adapters/cuda/command_buffer.hpp
- Change command handle constructors to accept const ref for vector types
- Add std::move to certain vector assignments
- Add missing call to store command handle in command buffer in urCommandBufferAppendMemBufferCopyExp
DPC++ PR https://github.com/intel/llvm/pull/16215
> Fix command_buffer coverity issues

- source/adapters/level_zero/queue.cpp
When using counterbased events, sometimes when retrieving immediate commandlist, we would return a commandlist that is does not have the ZE_COMMAND_QUEUE_FLAG_IN_ORDER flag set which causes an invalid argument when trying to use that commandlist later. 
SYCL/LLVM: https://github.com/intel/llvm/pull/16291
> [L0] Fixed getImmCmdList returning cmdlist with wrong properties

- cmake/helpers.cmake
- test/conformance/exp_command_buffer/fixtures.h
Enable compiler flags which harden MSVC builds against mistakes and vulnerabilities.
> Add SDL hardening flags for MSVC

- source/adapters/level_zero/program.cpp
Found by memcheck. The BuildFlagPtr vector was being populated by the backing data of temporarily created std::string.
> [L0] fix use-after-free in urProgramLinkExp

- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/queue.cpp
- source/adapters/level_zero/queue.hpp
This commit fixes two issues with the level zero implementation of timestamp recording events:
* Events allocated for timestamp recordings may have been previously used, which may lead the implementation to think that the recordings of the old timestamp are right. The implementation will now reset the value of it.
* To avoid cases where timestamp recordings could conflict in the recordings buffer, unfinished recordings of dead events are now moved to another map, to be evicted fully on queue synchronization or death.
> [L0] Fix cached and evicted timestamp recordings

- scripts/benchmarks/benches/compute.py
- scripts/benchmarks/benches/result.py
- scripts/benchmarks/benches/test.py
- scripts/benchmarks/main.py
- scripts/benchmarks/output_html.py
This patch adds back the previously removed bar charts, with one critical difference - we no longer normalize all results to a baseline 100%, but instead, benchmarks need to be explicitly grouped for the comparison bar charts to be generated. The groups need to be chosen such that the units are all the same, and the values are roughly similar.
> [benchmarks] add explicit benchmark groups

- source/loader/CMakeLists.txt
A file path change is missed from the last change of sanitizer code refactor.
This is targeted for 0.11. Please help tag this PR, thanks.
> [DeviceSan] Update cmake to add missing change from code refactor

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/device.hpp
- source/adapters/level_zero/queue.cpp
- Fixes a race condition when the wait events are counting events when executing the context's synchronous immediate command list.
- If a counting event is used in a non immediate command list, then an error will be returned.
> [UR] Fix correct usage of In Order sync list given counting events

- source/loader/CMakeLists.txt
- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_shadow.hpp
- source/loader/layers/sanitizer/msan/msan_allocator.cpp
- source/loader/layers/sanitizer/msan/msan_allocator.hpp
- source/loader/layers/sanitizer/msan/msan_buffer.cpp
- source/loader/layers/sanitizer/msan/msan_buffer.hpp
- source/loader/layers/sanitizer/msan/msan_ddi.cpp
- source/loader/layers/sanitizer/msan/msan_ddi.hpp
- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
- source/loader/layers/sanitizer/msan/msan_interceptor.hpp
- source/loader/layers/sanitizer/msan/msan_libdevice.hpp
- source/loader/layers/sanitizer/msan/msan_options.cpp
- source/loader/layers/sanitizer/msan/msan_options.hpp
- source/loader/layers/sanitizer/msan/msan_report.cpp
- source/loader/layers/sanitizer/msan/msan_report.hpp
- source/loader/layers/sanitizer/msan/msan_shadow.cpp
- source/loader/layers/sanitizer/msan/msan_shadow.hpp
- source/loader/layers/sanitizer/sanitizer_common/linux/sanitizer_utils.cpp
- source/loader/layers/sanitizer/sanitizer_common/sanitizer_common.hpp
- source/loader/layers/sanitizer/ur_sanddi.cpp
- source/loader/layers/sanitizer/ur_sanitizer_layer.cpp
LLVM: https://github.com/intel/llvm/pull/15955
> [DeviceMSAN] Support MemorySanitizer for device offloading

- scripts/benchmarks/output_html.py
Also add more info to tooltips.
> [benchmarks] adjust label and legend positions on bar charts

- source/adapters/cuda/device.hpp
- source/adapters/cuda/image.cpp
* added a map to ur_device_handle_t_.
* Capture the leaking Cumipmappedarray in urBindlessImagesMapExternalArrayExp into map.
* Update urBindlessImagesImageFreeExp to check if the Cuarray is derived, then destroy the corresponding Cumipmappedarray.
> [CUDA][Bindless] Fix memory leak in interop mapping

- source/adapters/cuda/command_buffer.cpp
- source/adapters/hip/command_buffer.cpp
`UR_CHECK_ERROR` must be called within a try catch block, as it can throw.
For functions that don't return a `ur_result_handle_t`, and which might throw, make sure these funcs are only called within try catches in the caller funcs, and that they are not exposed to the user.
DPC++ PR: https://github.com/intel/llvm/pull/16105
> [CUDA][HIP][CommandBuffer] Add try catches to anything that can throw

- scripts/benchmarks/benches/umf.py
benchmarks += s.benchmarks() was failing since benchmarks returned None
> [Benchmarks] fix running benchmarks when umf dir is not specified

- scripts/benchmarks/benches/base.py
- scripts/benchmarks/benches/compute.py
- scripts/benchmarks/benches/llamacpp.py
- scripts/benchmarks/benches/result.py
- scripts/benchmarks/benches/syclbench.py
- scripts/benchmarks/benches/umf.py
- scripts/benchmarks/benches/velocity.py
- scripts/benchmarks/main.py
- scripts/benchmarks/output_html.py
Now with UMF benchmarks being part of the scripts there's a LOT of charts, and it's getting hard to browse. So this patch adds a simple mechanism for filtering the benchmarks by suites. I also refactored the javascript a little bit.
> [benchmarks] add ability to filter benchmarks by suite

- source/adapters/opencl/device.cpp
Adds a few missing Intel GPU device queries, from the `cl_intel_device_attribute_query` extension:
https://registry.khronos.org/OpenCL/extensions/intel/cl_intel_device_attribute_query.html
Also, adds the PCI address query, using `cl_khr_pci_bus_info`:
https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#cl_khr_pci_bus_info
Also, fixes the query for `UR_DEVICE_INFO_DEVICE_ID`.  This query should return the PCI device ID, not the PCI device number from the PCI bus info query.  For now, the query uses the device ID query from `cl_intel_device_attribute_query`, though this could be expanded to support similar queries from other vendors as well.
> add a few missing Intel GPU device queries, fix device ID query

- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
OpenMP program would pass the global variables' address as kernel arguments. Therefore we would need to register those globals in order not to report them as invalid arguments.
This patch is targeted for v0.11, please help tag it.
Intel/llvm PR: https://github.com/intel/llvm/pull/16358
> [DeviceASAN] Register globals for the program

- source/adapters/level_zero/command_buffer.cpp
- test/conformance/program/program_adapter_level_zero_v2.match
- test/conformance/program/urMultiDeviceProgramCreateWithBinary.cpp
UR program and kernel objects can be tied to multiple devices, a UR command-buffer object however is tied to a single device.
When appending a kernel command to a command-buffer, select the correct single-device `ze_kernel_handle_t` object from the multi-device `ur_kernel_handle_t` object
DPC++ PR https://github.com/intel/llvm/pull/16343
> Fix L0 command-buffer consumption of multi-device kernels

- .github/workflows/benchmarks-reusable.yml
- scripts/benchmarks/benches/umf.py
Currently we use numactl to pin the benchmark scripts to
an entire numa node. However, after some testing, this
proved to be insufficient to make all the benchmarks stable.
This patch will change the workflow to now use taskset
to pin the benchmark script to physical cores of the
first numa node, with the exception for the first four,
which are more likely to be used by the kernel for
bookkeeping work or e.g., handling interrupts.
> [benchmarks] pin benchmarks to specific cores 

- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/common.cpp
- source/adapters/level_zero/common.hpp
- Changed the L0 Init failures to goto the error log vs debug and always return an error to the error log if no init is possible.
- Enabled for calling zeParseError to generate the string of L0 error codes in all UR L0 code.
> [L0] Update L0 Init checking to print details in error log

- source/adapters/level_zero/adapter.cpp
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/common.cpp
- source/adapters/level_zero/common.hpp
- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/platform.hpp
- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
- test/conformance/program/program_adapter_level_zero_v2.match
- test/conformance/program/urMultiDeviceProgramCreateWithBinary.cpp
- #2461
- #2454
- #2447
- #2449
- #2452
- #2467
> Candidate for the v0.11.1 release tag

- source/adapters/level_zero/image.cpp
- Due to limitations on certain systems, disable the usage of copy engines given 3-channel memory
- Currently only bindless requires this check due to 3-channel only being used in bindless and copy engine disabled by default in enqueueMemImageCommandHelper.
> [L0] For 3-Channel memory, disable Copy engine Usage

- source/adapters/level_zero/program.cpp
- source/adapters/level_zero/program.hpp
- Address Sanitizer HASAN fails with temporary strings even after last use after free patch. This change resolves all use after free of these strings satifsying the address sanitzer checks with HASAN.
> [L0] Fix use after free with Module build strings

- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
This is a same fix as #2412, we will refine the logic later.
> [DevMSAN] Don't return error if try to get "__MsanKernelMetadata" failed

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/event.hpp
- Given Internal Event that is not cached we must destroy the ze event
at handle destroy. This can only occur if the associated queue does
not have discard events enabled.
- during context release and when event caching is disabled, the destroy
sets the event handle to nullptr to avoid double cleanup.
> [L0] Fix Event Memory Leak due to no destroy on delete

- source/adapters/cuda/command_buffer.cpp
- source/adapters/cuda/command_buffer.hpp
- test/conformance/exp_command_buffer/event_sync.cpp
- test/conformance/exp_command_buffer/exp_command_buffer_adapter_level_zero_v2.match
- test/conformance/exp_command_buffer/update/event_sync.cpp
- Fix a potential issue where decomposed fill nodes for large patterns would overwrite external event dependencies provided by the user when stored in a command handle, this could lead to an error when events were updatd.
- Also store decomposed nodes in fill command handles for future use when updating.
- Add missing event_sync tests with and without event update for large pattern fills (> 4 bytes)
> [CUDA] Fix potential issue with command buffer fills on CUDA

- test/adapters/level_zero/ze_tracer_common.hpp
- Fix include path for the L0 tracing layer header which prevents it from being picked up from the deps downloaded by UR.
The previous path I believe is expected for L0 loader/headers installed on the system level but breaks if this is not present, as the headers downloaded and included by UR itself do not have `level_zero` folder containing the individual include folders (layer, loader etc.).
> [L0] Fix issue with test include path

- include/ur_api.h
- include/ur_ddi.h
- include/ur_print.hpp
- scripts/core/exp-cooperative-kernels.yml
- source/adapters/cuda/kernel.cpp
- source/adapters/hip/kernel.cpp
- source/adapters/level_zero/kernel.cpp
- source/adapters/level_zero/ur_interface_loader.hpp
- source/adapters/level_zero/v2/api.cpp
- source/adapters/mock/ur_mockddi.cpp
- source/adapters/opencl/kernel.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
Add extra param: ur_device_handle_t
It is necessary to implement this function on L0 for kernels that are build for multiple devices. Right now, the implementation only works when the kernel is created from a native handle.
Ref: https://github.com/oneapi-src/unified-runtime/issues/2262
> [Spec] fix urKernelSuggestMaxCooperativeGroupCountExp

- scripts/benchmarks/benches/result.py
- scripts/benchmarks/benchmark_results.html.template
- scripts/benchmarks/output_html.py
[benchmarks] use "unknown" suite for old results
Using a simple f-string was starting to get annoying
with the increased use of javascript.
[benchmarks] use "unknown" suite for old results
This fixes the empty "" checkbox on the results html.
> [benchmarks] use template for html output and set unknown suite

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/event.hpp
- source/adapters/level_zero/image.cpp
- source/adapters/level_zero/program.cpp
- source/adapters/level_zero/program.hpp
- source/loader/CMakeLists.txt
- source/loader/layers/sanitizer/asan/asan_ddi.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
- source/loader/layers/sanitizer/asan/asan_libdevice.hpp
- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
- #2472
- #2474
- #2477
- #2415
- #2476
> Candidate for the v0.11.2 release tag

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
The implementation was using zeCommandListImmediateAppendCommandListsExp directly with the loader. This creates an issue with old loaders that don't support this entrypoint. Instead, this change uses dlsym to load the function if available.
intel/llvm PR: https://github.com/intel/llvm/pull/16458
> Update usage of zeCommandListImmediateAppendCommandListsExp to use dlsym

- test/conformance/event/urEventGetProfilingInfo.cpp
End and start timing can be the same if the operation that is being measure is fast enough.
> [CTS] adjust timestamp test

- scripts/benchmarks/output_html.py
Fix for failing nightly build: https://github.com/oneapi-src/unified-runtime/actions/runs/12539743466/job/34966851258#step:19:847
`FileNotFoundError: [Errno 2] No such file or directory: 'benchmark_results.html.template'`
Ref. #2469
Verified it works here: https://github.com/oneapi-src/unified-runtime/actions/runs/12546801432/job/34984544056?pr=2510#step:19:762
> Fix bench template

- source/adapters/level_zero/context.cpp
When both counterbased and interruptbased events are enabled there is a ZeEventPoolDesc.pNext will get overwritten in
getFreeSlotInExistingOrNewPool. This fixes that.
> [L0] Fixes potential overwrite in ZeEventPoolDesc.pNext

- source/adapters/cuda/tensor_map.cpp
The documentation at https://docs.nvidia.com/cuda/cutensor/latest/ say it's supported in 11.0, 11.8, and 12.x
Our local testing against 11.7 fails because none of the required types or functions are declared in the header.
It's safer to remain buildable with older versions but with this feature disabled than requiring a version bump that isn't otherwise warranted.
> CUTensorMap is only in CUDA v12

- source/adapters/level_zero/command_buffer.cpp
Add barriers to the SignalCommandList that guarantee that resetting the WaitEvent is done at the right time.
This fixes a potential race condition where, if the SignalCommandList executes before the ComputeCommandList, the WaitEvent could be reset before the ComputeCommandList can wait on it and, consequently, create a deadlock.
> Fix potential deadlock in the WaitEvent path of CmdBuffers

- source/adapters/cuda/command_buffer.cpp
- source/adapters/cuda/device.cpp
- source/adapters/cuda/platform.cpp
Fixes [2497](https://github.com/oneapi-src/unified-runtime/issues/2497)
> [Windows][CUDA] Fix cuda uninitialized event warning

- source/adapters/level_zero/command_buffer.cpp
Reverts oneapi-src/unified-runtime#2481
Fails e2e tests so reverting for now: https://github.com/intel/llvm/actions/runs/12599326805/job/35117081245?pr=16469
> Revert "Fix potential deadlock in the WaitEvent path of CmdBuffers"

- source/loader/layers/sanitizer/asan/asan_ddi.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
- source/loader/layers/sanitizer/msan/msan_ddi.cpp
- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
- source/loader/layers/sanitizer/msan/msan_interceptor.hpp
LLVM: https://github.com/intel/llvm/pull/16473
Since we can't get nullptr when calling `getKernelInfo`, I changed the return type of this function to reference.
To make it support "urKernelCreateXXX" APIs automatically, I changed `getKernelInfo` to `getOrCreateKernelInfo`, so that we needn't intercept "urKernelCreateXXX" anymore.
Sync those changes to msan.
> [DeviceASAN] Fix urKernelCreateWithNativeHandle segfault

- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
LLVM: https://github.com/intel/llvm/pull/16478
> [DeviceMSAN] Fix empty kernel

- test/conformance/device_code/CMakeLists.txt
Pass -q to `clang-offload-extract` so it doesn't generate binary names when building.
Closes: #2084
> [NFC] Don't print generated device binary names

- test/conformance/context/urContextGetInfo.cpp
- test/conformance/event/urEventGetInfo.cpp
- test/conformance/queue/urQueueGetInfo.cpp
> Move urContextGetInfo success test from a switch to individual tests

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
- Fixes the translation of handles which is not needed when the loader extension of MCL is used. This also fixes the problem during multi driver scenarios.
intel/llvm PR: https://github.com/intel/llvm/pull/16459
> [L0] Remove handle Translation in MCL if loader extension used

- source/common/logger/ur_logger.hpp
Specifically this should fix warnings such as the one seen in pytorch CI: https://github.com/pytorch/pytorch/actions/runs/12043736074/job/33601354052#step:14:10286
> Use std::string in create_logger to avoid valgrind warning in some configs

- source/adapters/level_zero/event.cpp
- Fix Out Event created in Enqueue Wait Events to ensure the event is
not reused.
- Removed completion logic that was allowing caching of the event.
- event_handle_t zeEventDestroy handles the memory leak issue that this
branch was attempting to fix.
> [L0]: Fix Out Event in Enqueue Wait Events to prevent reuse

- include/ur_api.h
- scripts/core/exp-command-buffer.yml
- source/adapters/opencl/command_buffer.cpp
- source/adapters/opencl/command_buffer.hpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/exp_command_buffer/CMakeLists.txt
- test/conformance/exp_command_buffer/exp_command_buffer_adapter_native_cpu.match
- test/conformance/exp_command_buffer/invalid.cpp
- test/conformance/exp_command_buffer/update/invalid_update.cpp
The `UR_DEVICE_INFO_COMMAND_BUFFER_UPDATE_SUPPORT_EXP` query no longer exists, so error defined for trying to make an updatable command-buffer when a device doesn't support it needs reworded to say if no capabilities are supported.
Additionally, for each individual update capability, specify that an error is thrown if update is attempted using that characteristic.
UR CTS added to verify the above clarifications.
DPC++ PR https://github.com/intel/llvm/pull/16383
> Improve specification of command-buffer update errors

- CMakeLists.txt
- source/adapters/cuda/tensor_map.cpp
- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
- source/common/logger/ur_logger.hpp
- source/loader/CMakeLists.txt
- source/loader/layers/sanitizer/asan/asan_ddi.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
- source/loader/layers/sanitizer/asan/asan_shadow.cpp
- source/loader/layers/sanitizer/msan/msan_ddi.cpp
- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
- source/loader/layers/sanitizer/msan/msan_interceptor.hpp
- source/loader/layers/sanitizer/msan/msan_libdevice.hpp
- source/loader/layers/sanitizer/msan/msan_shadow.cpp
- source/loader/layers/sanitizer/msan/msan_shadow.hpp
- source/loader/layers/sanitizer/sanitizer_common/linux/sanitizer_utils.cpp
- source/loader/layers/sanitizer/sanitizer_common/sanitizer_utils.cpp
- #2498
- #2402
- #2507
- #2484
- #2501
- #2502
- #2478
- #2506
- #2508
- #2513
- #2504
- #2517
- #2524
> Candidate for the v0.11.3 release tag

- source/adapters/native_cpu/enqueue.cpp
- source/adapters/native_cpu/kernel.hpp
Depending on the number of available threads, NativeCPU goes through different code paths for launching kernels. Some of these were missing the call to `kernel.handleLocalArgs`, resulting in local pointers being left as `nullptr`.
https://github.com/intel/llvm/pull/16500
> [NativeCPU] Handle local args.

- test/conformance/platform/urPlatformGetInfo.cpp
> Rework urPlatformGetInfo test into individual tests instead of a switch

- test/adapters/cuda/fixtures.h
- test/adapters/hip/fixtures.h
I can't work out why all this complexity could be needed. My guess is there was a plan to mould this further into something useful, but we're not using it and it's fairly confusing to boot. DELETE.
> Get rid of extra-confounding test helper code

- test/conformance/adapter/urAdapterGetInfo.cpp
- test/conformance/event/urEventGetInfo.cpp
- test/conformance/memory/memory_adapter_level_zero.match
- test/conformance/memory/memory_adapter_native_cpu.match
- test/conformance/memory/urMemGetInfo.cpp
- test/conformance/queue/urQueueGetInfo.cpp
- test/conformance/testing/include/uur/fixtures.h
- test/conformance/virtual_memory/urPhysicalMemGetInfo.cpp
Also reworked urAdapterGetInfo - ValidAdapterBackend test was redundant. 
Also tidy up some other urXGetInfo tests with default values and removing unneccessary casts.
> Move urMemoryGetInfo success test from a switch to individual tests

- test/conformance/sampler/sampler_adapter_level_zero.match
- test/conformance/sampler/urSamplerGetInfo.cpp
> Move urSamplerGetInfo success test from a switch to individual tests

- scripts/core/enqueue.yml
- scripts/core/event.yml
- source/adapters/cuda/adapter.cpp
- source/adapters/cuda/memory.cpp
- source/adapters/hip/adapter.cpp
- source/adapters/hip/memory.cpp
This should hopefully make it easier to see which repo a given issue is
referring to.
> Replace bare issue numbers with URLs

- test/conformance/program/urProgramGetFunctionPointer.cpp
The spec says that implementations may return
`UR_RESULT_ERROR_FUNCTION_ADDRESS_NOT_AVAILABLE` for this function, but
that wasn't handled by this test.
> Update urProgramGetFunctionPointer test

- source/adapters/level_zero/physical_mem.cpp
Including ur_interface_loader.hpp in v2 adapter causes error C2375 as urPhysicalMemGetInfo is declared without UR_APIEXPORT UR_APICALL
> [L0] fix linkage for urPhysicalMemGetInfo on Windows

- scripts/templates/ldrddi.cpp.mako
- source/loader/ur_ldrddi.cpp
- test/conformance/event/urEventSetCallback.cpp
The events returned by the loader do not match the events returned by
openCL (or other backends), which causes issues when adding a callback
handler. This adds an intermediate wrapper to replace the event with the
loader event.
> Wrap urEventSetCallback when ran through loader

- include/ur_api.h
- scripts/core/usm.yml
- scripts/templates/helper.py
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
This previously referenced a nonexistent `hDevice` parameter. It has
been updated to match the OpenCL function.
Also, the validation layer generator logic has been updated to handle
conditions that contain "`", which was an edge case that wasn't handled
before.
> Fix error returns of urUSMHostAlloc

- source/loader/layers/sanitizer/msan/msan_buffer.cpp
- source/loader/layers/sanitizer/msan/msan_ddi.cpp
- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
- source/loader/layers/sanitizer/msan/msan_interceptor.hpp
intel/llvm part: https://github.com/intel/llvm/pull/16526
> [DevMSAN] Propagate shadow memory in buffer related APIs

- test/conformance/device/urDeviceGetGlobalTimestamps.cpp
The `SuccessSynchronizedTime` previously sampled for several hundred
nanoseconds in order to detect clock drift. This is too strict, and so
it has been increased to 16ms.
> Be less strict with timer test

- test/conformance/program/urProgramGetBuildInfo.cpp
- test/conformance/program/urProgramGetInfo.cpp
> Move urProgramGetInfo success test from a switch to individual tests.

- test/conformance/virtual_memory/urVirtualMemGetInfo.cpp
> Move urVirtualMemGetInfo success test from a switch to individual tests

- test/conformance/memory/urMemBufferCreateWithNativeHandle.cpp
Functions in this test are optional, so the test should allow them to
return "not supported".
> Update MemBufferCreate with unsupported checks

- test/conformance/kernel/urKernelGetGroupInfo.cpp
I have a 12th gen CPU, and this is reporting an error to stdout saying
it is unsupported.
> Mark urKernelGetGroupInfoMaxWorkGroupSize as failing on 12th gen

- source/loader/layers/sanitizer/asan/asan_shadow.hpp
ShadowMemory holds a reference to the appropriate device, but did not
retain/release it properly, resulting in use-after-frees in the asan
testing.
> ShadowMemory should increment/decrement device handle

- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
intel/llvm part: https://github.com/intel/llvm/pull/16654
> [DevASAN] Only report warning if passing host ptr to kernel

- scripts/templates/ldrddi.cpp.mako
- source/loader/ur_ldrddi.cpp
If the function pointer passed into the function was null, then the
wrapper is leaked. This change re-orders things so the wrapper is
created later.
> Fix memory leak in loader urEventSetCallback

- test/conformance/testing/include/uur/fixtures.h
- test/conformance/usm/urUSMGetMemAllocInfo.cpp
- test/conformance/usm/urUSMPoolGetInfo.cpp
> Move urUSMGetMemAlloc/PoolGetInfo success test from a switch to indivual tests

- test/conformance/adapter/urAdapterGetInfo.cpp
- test/conformance/context/urContextGetInfo.cpp
- test/conformance/event/urEventGetInfo.cpp
- test/conformance/kernel/urKernelGetGroupInfo.cpp
- test/conformance/kernel/urKernelGetInfo.cpp
- test/conformance/kernel/urKernelGetSubGroupInfo.cpp
- test/conformance/memory/urMemGetInfo.cpp
- test/conformance/platform/urPlatformGetInfo.cpp
- test/conformance/program/urProgramGetBuildInfo.cpp
- test/conformance/program/urProgramGetInfo.cpp
- test/conformance/queue/urQueueGetInfo.cpp
- test/conformance/sampler/urSamplerGetInfo.cpp
- test/conformance/virtual_memory/urPhysicalMemGetInfo.cpp
- test/conformance/virtual_memory/urVirtualMemGranularityGetInfo.cpp
Redo various urXGetInfo query tests so the first call uses the ASSERT_SUCCESS_OR_OPTIONAL_QUERY macro.
Rework urVirtualMemGranularityGetInfoTest into separate tests.
Various tidying up of the urXGetInfo tests for better consistency.
> Redo various urXGetInfo query tests so the first call uses the ASSERT_SUCCESS_OR_OPTIONAL_QUERY macro

- source/adapters/level_zero/command_buffer.cpp
- source/adapters/level_zero/command_buffer.hpp
- Track whether a command buffer was recently synchronized so we can skip unnecessary fence/event waits. Previous consecutive calls to update a command buffer would result in calling `zeFenceHostSynchronize` for each call unnecessarily.
> [L0][CMDBUF] Optimize fence/event waits during update

- source/adapters/level_zero/image.cpp
Minor patch that enables images to be created from Host USM on the L0 backend.
> Enable Host USM backed images on Level Zero

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/device.yml
- scripts/core/program.yml
- source/adapters/cuda/device.cpp
- source/adapters/hip/device.cpp
- source/adapters/level_zero/device.cpp
- source/adapters/native_cpu/device.cpp
- source/adapters/opencl/device.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/device/urDeviceGetInfo.cpp
- test/conformance/program/urProgramSetSpecializationConstants.cpp
- tools/urinfo/urinfo.hpp
THis is similar to the existing
`DEVICE_INFO_KERNEL_SET_SPECIALIZATION_CONSTANTS` device info, only
it applies to programs rather than kernels. All of the adapters should
be updated to report it correctly, and tests have been added.
> Added `DEVICE_INFO_PROGRAM_SET_SPECIALIZATION_CONSTANTS`

- source/loader/layers/sanitizer/asan/asan_ddi.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
- source/loader/layers/sanitizer/sanitizer_common/sanitizer_utils.cpp
Previously we had one `ShadowMemory` for every `DeviceInfo`. That is causing problem because it's release process is called too late. And only the first `ShadowMemory` would do the actual shadow memory bookkeeping.
This is a quick fix but also is heading in the direction we plan, which is one `ShadowMemory` for each device type. This relies on the fact that for the virtual memory with L0, it can access the address from different device and within different context with newer driver. And as for opencl CPU device, since it is host memory, it does not have to worry about this issue.
We will purpose PR later to do a better refactor, but for now we are trying to fix the issue with minimum changes to avoid any possible regression.
Intel/llvm PR: https://github.com/intel/llvm/pull/16687
> [DeivceASAN] Make ShadowMemory one instance per type

- source/loader/layers/sanitizer/sanitizer_common/sanitizer_utils.cpp
A logical error in `GetDeviceType()` is introduced with a recent PR. This fixes the bug.
Intel/llvm PR: https://github.com/intel/llvm/pull/16745
> [DeviceASAN] Bugfix for GetDeviceType

- CMakeLists.txt
- source/loader/layers/sanitizer/asan/asan_ddi.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
- source/loader/layers/sanitizer/msan/msan_ddi.cpp
- source/loader/layers/sanitizer/sanitizer_common/sanitizer_utils.cpp
> Candidate for the v0.11.5 release tag

- source/adapters/cuda/command_buffer.cpp
- source/adapters/cuda/enqueue.cpp
- source/adapters/cuda/kernel.hpp
- source/adapters/hip/command_buffer.cpp
- source/adapters/hip/enqueue.cpp
- source/adapters/hip/kernel.hpp
- test/adapters/cuda/kernel_tests.cpp
- test/conformance/exp_command_buffer/update/local_memory_update.cpp
- test/conformance/kernel/urKernelSetArgLocal.cpp
In the Cuda and Hip adapter, when kernel arguments are added out of order (e.g. argument at index 1 is added before argument at index 0), the existing arguments are currently being overwritten. This happens because some of the argument sizes might not be known when adding them out of order and the code relies on those sizes to choose where to store the argument.
This PR avoids this issue by storing the arguments in the same order that they are added and accessing them using pointer offsets.
intel/llvm: https://github.com/intel/llvm/pull/16733
> [CUDA][HIP] Fix kernel arguments being overwritten when added out of order

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/memory.yml
- source/adapters/opencl/memory.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/memory/urMemImageGetInfo.cpp
- test/conformance/queue/urQueueGetInfo.cpp
- test/conformance/testing/include/uur/fixtures.h
Also adds a few missing enums to the `ur_image_info_t` struct
https://github.com/intel/llvm/pull/16655
> Move urMemImageGetInfo success test from a switch to individual test

- .github/workflows/benchmarks-reusable.yml
- .github/workflows/docs.yml
The cache action is stopping support for anything but the very latest version. We need to update to 4.2.0 for the cache to continue functioning.
https://github.com/actions/cache/discussions/1510
> update GitHub Cache action to 4.2.0

- include/ur_api.h
- include/ur_print.hpp
- scripts/core/memory.yml
- source/adapters/opencl/memory.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/memory/urMemImageGetInfo.cpp
- test/conformance/queue/urQueueGetInfo.cpp
- test/conformance/testing/include/uur/fixtures.h
Reverts oneapi-src/unified-runtime#2549
> Revert "Move urMemImageGetInfo success test from a switch to individual test"

- test/adapters/level_zero/event_cache_tests.cpp
- test/adapters/level_zero/multi_device_event_cache_tests.cpp
- test/adapters/level_zero/ze_tracer_common.hpp
Don't pass large objects by value, use a r-value reference instead. Also make function defined in header `inline`.
> Fix passing struct object by value

- source/adapters/cuda/image.cpp
Small patch to enable bindless images backed by host USM in the CUDA adapter.
Host and Device USM pointers are usable across the host and device for all versions of CUDA that we support. There is no need to provide the `CU_MEMHOSTALLOC_DEVICEMAP` flag during allocation, or calling `cuMemHostGetDevicePointer` to retrieve a device usable address.
Passing a `CU_MEMHOSTALLOC_WRITECOMBINED` flag to the host USM allocation will enhance performance in certain scenarios, however, an extension allowing this is not yet available.
Related DPC++ PR: https://github.com/intel/llvm/pull/16607
> Enable creation of bindless images backed by host USM

- CMakeLists.txt
- source/adapters/cuda/command_buffer.cpp
- source/adapters/cuda/device.cpp
- source/adapters/cuda/platform.cpp
> Candidate for the v0.11.6 release tag

- source/common/umf_pools/disjoint_pool_config_parser.cpp
- test/usm/usmPoolManager.cpp
fix parseDisjointPoolConfig() (which parses the SYCL_PI_LEVEL_ZERO_USM_ALLOCATOR environment variable) + add basic tests
this is a fix for #2544 
intel/llvm: https://github.com/intel/llvm/pull/16708
> fix parseDisjointPoolConfig and add tests

- test/conformance/kernel/urKernelGetInfo.cpp
I think this must have crept back into the match file at some point after the optional-query PR
> Remove unnecessary OpenCL KNOWN_FAILURE from urKernelGetInfoTest.

- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
This (hopefully) silences a Coverity issue.
> Assert that Device is valid for memory poisoning

- source/adapters/cuda/command_buffer.hpp
This class isn't used as a base class.
> Remove unused `virtual` in cuda command buffers

- source/adapters/opencl/adapter.cpp
When attempting to get a handle for the `libOpenCL.so` library in order to call `dlsym()` invalid arguments were set so `dlopen()` always returned null. This just happened to work due to the value of `RTLD_DEFAULT` being 0 so the `dlsym()` calls succeeded. This patch removes the invalid `dlopen()` usage and explicitly uses `RTLD_DEFAULT` instead of the null `handle`.
https://github.com/intel/llvm/pull/16736
> Fix invalid use of dlopen()

- .github/workflows/benchmarks-reusable.yml
- scripts/benchmarks/README.md
- scripts/benchmarks/main.py
- scripts/benchmarks/options.py
- scripts/benchmarks/utils/compute_runtime.py
- scripts/benchmarks/utils/utils.py
- third_party/benchmark_requirements.txt
Instead of hardcoding compute runtime dependencies, scripts will now fetch its manifest file to see what are the correct versions of dependencies to build them.
This patch also adds an option to build IGC from source.
> [benchmarks] use manifest to build compute-runtime dependencies

- test/conformance/exp_command_buffer/update/local_memory_update.cpp
The CTS tests for updating local memory in command-buffer kernel commands are currently skipped on Level-Zero. This feature is now available in L0 drivers so the tests can be enabled.
There is a failure in `LocalMemoryUpdateTest.UpdateParametersSmallerLocalSize` with incorrect results. Mark the individual test as failed as it needs further investigation.
> Enable cmd-buf local memory update CTS tests on L0

- test/conformance/device/urDeviceGetGlobalTimestamps.cpp
- test/conformance/kernel/urKernelGetGroupInfo.cpp
- test/conformance/kernel/urKernelGetSubGroupInfo.cpp
- test/conformance/kernel/urKernelSetArgSampler.cpp
- test/conformance/memory/urMemGetInfo.cpp
- test/conformance/memory/urMemImageCreate.cpp
- test/conformance/memory/urMemImageCreateWithImageFormatParam.cpp
- test/conformance/sampler/urSamplerCreate.cpp
- test/conformance/testing/include/uur/fixtures.h
- test/conformance/usm/urUSMGetMemAllocInfo.cpp
Mostly this involved removing unneeded skips and checking for image support where appropriate. Also adds ticket links for the less simple fails.
> Fix the easily dealt with CL adapter KNOWN_FAILURES.

- scripts/templates/queue_api.cpp.mako
- scripts/templates/queue_api.hpp.mako
- source/adapters/level_zero/v2/queue_api.cpp
- source/adapters/level_zero/v2/queue_api.hpp
- source/adapters/level_zero/v2/queue_handle.hpp
- source/adapters/level_zero/v2/queue_immediate_in_order.cpp
- source/adapters/level_zero/v2/queue_immediate_in_order.hpp
after introducing variant to store the actual queue instance, urQueueRelease became incorrect. It called delete on 'this' and not on ur_queue_handle_t_ which is an UB.
> [L0 v2] fix queue destruction

- source/adapters/level_zero/event.cpp
- Added check during event handle release to perform an additional
cleanup of an enqueue wait event once the user has released their
usage of the out event.
> [L0]: fix missing destroy of event given enqueue wait out event

- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/memory.hpp
We want to transition to handle pointers containing the ddi table as the
first element. For this to work, handle object must not have a vtable.
Since ur_mem_handle_t_ is relatively simple, it's easy enough to roll
out our own version of dynamic dispatch.
> Remove virtual methods from ur_mem_handle_t_

- source/common/CMakeLists.txt
- source/common/umf_helpers.hpp
intel/llvm testing: https://github.com/intel/llvm/pull/16749
> [common] Bump UMF to early 0.11 version, from main

- source/adapters/level_zero/device.cpp
- source/adapters/level_zero/platform.cpp
- source/adapters/level_zero/platform.hpp
For some recovery SKUs, MAX_COMPUTE_COUNT calculation does not provide the correct number of EUs. Now we will  use ze_eu_count_t when available.
LLVM/SYCL: https://github.com/intel/llvm/pull/16818
> [L0] MAX_COMPUTE_UNITS using ze_eu_count_ext_t

- source/adapters/cuda/context.hpp
- source/adapters/cuda/device.hpp
- source/adapters/cuda/memory.cpp
- source/adapters/cuda/platform.cpp
- source/adapters/cuda/usm.cpp
- source/common/CMakeLists.txt
- source/common/umf_helpers.hpp
llvm: https://github.com/intel/llvm/pull/16761
> Use UMF CUDA memory provider in UR

- CMakeLists.txt
- source/adapters/level_zero/event.cpp
Cherry-pick of https://github.com/oneapi-src/unified-runtime/pull/2612 to 0.11.x for release.
> [L0]: fix missing destroy of event given enqueue wait out event cherry-pick to 0.11.x

- source/adapters/hip/common.cpp
- source/adapters/hip/device.cpp
- source/adapters/hip/device.hpp
- source/adapters/hip/image.cpp
- source/adapters/hip/image.hpp
- source/adapters/hip/sampler.hpp
- source/adapters/hip/ur_interface_loader.cpp
This PR implements the entry points in the HIP adapter for the Bindless Images extension.
Some features, while implemented, only partially pass the End-to-end tests for them in DPC++ (the PR that enables the support and testing in DPC++: https://github.com/intel/llvm/pull/16439). This is because the HIP runtime doesn't support, for example, some parameter combinations with some image memory types. The not-fully supported features are marked with `TODO`s in the device info queries for further work.
Signed-off-by: Georgi Mirazchiyski <georgi.mirazchiyski@codeplay.com>
Co-authored-by: Peter Žužek <peter@codeplay.com>
> [UR][Bindless] Initial implementation of bindless images for HIP

- source/adapters/native_cpu/enqueue.cpp
The documentation for urEnqueueKernelLaunch marks phEvent as optional, so make sure we only set it if provided.
Matching PR: https://github.com/intel/llvm/pull/16868
> [NativeCPU] Handle null phEvent.

- test/conformance/usm/helpers.h
- test/conformance/usm/urUSMDeviceAlloc.cpp
- test/conformance/usm/urUSMHostAlloc.cpp
- test/conformance/usm/urUSMPoolRelease.cpp
- test/conformance/usm/urUSMSharedAlloc.cpp
- Additional error case checking
- More validation for urUSMPoolRelease
- Refactored urUSMDevice/Shared/HostAlloc test structs into a shared parent struct
- Added ur_usm_advice_flags_t param to parameterised Alloc tests
> Improvements to align CTS and Spec for USM

- test/conformance/adapter/urAdapterGetInfo.cpp
- test/conformance/context/urContextGetInfo.cpp
- test/conformance/event/urEventGetInfo.cpp
- test/conformance/event/urEventGetProfilingInfo.cpp
- test/conformance/kernel/urKernelGetGroupInfo.cpp
- test/conformance/kernel/urKernelGetInfo.cpp
- test/conformance/kernel/urKernelGetSubGroupInfo.cpp
- test/conformance/memory/urMemGetInfo.cpp
- test/conformance/memory/urMemImageGetInfo.cpp
- test/conformance/platform/urPlatformGetInfo.cpp
- test/conformance/program/urProgramGetBuildInfo.cpp
- test/conformance/program/urProgramGetInfo.cpp
- test/conformance/queue/urQueueGetInfo.cpp
- test/conformance/sampler/urSamplerGetInfo.cpp
- test/conformance/testing/include/uur/checks.h
- test/conformance/usm/urUSMGetMemAllocInfo.cpp
- test/conformance/usm/urUSMPoolGetInfo.cpp
- test/conformance/virtual_memory/urPhysicalMemGetInfo.cpp
- test/conformance/virtual_memory/urVirtualMemGetInfo.cpp
- test/conformance/virtual_memory/urVirtualMemGranularityGetInfo.cpp
Also done a housekeeping pass across all urXGetInfo tests, renaming and adding consts where appropriate, and adding extra checks to tests with vectors.
> Reorganised urEventGetProfilingInfo test into separate tests instead of a switch

- source/loader/layers/sanitizer/asan/asan_shadow.hpp
ShadowMemory object is destroyed during shutdown stage, in that time
some resources in context_t should have been freed. So directly call ur api
may cause use-after-free problem.
> [DevASAN] Avoid directly UR api call

- source/loader/layers/sanitizer/asan/asan_ddi.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
Not allow concurrent kernel launches across different queues as the local/private shadow memory implementation does not support it.
intel/llvm PR: https://github.com/intel/llvm/pull/16935
> [DeviceASAN][bugfix] Not allow concurrent kernel launches across different queue

- CMakeLists.txt
- source/loader/layers/sanitizer/asan/asan_ddi.cpp
- source/loader/layers/sanitizer/asan/asan_interceptor.hpp
> Candidate for the v0.11.8 release tag

- .github/workflows/benchmarks-reusable.yml
Added more cmake options for UMF benchmarks, including an option for building libumf_proxy.so. The file was missing previously.
> fix missing cmake options for UMF benchmarks

- source/adapters/level_zero/v2/command_buffer.cpp
- source/adapters/level_zero/v2/command_list_manager.cpp
- source/adapters/level_zero/v2/context.cpp
- source/adapters/level_zero/v2/context.hpp
- source/adapters/level_zero/v2/event.cpp
- source/adapters/level_zero/v2/memory.cpp
- source/adapters/level_zero/v2/queue_immediate_in_order.cpp
- test/adapters/level_zero/v2/command_list_cache_test.cpp
so that ze_context is destroyed last, after it's no longer needed.
The previous order caused problems in some tests with defer free
> [L0 v2] reorder context members

- .github/workflows/benchmarks-reusable.yml
and print produced results in CI, just FYI.
> [CI][Bench] Use GPU mask to match the CPU mask

- source/adapters/level_zero/v2/command_buffer.cpp
This is a regression after #2688
> [L0 v2] add missing urCommadBufferEnqueueExp function

- source/adapters/level_zero/common.hpp
- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/event.hpp
- source/adapters/level_zero/v2/event_provider.hpp
CI in LLVM/SYCL: https://github.com/intel/llvm/pull/14536
> [L0] Refactoring of boolean event parameters

- test/conformance/event/urEventCreateWithNativeHandle.cpp
- test/conformance/event/urEventGetProfilingInfo.cpp
- test/conformance/event/urEventSetCallback.cpp
* Added test case for urEventGetProfilingInfo return UR_RESULT_ERROR_PROFILING_INFO_NOT_AVAILABLE
* Added test case for urEventCreateWithNativeHandle return UR_RESULT_ERROR_INVALID_NULL_HANDLE
* Added test case for urEventCreateWithNativeHandle return UR_RESULT_ERROR_INVALID_NULL_POINTER
* Added test case for urEventSetCallback return UR_RESULT_ERROR_UNSUPPORTED_ENUMERATION
> Improvements to align CTS and Spec for Event.

- source/adapters/level_zero/context.cpp
- source/adapters/level_zero/context.hpp
- source/adapters/level_zero/event.cpp
- source/adapters/level_zero/event.hpp
- source/adapters/level_zero/v2/event_provider.hpp
Reverts oneapi-src/unified-runtime#1600 due to CI failures on https://github.com/intel/llvm/pull/14536
> Revert "[L0] Refactoring of boolean event parameters"

- source/common/CMakeLists.txt
It includes fix for icx compiler
// sycl build: https://github.com/intel/llvm/pull/16919
> common: Bump UMF version to v0.11.0-dev2

- include/ur_api.h
- scripts/core/enqueue.yml
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
- test/conformance/enqueue/urEnqueueDeviceGlobalVariableRead.cpp
- test/conformance/enqueue/urEnqueueDeviceGlobalVariableWrite.cpp
- test/conformance/enqueue/urEnqueueKernelLaunch.cpp
- test/conformance/enqueue/urEnqueueMemBufferCopyRect.cpp
- test/conformance/enqueue/urEnqueueMemBufferReadRect.cpp
- test/conformance/enqueue/urEnqueueMemBufferWriteRect.cpp
- test/conformance/enqueue/urEnqueueUSMAdvise.cpp
- test/conformance/enqueue/urEnqueueUSMFill.cpp
- test/conformance/enqueue/urEnqueueUSMMemcpy2D.cpp
- test/conformance/testing/include/uur/fixtures.h
- test/conformance/usm/helpers.h
- test/conformance/usm/urUSMDeviceAlloc.cpp
- test/conformance/usm/urUSMHostAlloc.cpp
- test/conformance/usm/urUSMSharedAlloc.cpp
- Add test for invalid null pointer for urEnqueueKernelLaunch and urEnqueueUSMFill
- Remove redundant sentence in urEnqueueMemBufferMap description
- Add advice flag parameters in test for urEnqueueUSMAdvise
- Added blocking/non-blocking success tests for urEnqueueDeviceGlobalVariableRead/Write
- Added all invalid size scenarios for urEnqueueMemBufferFill and urEnqueueMemBufferWrite/Read/CopyRect
- Added to description of urEnqueueMemAdvice to say some adapters will return UR_RESULT_ERROR_ADAPTER_SPECIFIC and allowing this return value in relevant tests
I've not attached an intel/llvm tag update as the spec change is very minor - just removing a sentence from an entry-point description.
> Improvements to align CTS and Spec for Enqueue

- source/common/CMakeLists.txt
Set `UMF_CUDA_INCLUDE_DIR` so that UMF does not fetch cudart from gitlab.com.
llvm: https://github.com/intel/llvm/pull/16941
> Do not fetch cudart from gitlab for UMF

- test/conformance/kernel/urKernelGetGroupInfo.cpp
Use "Intel(R) Core(TM)" to match all client CPUs instead of specific generations.
> Mark OpenCL CPU known failing device more generally

- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_options.cpp
- source/loader/layers/sanitizer/asan/asan_options.hpp
LLVM: https://github.com/intel/llvm/pull/16706
a small enhancement
> [DeviceASAN] Fix throw "UR_RESULT_ERROR_INVALID_ARGUMENT" exception when catching free related error

- source/loader/layers/sanitizer/asan/asan_interceptor.cpp
- source/loader/layers/sanitizer/asan/asan_options.cpp
- source/loader/layers/sanitizer/asan/asan_options.hpp
Reverts oneapi-src/unified-runtime#2592 due to test failures on https://github.com/intel/llvm/pull/16706
> Revert "[DeviceASAN] Fix throw "UR_RESULT_ERROR_INVALID_ARGUMENT" exception when catching free related error"

- source/loader/ur_adapter_registry.hpp
This PR enable us to register level_zero_v2 in the list of UR adapters, so it could be used with dpc++.
> Enable the registry of level_zero_v2

- source/loader/layers/sanitizer/msan/msan_interceptor.cpp
This is a false positive flagged by coverity. However, since DeviceInfo
is never used if there is no device, may as well just de-footgun it.
> [NFC] Small refactor for MsanInterceptor::allocateMemory

- include/ur_api.h
- scripts/YaML.md
- scripts/core/adapter.yml
- scripts/core/context.yml
- scripts/core/device.yml
- scripts/core/enqueue.yml
- scripts/core/event.yml
- scripts/core/exp-bindless-images.yml
- scripts/core/exp-command-buffer.yml
- scripts/core/exp-cooperative-kernels.yml
- scripts/core/exp-launch-properties.yml
- scripts/core/exp-low-power-events.yml
- scripts/core/exp-multi-device-compile.yml
- scripts/core/exp-native-enqueue.yml
- scripts/core/kernel.yml
- scripts/core/loader.yml
- scripts/core/memory.yml
- scripts/core/platform.yml
- scripts/core/program.yml
- scripts/core/queue.yml
- scripts/core/sampler.yml
- scripts/core/usm.yml
- scripts/core/virtual_memory.yml
- source/adapters/mock/ur_mockddi.cpp
- source/loader/layers/tracing/ur_trcddi.cpp
- source/loader/layers/validation/ur_valddi.cpp
- source/loader/ur_ldrddi.cpp
- source/loader/ur_libapi.cpp
- source/ur_api.cpp
Mark all functions in the API who allocate handles (which must later be
free'd with `Release*` or similar with an `[alloc]` annotation.
----
I've marked the functions I feel should be free'd with the "Release" family of functions, mostly functions named "Create"
or that return events, but I'm not 100% sure I've not miscategorized any. Any feedback is appreciated.
> In docs, mark "allocating" functions as such

- .github/workflows/benchmarks-reusable.yml
- .github/workflows/benchmarks.yml
- scripts/benchmarks/README.md
- scripts/benchmarks/main.py
- scripts/benchmarks/options.py
- scripts/benchmarks/output_markdown.py
🥺 add an option for limiting markdown content size
🥺 calculate relative performance with different baselines
🥺 calculate relative performance using only already saved data
🥺 group results according to suite names and explicit groups
🥺 add multiple data columns if multiple --compare specified
An [example](https://github.com/EuphoricThinking/unified-memory-framework/pull/1#issuecomment-2624875443) of the previous output design
> change markdown output in benchmark PR comments

- .github/workflows/benchmarks-reusable.yml
The results from the benchmark run should be always compared against baseline. This is a temporary solution before more baselines could be available.
> add comparing to baseline in benchmark workflow

- test/conformance/memory/urMemRetain.cpp
This is required for intel/llvm.
> [NFC] Format c++ code

- scripts/move-pr-to-intel-llvm.py
* Added an `--allow-dirty` option to skip the dirty git repo checks.
Untracked files trip this check up but don't seem to cause any
problems.
* The default `intel-base-branch` is now "sycl"
* Specifically say "LLVM" branch when talking about feature branches.
* Push to `intel_llvm_push_remote` rather than origin.
* Closing a pull request now uses a string when building the command.
> Improvements to the move-pr-to-intel-llvm script

- .github/workflows/pr-migration-auto-close.yml
- .github/workflows/pr-migration-warn.yml
Add two new workflows to warn PR authors about the intel/llvm migration, label PRs and automatically close them after 30 days.
- `pr-migration-warn.yml`
- comments on new PRs (also reopened, edited, marked ready for review or synchronized) explaining the move to intel/llvm
- label the PR with the new `auto-close` label
- will only run when `auto-close` is not present
- `pr-migration-auto-close.yml`
- runs once daily and checks for any `auto-close` labelled PRs older than 30 days, and closes them with an additional comment about the intel/llvm migration
Should there be a reason to keep a PR open, simply manually remove the `auto-close` label. The first workflow does not run when PR labels are modified, so it would not run and re-label the PR again.
> Add two new workflows to warn PR authors about the intel/llvm migration

- scripts/mirror-commits-from-intel-llvm.py
Previously, it used the currently checked out commit, causing desyncs
if the intel llvm directory isn't updated.
> In mirror script, ensure it uses remote sycl

- .github/workflows/benchmarks-nightly.yml
- .github/workflows/benchmarks-reusable.yml
- .github/workflows/benchmarks.yml
- .github/workflows/docs.yml
and update the docs job to use the new format of the html dashboard.
> restore performance workflow

- source/adapters/level_zero/memory.cpp
- source/adapters/level_zero/memory.hpp
This commit fixes an issue where the sub-buffer object in the L0 V1 adapter would not release its retained parent, causing leaks.
> [UR][L0] Release parent of sub-buffer when sub-buffer dies

- .github/workflows/benchmarks-reusable.yml
The BMG nightly job is regularly failing on the first push to the benchmarks-results branch, requiring the benchmark data to be regenerated using a dry-run. However, currently there's an issue with dry-runs where it won't include all the metadata for benchmarks if ur and sycl aren't specified.
This workaround just sets ur/sycl to some values so that the metadata fields are populated. It's a dry-run so these values aren't really being used.
I've been regenerating the metadata manually:
https://github.com/oneapi-src/unified-runtime/actions/runs/14060532242
> fix regenerating htmls using dry run in nightly

- .github/workflows/mirror-intel-llvm-commits.yml
Since GitHub Actions bot is not allowed to push to main, instead periodically create a PR which can be merged by one of the team.
> Automate PR containing intel/llvm mirror commits

- .github/workflows/mirror-intel-llvm-commits.yml
* Set the path to the UR checkout to create the PR with
* Only trigger the workflow once a day instead of every hour
> Fix intel/llvm mirror commits job

- .github/workflows/benchmarks-reusable.yml
and use benchmark scripts from SYCL version specified by the user.
> [Benchmarks] Only checkout SYCL repo once

- .github/workflows/docs.yml
We are moving perf CI to intel/llvm. Redirect the old URL.
> [Benchmarks] redirect perf location to intel/llvm

- .github/workflows/mirror-intel-llvm-commits.yml
- scripts/mirror-commits-from-intel-llvm.py
Tested on upsteram (with dry-run push): https://github.com/oneapi-src/unified-runtime/actions/runs/17102368654/job/48502177190#step:7:1
`git log` looks good and also I compared it with open PR (https://github.com/oneapi-src/unified-runtime/pull/2834) and also looks ok.
> Mirror commits from intel/llvm without PRs
