oneapi-src/unified-runtime

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/YaML.md
scripts/core/context.yml
scripts/core/module.yml
scripts/templates/api.h.mako
scripts/templates/api.py.mako
scripts/templates/helper.py

Adds infra for generating function pointer typedef for C and Python bindings.

Adding function pointer type for C/C++ and Python

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/module.yml
scripts/core/program.yml

[ur] Values for sizeof allocations should use size_t

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/context.yml
scripts/core/device.yml
scripts/core/event.yml
scripts/core/kernel.yml
scripts/core/platform.yml
scripts/core/program.yml

[ur] Stop using [in,out] pointers for queries

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/common.yml
scripts/core/misc.yml

Fixes https://github.com/oneapi-src/unified-runtime/issues/16.

Add GetLastError API

---

include/ur.py
include/ur_api.h
scripts/core/memory.yml

[ur] add ur_image_info_t enumeration

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/memory.yml
scripts/core/usm.yml

[ur] Add ur_mem_info_t enum

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/context.yml
scripts/core/device.yml
scripts/core/event.yml
scripts/core/kernel.yml
scripts/core/memory.yml
scripts/core/module.yml
scripts/core/platform.yml
scripts/core/program.yml
scripts/core/queue.yml
scripts/core/sampler.yml
source/ur_api.cpp

[ur] Remove unnecessary platform handle

---

include/ur.py
include/ur_api.h
scripts/core/enqueue.yml
scripts/core/event.yml
scripts/core/memory.yml
scripts/core/sampler.yml
scripts/core/usm.yml
source/ur_api.cpp

[ur] Cleanup enum names

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/program.yml
source/ur_api.cpp

Fixes another in/out pointer issue I noticed.

[ur] Fix inout pointer in urProgramGetBuildInfo

---

scripts/core/PROG.rst

Fixes some error seen during generation of headers

Fix some errors seen during generation of docs

---

include/ur_api.h
scripts/core/device.yml
scripts/core/platform.yml
source/ur_api.cpp

Fix `urPlatformGet` & `urDeviceGet` to return `UR_RESULT_ERROR_INVALID_SIZE`

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/context.yml
scripts/core/enqueue.yml
source/drivers/null/ur_nullddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

[ur] Implement USM 2D operations

---

scripts/core/INTRO.rst

I couldn't find any reference to environment variables that we use currently so I've put in a placeholder currently to demonstrate the feature, although I'm not sure about placing in fake information in our docs. Perhaps we need a discussion of what environment variables we want or will these just be introduced based on requirements?
Closes #140

[UR] Document Environment Variables

---

include/ur.py
include/ur_api.h
scripts/core/device.yml
scripts/core/event.yml

Fixes some small changes that were not caught from two previous changes:
#191 & #189

[ur] Fix unresolved references

---

.github/workflows/cmake.yml
CMakeLists.txt
README.md
cmake/helpers.cmake
source/common/ur_util.hpp

add support for ubsan/asan/msan in cmakes

---

source/common/unified_memory_allocation/include/uma/base.h
source/common/unified_memory_allocation/include/uma/memory_pool.h
source/common/unified_memory_allocation/include/uma/memory_pool_ops.h
source/common/unified_memory_allocation/include/uma/memory_provider.h
source/common/unified_memory_allocation/include/uma/memory_provider_ops.h
source/common/unified_memory_allocation/src/memory_pool.c
source/common/unified_memory_allocation/src/memory_provider.c
test/unified_memory_allocation/common/pool.c
test/unified_memory_allocation/common/provider.c
test/unified_memory_allocation/memoryPool.cpp
test/unified_memory_allocation/memoryProvider.cpp

[uma] add get_last_result and refactor results enum

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/usm.yml
source/drivers/null/ur_nullddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/testing/uur/checks.h
test/conformance/usm/urMemGetMemAllocInfo.cpp

[ur] Cleanup USM enueration names

---

test/conformance/device/urDevicePartition.cpp

Add tests for UR_DEVICE_PARTITION_BY_COUNTS and UR_DEVICE_PARTITION_BY_AFFINITY_DOMAIN flags

Add more tests for urDevicePartition()

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/usm.yml
source/drivers/null/ur_nullddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/testing/uur/fixtures.h
test/conformance/usm/CMakeLists.txt
test/conformance/usm/urUSMDeviceAlloc.cpp
test/conformance/usm/urUSMFree.cpp
test/conformance/usm/urUSMGetMemAllocInfo.cpp
test/conformance/usm/urUSMHostAlloc.cpp
test/conformance/usm/urUSMSharedAlloc.cpp

[ur] Make USM entry point names consistent

---

CMakeLists.txt
source/common/unified_memory_allocation/CMakeLists.txt

This might be useful for prototype integration with OpenMP

[uma] allow building UMA as shared library

---

source/loader/ur_loader.cpp

Signed-off-by: Jaime Arteaga <jaime.a.arteaga.molina@intel.com>

[ur] Remove extra semicolons

---

source/common/unified_memory_allocation/include/uma/base.h
source/common/unified_memory_allocation/src/memory_pool.c
source/common/unified_memory_allocation/src/memory_provider.c

and add missing 'ERROR' to UMA_RESULT_OUT_OF_HOST_MEMORY

[uma] add INVALID_ARGUMENT error code

---

.clang-format
.github/workflows/cmake.yml
CMakeLists.txt
README.md
source/common/ur_singleton.hpp
source/common/ur_util.hpp
source/drivers/null/ur_null.cpp
source/drivers/null/ur_nullddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_ldrddi.hpp
source/loader/ur_libapi.cpp
source/loader/ur_libddi.cpp
source/loader/ur_loader.cpp
source/loader/windows/platform_discovery_win.cpp
source/ur_api.cpp
test/conformance/usm/urUSMGetMemAllocInfo.cpp
third_party/requirements.txt

[ur] Fix clang-format

---

test/conformance/event/urEventGetNativeHandle.cpp

[ur] Add CTS for  urEventGetNativeHandle

---

include/ur.py
include/ur_api.h
scripts/core/queue.yml
test/conformance/queue/urQueueCreate.cpp

[ur] Add tests for queues with properties

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/PROG.rst
scripts/core/common.yml
scripts/core/enqueue.yml
scripts/core/usm.yml
source/drivers/null/ur_nullddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_ldrddi.hpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/enqueue/urEnqueueUSMMemcpy.cpp
test/conformance/enqueue/urEnqueueUSMMemset.cpp
test/conformance/enqueue/urEnqueueUSMMemset2D.cpp
test/conformance/testing/uur/fixtures.h
test/conformance/usm/urUSMDeviceAlloc.cpp
test/conformance/usm/urUSMFree.cpp
test/conformance/usm/urUSMHostAlloc.cpp
test/conformance/usm/urUSMSharedAlloc.cpp

and extend ur_usm_mem_flags_t and ur_mem_advice_t
Closes: https://github.com/oneapi-src/unified-runtime/issues/142
Closes: https://github.com/oneapi-src/unified-runtime/issues/176
Closes: https://github.com/oneapi-src/unified-runtime/issues/116

[ur] Add urUSMPoolCreate

---

CMakeLists.txt
source/common/unified_memory_allocation/src/memory_pool.c
source/common/unified_memory_allocation/src/memory_provider.c
test/unified_memory_allocation/common/pool.c
test/unified_memory_allocation/common/provider.c

Add missing '*.c' to format_src

---

include/ur_api.h
scripts/core/usm.yml
source/drivers/null/ur_nullddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/testing/uur/fixtures.h
test/conformance/usm/urUSMDeviceAlloc.cpp
test/conformance/usm/urUSMFree.cpp
test/conformance/usm/urUSMHostAlloc.cpp
test/conformance/usm/urUSMSharedAlloc.cpp

This PR clarifies USM allocation entry-points:
* Add additional error code checks for support and alignment
* Fix tests to check for USM support
* Test `urUSMFree` with each type of USM allocation

[spec] Clarify USM allocation entry-points

---

test/conformance/enqueue/urEnqueueUSMMemAdvise.cpp
test/conformance/testing/uur/fixtures.h

[CTS] Add urEnqueueUSMMemAdvise tests

---

include/ur_api.h
scripts/core/enqueue.yml
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/enqueue/urEnqueueUSMFill2D.cpp
test/conformance/enqueue/urEnqueueUSMMemset2D.cpp

Add tests for urEnqueueUSMFill2D

---

source/loader/layers/tracing/ur_trcddi.cpp

PR #320 generated sources before tracing layer was added

[ur] regenerate sources for tracking layer

---

include/ur.py
include/ur_api.h
scripts/core/kernel.yml
scripts/core/program.yml

The new wording should make a bit more sense with the latest changes to the compiler API.

Add a bit of spec detail to the PROGRAM_BUILD_INFO_OPTIONS query.

---

source/loader/linux/platform_discovery_lin.cpp

Register Level zero adapter library with known platforms

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/kernel.yml
scripts/core/usm.yml
source/drivers/null/ur_nullddi.cpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

- fixes small typos
Closes #141

[ur] Remove  argument from urKernelSetArgPointer

---

include/ur_api.h
scripts/core/kernel.yml
scripts/core/program.yml
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

Also replace INVALID_VALUE with INVALID_SIZE in a couple of places.

Add missing validation clause to ProgramLink.

---

include/ur.py
include/ur_api.h
scripts/Doxyfile
scripts/core/platform.yml
scripts/templates/libddi.cpp.mako
scripts/templates/trcddi.cpp.mako
scripts/templates/valddi.cpp.mako
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/ur_proxy_layer.hpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libddi.cpp
source/loader/ur_loader.hpp
test/layers/tracing/hello_world.out.match

[ur] adjust api version to 0.6

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/common.yml
scripts/core/usm.yml
source/drivers/null/ur_nullddi.cpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/usm/urUSMSharedAlloc.cpp

[ur] Add separate host/device descriptors to 'urUSMSharedAlloc'

---

include/ur.py
include/ur_api.h
scripts/core/device.yml
scripts/core/usm.yml
source/loader/ur_libapi.cpp
source/ur_api.cpp

Small fixes to the YAML:
* `desc` -> `decl`
* removes duplicate desc

[ur] Fix yaml problems

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/enqueue.yml
scripts/core/usm.yml
source/drivers/null/ur_nullddi.cpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/enqueue/urEnqueueUSMAdvise.cpp
test/conformance/usm/urUSMSharedAlloc.cpp

To allow setting multiple advices during allocation
Closes: https://github.com/oneapi-src/unified-runtime/issues/337.

[ur] convert ur_usm_advice_t into ur_usm_advice_flag_t

---

scripts/generate_ids.py

Registry id wasn't being properly read during spec parsing...

[ur] fix existing id registry parsing

---

scripts/templates/ldrddi.cpp.mako
scripts/templates/ldrddi.hpp.mako
scripts/templates/trcddi.cpp.mako
scripts/templates/valddi.cpp.mako
source/common/linux/ur_lib_loader.cpp
source/common/ur_lib_loader.hpp
source/common/windows/ur_lib_loader.cpp
source/loader/layers/tracing/ur_tracing_layer.cpp
source/loader/layers/tracing/ur_tracing_layer.hpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/backtrace.hpp
source/loader/layers/validation/backtrace_lin.cpp
source/loader/layers/validation/backtrace_win.cpp
source/loader/layers/validation/ur_leak_check.hpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/layers/validation/ur_validation_layer.cpp
source/loader/layers/validation/ur_validation_layer.hpp
source/loader/linux/loader_init.cpp
source/loader/ur_adapter_registry.hpp
source/loader/ur_ldrddi.cpp
source/loader/ur_ldrddi.hpp
source/loader/ur_lib.cpp
source/loader/ur_loader.cpp
source/loader/ur_loader.hpp
source/loader/windows/lib_init.cpp
source/loader/windows/loader_init.cpp

Rename namespaces to avoid conflicts with L0 loader

---

include/ur.py
include/ur_api.h
scripts/core/kernel.yml
source/common/ur_params.hpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

[UR] Add UR_KERNEL_INFO_NUM_REGS enumeration

---

include/ur.py
include/ur_api.h
scripts/core/context.yml
source/common/ur_params.hpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

[UR] Add Context query enums for atomic capabilities

---

test/conformance/CMakeLists.txt
test/conformance/device_code/CMakeLists.txt
test/conformance/device_code/nop.cpp
test/conformance/program/CMakeLists.txt
test/conformance/program/urProgramCreateWithIL.cpp
test/conformance/source/environment.cpp
test/conformance/testing/include/uur/environment.h
test/conformance/testing/include/uur/fixtures.h

Also implement tests for urProgramCreateWithIL entry point.

Add a simple mechanism to generate test binaries from sycl source files.

---

test/conformance/device/urDevicePartition.cpp

[UR] Fix device tests that skip

---

include/ur.py
include/ur_api.h
scripts/core/kernel.yml
source/common/ur_params.hpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

[UR] Add kernel exec info property cache options

---

.github/workflows/cmake.yml

This will likely keep failing until #448 is merged.

add clang to the CI workflow

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/common.yml
scripts/core/kernel.yml
source/common/ur_params.hpp
source/drivers/null/ur_nullddi.cpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

Add needed members for PI:
Program
OwnNativeHandle

Expand urKernelCreateWithNativeHandle

---

test/conformance/memory/urMemBufferPartition.cpp
test/conformance/memory/urMemImageCreate.cpp

Small fixes/improvements to memory cts tests

[UR][CTS] Fixes for memory tests

---

include/ur.py
include/ur_api.h
scripts/core/device.yml

Clarify description of UR_DEVICE_INFO_IMAGE_SRGB

---

include/ur.py
include/ur_api.h
scripts/core/device.yml
source/common/ur_params.hpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/device/urDeviceGetInfo.cpp

Added missing enums for ur_device_info_t.

---

include/ur.py
include/ur_api.h
scripts/core/enqueue.yml
source/common/ur_params.hpp

Address [!479](https://github.com/oneapi-src/unified-runtime/issues/479)

Add WRITE_INVALIDATE_REGION to ur_map_flags

---

include/ur.py
include/ur_api.h
scripts/core/usm.yml
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/usm/urUSMDeviceAlloc.cpp
test/conformance/usm/urUSMHostAlloc.cpp

to urUSM*Alloc and urUSMPoolCreate functions.
Also, add tests for chained descriptors for Host
and Device allocations.

[ur] add missing documentation about chained param

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/common.yml
scripts/core/event.yml
source/adapters/null/ur_nullddi.cpp
source/common/ur_params.hpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/event/urEventCreateWithNativeHandle.cpp
test/conformance/event/urEventGetNativeHandle.cpp

Add needed members for PI:
OwnNativeHandle

Expand urEventCreateWithNativeHandle

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/device.yml
scripts/core/enqueue.yml
scripts/core/event.yml
scripts/core/registry.yml
source/adapters/null/ur_nullddi.cpp
source/common/ur_params.hpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/device/urDeviceGetInfo.cpp
test/conformance/enqueue/CMakeLists.txt
test/conformance/enqueue/urEnqueueReadHostPipe.cpp
test/conformance/enqueue/urEnqueueWriteHostPipe.cpp
test/conformance/testing/include/uur/fixtures.h
test/conformance/testing/include/uur/utils.h
test/conformance/testing/source/utils.cpp

See #400
Success testing is not included in this PR as it requires a very specific setup (typically only FPGAs support the pipes feature so a supported device and kernel would be required). A follow up ticket will be created for this.

[UR] Enable support for host pipe read/write commands

---

include/ur.py
include/ur_api.h
scripts/core/common.yml
scripts/core/runtime.yml
scripts/generate_code.py
source/loader/ur_libapi.cpp
source/ur_api.cpp

UR loads adapters, and adapters are the ones loading drivers.

Change "driver" to "adapter" in some places

---

CMakeLists.txt
cmake/helpers.cmake

[UR] Escape string for processing by regex

---

include/ur.py
include/ur_api.h
scripts/core/device.yml
source/common/ur_params.hpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/device/urDeviceGetInfo.cpp

[UR] Add UR_DEVICE_INFO_MAX_REGISTERS_PER_WORK_GROUP

---

scripts/templates/ldrddi.cpp.mako
source/loader/ur_ldrddi.cpp
source/loader/ur_lib.cpp
source/loader/ur_loader.cpp
test/loader/CMakeLists.txt
test/loader/platforms/CMakeLists.txt
test/loader/platforms/no_platforms.match
test/loader/platforms/null_platform.match
test/loader/platforms/platforms.cpp

[loader] don't fail with no platforms present

---

.github/workflows/cmake.yml
CMakeLists.txt
examples/collector/CMakeLists.txt
source/loader/CMakeLists.txt
source/loader/layers/validation/backtrace_libbacktrace.cpp
tools/urtrace/CMakeLists.txt
tools/urtrace/urtrace

Requires #534 
- add libbacktrace builds in CI
- fixes UR build issue when libbacktrace is used

[ci] Test tracing using libbacktrace

---

source/common/logger/ur_sinks.hpp
source/loader/linux/loader_location.cpp
source/loader/ur_adapter_registry.hpp
source/loader/ur_loader_location.hpp
source/loader/windows/loader_location.cpp
test/unit/logger/fixtures.hpp
test/unit/logger/logger.cpp

Resolves: https://github.com/oneapi-src/unified-runtime/issues/547

Fix filesystem

---

include/ur_api.h
scripts/core/context.yml
scripts/core/device.yml
scripts/core/event.yml
scripts/core/kernel.yml
scripts/core/memory.yml
scripts/core/platform.yml
scripts/core/program.yml
scripts/core/queue.yml
scripts/core/sampler.yml
scripts/core/usm.yml
source/adapters/null/ur_nullddi.cpp
source/common/ur_params.hpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/context/urContextGetInfo.cpp
test/conformance/device/urDeviceGetInfo.cpp
test/conformance/event/urEventGetInfo.cpp
test/conformance/kernel/urKernelGetInfo.cpp
test/conformance/memory/urMemGetInfo.cpp
test/conformance/platform/urPlatformGetInfo.cpp
test/conformance/program/urProgramGetInfo.cpp
test/conformance/queue/urQueueGetInfo.cpp
test/conformance/sampler/urSamplerGetInfo.cpp
test/conformance/usm/urUSMPoolGetInfo.cpp

Make GetInfo queries consistent and tested

---

.github/workflows/coverity.yml
examples/collector/collector.cpp
scripts/templates/ldrddi.cpp.mako
scripts/templates/ldrddi.hpp.mako
source/common/logger/ur_logger_details.hpp
source/common/unified_memory_allocation/src/memory_tracker.cpp
source/common/ur_singleton.hpp
source/loader/ur_ldrddi.cpp
source/loader/ur_ldrddi.hpp
source/loader/ur_object.hpp
test/unified_memory_allocation/common/base.hpp
test/unified_memory_allocation/common/pool.hpp
test/unified_memory_allocation/memoryPoolAPI.cpp
test/unit/logger/fixtures.hpp
test/unit/logger/logger.cpp

I assumed that nullptr checks in UR API are not necessary. If given handle ptr is not an array such checks do not exist, which is inconsistent. Might add nullptr checks if required.

[coverity] Fix Coverity issues

---

test/conformance/source/environment.cpp
test/conformance/testing/include/uur/environment.h

- fix copy instead of move issue

[ur] fix minor coverity issues

---

include/ur.py
include/ur_api.h
scripts/core/event.yml
source/common/ur_params.hpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

Enum present in OpenCL was missing in UR.

Add UR_PROFILING_INFO_COMMAND_COMPLETE to ur_profling_info_t.

---

scripts/core/CONTRIB.rst

For pull requests which introduce experimental features, document that
the *experimental* label should be used.

[ur] Document adding the experimental label

---

include/ur_api.h
scripts/core/registry.yml
scripts/generate_ids.py

[UR] Assign registry IDs from largest value

---

include/ur_api.h
scripts/core/INTRO.rst
scripts/core/program.yml
scripts/generate_docs.py
scripts/run.py

Remove the last remaining references to level zero.

[UR] Remove references to Level Zero

---

source/common/uma_helpers.hpp
source/common/uma_pools/disjoint_pool.cpp
source/common/uma_pools/disjoint_pool.hpp

Add try/catch to uma_helpers and lift the requirement for pool/provider functions to be noexcept.

[ur] fix 'uncaught exception' error from coverity

---

CMakeLists.txt
include/ur.py
include/ur_api.h
scripts/core/device.yml
scripts/run.py
source/common/ur_params.hpp

[UR] Format ur_api.h to fix doxygen rendering

---

scripts/add_experimental_feature.py
scripts/core/CONTRIB.rst
scripts/templates/exp_feat.rst.mako
scripts/templates/exp_feat.yml.mako

Adds a script to generate template files for experimental feature additions.
I'm going to keep this draft initially as it would be useful to discuss what should/shouldn't be included in these templates.
Closes #600

[UR] Add script to generate experimental feature template files

---

scripts/core/CONTRIB.rst
scripts/core/INTRO.rst

[UR] Unify Naming Convention sections

---

include/ur.py
include/ur_api.h
scripts/core/registry.yml
scripts/generate_ids.py
scripts/templates/helper.py
scripts/util.py
source/common/ur_params.hpp
source/loader/layers/tracing/ur_trcddi.cpp

[ur] fix snake case conversion with numbers

---

include/ur_api.h
scripts/core/memory.yml
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/memory/urMemImageGetInfo.cpp
test/conformance/testing/include/uur/fixtures.h

[UR][CTS] Add urMemImageGetInfo tests and missing spec return values

---

test/conformance/CMakeLists.txt
test/conformance/virtual_memory/CMakeLists.txt
test/conformance/virtual_memory/urPhysicalMemCreate.cpp
test/conformance/virtual_memory/urPhysicalMemRelease.cpp
test/conformance/virtual_memory/urPhysicalMemRetain.cpp
test/conformance/virtual_memory/urVirtualMemFree.cpp
test/conformance/virtual_memory/urVirtualMemGetInfo.cpp
test/conformance/virtual_memory/urVirtualMemGranularityGetInfo.cpp
test/conformance/virtual_memory/urVirtualMemMap.cpp
test/conformance/virtual_memory/urVirtualMemReserve.cpp
test/conformance/virtual_memory/urVirtualMemSetAccess.cpp
test/conformance/virtual_memory/urVirtualMemUnmap.cpp

Setup Virtual memory CTS files:
- Hopefully this will avoid conflicts with multiple people working on this.

[UR] Setup Virtual Memory CTS template

---

include/ur_api.h
scripts/core/virtual_memory.yml
source/adapters/null/ur_nullddi.cpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
test/conformance/testing/include/uur/fixtures.h
test/conformance/virtual_memory/urPhysicalMemCreate.cpp
test/conformance/virtual_memory/urPhysicalMemRelease.cpp
test/conformance/virtual_memory/urPhysicalMemRetain.cpp

[UR][CTS] Test urPhysicalMem entry-points

---

test/conformance/enqueue/CMakeLists.txt
test/conformance/enqueue/urEnqueueMemImageCopy.cpp
test/conformance/enqueue/urEnqueueMemImageFill.cpp
test/conformance/enqueue/urEnqueueMemImageMap.cpp

Also remove image map and fill test files as they no longer exist in the API

[UR][CTS] Add tests for urEnqueueMemImageCopy

---

test/conformance/platform/CMakeLists.txt
test/conformance/platform/urPlatformGetApiVersion.cpp

[UR][CTS] Add tests for urPlatformGetApiVersion

---

test/conformance/platform/CMakeLists.txt
test/conformance/platform/urPlatformCreateWithNativeHandle.cpp
test/conformance/platform/urPlatformGetNativeHandle.cpp

[UR][CTS] Add tests for urPlatformGetNaitiveHandle and urPlatformCreateWithNativeHandle

---

README.md

Coverity finally started working correctly. Thanks @wlemkows.

Add coverity badge to README

---

source/common/umf_helpers.hpp
test/unified_malloc_framework/memoryPoolAPI.cpp
test/unified_malloc_framework/umf_pools/disjoint_pool.cpp

This will simplify memory provider lifetime management in adapters.

[umf] add extra poolMakeUnique overload to helpers

---

include/ur.py
include/ur_api.h
scripts/core/platform.yml
source/common/ur_params.hpp

Adds a constant to identify the Native CPU backend adapter.

[UR] Added Native CPU constants

---

source/common/umf_helpers.hpp

Simple helper function for UMF error translation.

[umf] add error translation function to helpers

---

include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/core/EXP-BINDLESS-IMAGES.rst
scripts/core/exp-bindless-images.yml
source/adapters/null/ur_nullddi.cpp
source/common/ur_params.hpp
source/loader/layers/tracing/ur_trcddi.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_ldrddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

Updated some interop struct and function parameter names to adhere to convention.

[Bindless][Exp] Update struct and param naming style to adhere to convention

---

source/common/logger/ur_sinks.hpp

that appeared on intel/llvm CI

[ur] fix ctad-maybe-unsupported warning

---

test/conformance/adapters/CMakeLists.txt
test/conformance/adapters/cuda/CMakeLists.txt
test/conformance/adapters/cuda/cuda_fixtures.h
test/conformance/adapters/cuda/cuda_urContextGetNativeHandle.cpp
test/conformance/adapters/cuda/cuda_urDeviceCreateWithNativeHandle.cpp
test/conformance/adapters/cuda/cuda_urDeviceGetNativeHandle.cpp
test/conformance/adapters/cuda/cuda_urEventCreateWithNativeHandle.cpp
test/conformance/adapters/cuda/cuda_urEventGetNativeHandle.cpp

#756 Introduced some new files which were missing License descriptions at the top of each file. This PR adds the missing license comments

[UR] Add license to missing files

---

README.md
test/conformance/CMakeLists.txt

Add cmake warning about setting UR_CONFORMANCE_TARGET_TRIPLES

---

test/conformance/adapters/hip/hip_urDeviceGetNativeHandle.cpp

[ur][adapters][hip] fix potential strict-aliasing violation

---

test/conformance/enqueue/urEnqueueMemBufferFill.cpp
test/conformance/enqueue/urEnqueueUSMFill.cpp
test/conformance/enqueue/urEnqueueUSMFill2D.cpp
test/conformance/testing/include/uur/fixtures.h

This effectively ports some cases from the old PI unit tests.

Add some parameterization to MemBufferFill tests.

---

CMakeLists.txt
include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/Doxyfile
scripts/core/platform.yml
scripts/parse_specs.py
source/ur_api.cpp

[ur] Bump version to v0.8 on main branch

---

source/loader/ur_adapter_registry.hpp

Allow loader to find HIP and openCL adapters

[loader] Add more known adapters to list

---

.github/workflows/cmake.yml
test/fuzz/CMakeLists.txt
test/fuzz/README.md
test/fuzz/corpus/README.md

This is partially in response to review comments left here: https://github.com/oneapi-src/unified-runtime/pull/795/files

Small updates in fuzz tests

---

test/conformance/event/urEventSetCallback.cpp
test/conformance/memory/urMemGetInfo.cpp

Fix CTS to check for the correct error codes.

[UR] Fixup minor CTS issues

---

test/conformance/program/urProgramGetBuildInfo.cpp
test/conformance/program/urProgramGetInfo.cpp

Asserts on the correct behaviour expected to return from program entry-points.

[UR] Fix program CTS assesion checks

---

include/ur_api.h
scripts/core/enqueue.yml
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp

- Added extra conditions to the validation layers of urEnqueueMemBufferFill, urEnqueueMemImageCopy, urEnqueueMemImageWrite and urEnqueueMemImageReady

Update specification for urEnqueue entrypoints

---

.github/workflows/cmake.yml

[ADAPTERS] Cherry-pick "Temporarily disable running check-generated target in windows CI."

---

.github/workflows/cmake.yml

Install doxygen on windows runners, re-enable generating spec on windows

---

source/adapters/cuda/queue.cpp
source/adapters/cuda/queue.hpp

This PR cherry-picks a commit that was recently merged to intel/llvm: https://github.com/intel/llvm/pull/11297/files

[CUDA] Cherry-pick commit from intel/llvm

---

source/adapters/level_zero/context.cpp
source/adapters/level_zero/event.cpp

- Second return has no effect
- Checking the same flag twice has no effect
No functional changes expected

[UR][L0] Fix minor code duplication

---

CMakeLists.txt
cmake/helpers.cmake
include/ur.py
include/ur_api.h
include/ur_ddi.h
scripts/Doxyfile
scripts/ci.py
scripts/core/INTRO.rst
scripts/core/platform.yml
scripts/parse_specs.py
scripts/templates/params.hpp.mako
source/common/CMakeLists.txt
source/common/linux/ur_lib_loader.cpp
source/common/ur_params.hpp
source/loader/ur_adapter_registry.hpp
source/ur_api.cpp
test/conformance/context/context_adapter_level_zero.match
test/conformance/context/urContextCreateWithNativeHandle.cpp
test/loader/loader_config/CMakeLists.txt

Reverts oneapi-src/unified-runtime#1005

Revert "Bump adapters branch"

---

source/adapters/level_zero/queue.cpp

Instead of creating an event, appending, and synchronizing it on it to wait for all commands in an immediate command list, emit a zeCommandListHostSynchronize instead.
LLVM testing: https://github.com/intel/llvm/pull/10003

[UR][L0] Add support for zeCommandListHostSynchronize

---

scripts/core/INTRO.rst

Fixes https://github.com/oneapi-src/unified-runtime/issues/1073

Update Error Handling documentation wording.

---

.github/workflows/e2e_nightly.yml
.github/workflows/nightly.yml
scripts/core/CONTRIB.rst

Update Adapter Change Process to use main branch

---

third_party/requirements.txt

(to trigger dependency graph update)

Sort dependencies in third_party/requirements.txt

---

source/adapters/hip/queue.cpp
source/adapters/hip/queue.hpp

Reverts oneapi-src/unified-runtime#1228

Revert "Revert "[HIP] Implement ext_oneapi_queue_priority""

---

source/adapters/level_zero/kernel.cpp
source/adapters/level_zero/kernel.hpp
source/adapters/level_zero/program.cpp
source/adapters/level_zero/program.hpp
source/adapters/level_zero/queue.cpp

Candidate for v0.8.4 release tag

---

.github/workflows/cmake.yml

The Conda environment setup is consistently failing, disabling the job until we figure out a fix for this.

[CI] Temporarily disable HW examples job

---

source/adapters/level_zero/kernel.cpp
source/adapters/level_zero/program.cpp

- Fix native kernel usage given no kernel creation in kernel map
- fix set of kernel function pointer given multi device
- Fix Global WorkSize variable to use a local variable to avoid invalid memory access.

[L0] Fix native kernel usage, multi device kernel pointer and WorkSize

---

.github/workflows/cmake.yml
CMakeLists.txt
source/adapters/level_zero/CMakeLists.txt
source/adapters/level_zero/kernel.cpp
source/adapters/level_zero/kernel.hpp
source/adapters/level_zero/program.cpp
source/common/ur_util.hpp

Candidate for v0.8.5 release tag

---

CMakeLists.txt
source/adapters/opencl/program.cpp

Candidate for the v0.8.6 release tag

---

scripts/core/CONTRIB.rst
scripts/parse_specs.py
scripts/templates/helper.py
scripts/templates/ldrddi.cpp.mako

Also document limitations of this implementation in CONTRIB.rst

Update scripts and loader template to allow object handles in structs.

---

source/adapters/level_zero/command_buffer.cpp

Fixes the bug introduced in commit 1cd402e.

[EXP][CMDBUF] Reset events for multiple submissions (bugfix)

---

include/ur_print.hpp
scripts/Doxyfile
scripts/templates/api_listing.mako
scripts/templates/print.hpp.mako
scripts/templates/print_helper.py

This PR adds html docs generation for Printing C++ API.
[preview](https://patkamin.github.io/unified-runtime/core/api.html#id628)

[docs] Generate Print C++ API html docs

---

CMakeLists.txt
source/adapters/level_zero/context.cpp
source/adapters/level_zero/context.hpp
source/adapters/level_zero/queue.cpp
source/adapters/level_zero/queue.hpp

Candidate for v0.8.10 release tag

---

scripts/core/CONTRIB.rst

Some minor problems spotted & fix here.

[Docs] Minor fixes for CONTRIB.rst

---

source/adapters/cuda/image.cpp

Add bindless image support for the existing core spec mem types:
- `UR_MEM_TYPE_IMAGE1D_ARRAY`
- `UR_MEM_TYPE_IMAGE2D_ARRAY`.
With these changes these memory/image types can now be created and copied in the CUDA adapter.
Correlated DPC++ PR: [ [SYCL][Bindless][Exp] Add Support For Unsampled Image Arrays #12464 ](https://github.com/intel/llvm/pull/12464)

[Bindless][Exp] Add Support For Image Arrays

---

.github/workflows/coverage.yml

[CI] Disable codecov on push - it doesn't work

---

.github/workflows/bandit.yml
test/conformance/cts_exe.py

I believe we can and should enable more scans for Bandit tool. Right now we only scan tools dir - with my change we scan also at least tests.

[CI] Enable more scans with Bandit

---

include/ur_api.h
include/ur_print.hpp
scripts/core/EXP-BINDLESS-IMAGES.rst
scripts/core/exp-bindless-images.yml
source/adapters/cuda/device.cpp
source/loader/layers/validation/ur_valddi.cpp
source/loader/ur_libapi.cpp
source/ur_api.cpp
tools/urinfo/urinfo.hpp

"Merge pull request #1264 from przemektmalon/przemek/sampled-image-fetch"
This reverts commit 4347e0c19167ef402f2e74ea02eccdfb42016939, reversing changes made to 76115428c7a4d8e5fc5dd067fee1036018d0498e.

Revert #1264

---

README.md

... and remove unusued codecov badge.

add CUDA e2e badge to README

---

source/adapters/native_cpu/threadpool.hpp

Addresses some warnings raised by Coverity in the Native CPU threadpool implementation:
* the `threadId` for each thread is now set when the worker thread is constructed, making it so it always initialized and `const`.
* the worker task is `std::moved`
* the `m_isRunning` member of the worker thread class is now implemented using `std::atomic`
Corresponding DPC++ PR: https://github.com/intel/llvm/pull/13431

[NATIVECPU] Address coverity warnings in threadpool implementation

---

test/conformance/source/environment.cpp

Fix some dead code in `environment.cpp` file.

Fix dead code in environment.cpp

---

CMakeLists.txt
source/adapters/level_zero/adapter.hpp
source/adapters/level_zero/command_buffer.cpp
source/adapters/level_zero/common.cpp
source/adapters/level_zero/common.hpp
source/adapters/level_zero/context.cpp
source/adapters/level_zero/context.hpp
source/adapters/level_zero/device.hpp
source/adapters/level_zero/event.cpp
source/adapters/level_zero/event.hpp
source/adapters/level_zero/image.cpp
source/adapters/level_zero/kernel.cpp
source/adapters/level_zero/memory.cpp
source/adapters/level_zero/queue.cpp
source/adapters/level_zero/queue.hpp
test/adapters/CMakeLists.txt
test/adapters/level_zero/event_cache_tests.cpp
test/adapters/level_zero/zeCallMap.cpp
test/conformance/testing/include/uur/fixtures.h

Candidate for the v0.9.1 release tag

---

.github/workflows/e2e_core.yml
.github/workflows/e2e_level_zero.yml
README.md

Creating as draft because runners are not added yet.

add level zero e2e workflow

---

CMakeLists.txt
source/adapters/level_zero/kernel.cpp

Candidate for the v0.9.3 release tag

---

source/adapters/level_zero/device.cpp

When being queried a device version:
- CUDA adapter returns the compute capability version of the device,
- HIP adapter returns the architecture name.
Both of these are what define a GPU architecture to compile binaries for and can be used with GPU compilers, this is useful information for applications and developers.
On L0/Intel side, prior to this change, it returns the L0 API version. This information is already returned in BACKEND_RUNTIME_VERSION and DRIVER_VERSION queries.
With this change, we align the adapters behavior with CUDA and HIP, and return the Intel device architecture version that can be used with ocloc compiler.
https://github.com/intel/llvm/pull/13812

[UR][L0] Return device version based on DeviceIpVersion

---

test/conformance/integration/integration_adapter_hip.match
test/conformance/kernel/kernel_adapter_cuda.match
test/conformance/kernel/kernel_adapter_hip.match

* Integration tests are passing on CUDA
* Kernel tests are not crashing on CUDA and HIP
* NullHandle and set local arg kernel tests are passing on CUDA

[CTS] Update CUDA and HIP match files

---

CMakeLists.txt
source/adapters/level_zero/kernel.cpp
source/adapters/level_zero/program.cpp

Candidate for the v0.9.4 release tag

---

source/adapters/level_zero/kernel.cpp

Defines `urKernelSuggestMaxCooperativeGroupCountExp` and `urEnqueueCooperativeKernelLaunchExp` to enable cooperative kernels with more than one work group.

Implement L0 cooperative kernel functions

---

CMakeLists.txt
source/adapters/level_zero/event.cpp
test/adapters/level_zero/CMakeLists.txt
test/adapters/level_zero/event_cache_tests.cpp
test/adapters/level_zero/multi_device_event_cache_tests.cpp

Candidate for the v0.9.5 release tag

---

.github/workflows/codeql.yml

The Windows CodeQL job started failing for PRs for no apparent reason.

Update CodeQL to latest and disable it for PRs

---

source/adapters/hip/device.cpp
test/conformance/device/device_adapter_hip.match

This is mostly just a copy of the CUDA version of this implementation.

[HIP] Implement urDeviceGetNativeHandle

---

.github/workflows/cmake.yml
.github/workflows/e2e_core.yml

fix permissions in e2e workflow

---

source/adapters/level_zero/command_buffer.cpp

For out-of-order command-lists in the UR command-buffer we always create a L0 event to synchronize the commands.
However, this L0 event is only registered with the command-buffer when there is a return sync-point to associate it with. This means that if no return sync-point is passed, then the L0 event is leaked as the command-buffer won't free it on destruction.
Fixed by always registering the L0 event with a sync point, regardless of if a return sync point is passed.
DPC++ PR https://github.com/intel/llvm/pull/14028

Fix L0 Event leak without return sync point

---

scripts/core/PROG.rst

Add a short section for Memory in UR, which says how ur_mem_handle_ts can be expected to work.

[UR] Add some information about buffers in spec

---

scripts/core/EXP-BINDLESS-IMAGES.rst

Include image arrays in list of supported bindless images.

[Bindless][Exp] Add image arrays to bindless images doc 

---

source/adapters/hip/queue.cpp
test/conformance/queue/queue_adapter_hip.match

This fixes the UR CTS queue tests

[HIP] Add missing queue properties

---

source/adapters/hip/common.hpp
source/adapters/hip/usm.cpp
test/conformance/usm/usm_adapter_hip.match

Also refactor some common code into helper methods.

[HIP] Add support for querying USM base pointer

---

test/conformance/queue/urQueueGetNativeHandle.cpp

Test that an in order queue will return the same backend queue when calling urQueueGetNativeHandle.
Ping @JackAKirk

[UR] Test that an in order queue returns same backend q

---

scripts/core/PROG.rst

Clarify the wording in a few places.

[UR][doc] Reword some programming guide sections

---

CMakeLists.txt
source/adapters/level_zero/device.cpp
source/adapters/level_zero/device.hpp
source/adapters/level_zero/event.cpp

* https://github.com/oneapi-src/unified-runtime/pull/1806

Candidate for the v0.8.15 release tag

---

CMakeLists.txt
source/adapters/level_zero/device.cpp
source/adapters/level_zero/device.hpp
source/adapters/level_zero/event.cpp

* https://github.com/oneapi-src/unified-runtime/pull/1806

Candidate for the v0.9.8 release tag

---

source/adapters/cuda/device.cpp
test/adapters/cuda/urDeviceCreateWithNativeHandle.cpp

Fix CUDA Windows build

---

source/adapters/level_zero/command_buffer.cpp
source/adapters/level_zero/common.cpp
source/adapters/level_zero/common.hpp
source/adapters/level_zero/device.cpp

- Checks if compatible L0 driver for default enable
- Allow for force on/off toggle using env variable

[L0] Enable default support for L0 in-order lists

---

source/common/CMakeLists.txt
source/common/ur_util.cpp

- enable static linking with hwloc
- fix linker script for lld

Bump UMF tag and fix syscalls

---

source/common/CMakeLists.txt

bump UMF tag to switch to 0.9.0-rc2 release - this branch contains all latest fixes

bump UMF tag to switch to rc2 release

---

source/loader/CMakeLists.txt

Fix syclos post commit failure:
https://github.com/intel/llvm/actions/runs/10196353773/job/28206962107

[DeviceSanitizer] Add missing required library

---

.github/workflows/e2e_core.yml
.github/workflows/e2e_level_zero.yml

suppressing the latest failing tests

update L0 e2e workflow

---

source/ur/ur.cpp

Update the expected tracing values for https://github.com/intel/llvm/pull/14983

Update expected values of SYCL_UR_TRACE environment variable

---

source/adapters/level_zero/program.cpp
source/adapters/level_zero/program.hpp

- Fix coverity issues program handle init of member variables and program info binary size query given multi device.

[L0] Fixed program info binary size query and fix program handle init

---

source/common/CMakeLists.txt

Ref: https://github.com/oneapi-src/unified-memory-framework/pull/682

[Common] bump umf version to include SOVERSION fix

---

source/common/CMakeLists.txt

to include fix in hwloc configure.
Testing in intel/llvm: https://github.com/intel/llvm/pull/15143

[common] Bump UMF version

---

.github/workflows/e2e_core.yml
.github/workflows/e2e_level_zero.yml

* Update l0 xfail/flakey list
* Rename PI_TRACE -> UR_TRACE

Update e2e config

---

scripts/benchmarks/main.py

This will allow to easily compare perfomance of L0 and L0 v2 adapter (v2 adapter does not yet implement all features needed for all benchmarks).

[Benchmarks] skip failed benchmarks by default

---

scripts/benchmarks/benches/compute.py
scripts/benchmarks/benches/velocity.py
scripts/benchmarks/output.py

- use underscore to highlight better result
- fix passing 'lower_is_better'

[Benchmarks] minor tweaks

---

README.md
source/adapters/hip/CMakeLists.txt

This helps with auto-detection of ROCm installation on some systems.

[HIP] Take ROCm path from environment if available

---

third_party/requirements.txt

[Security] Bump requests

---

source/adapters/cuda/image.cpp

* Add support for sub-region copies.
DPC++ PR: https://github.com/intel/llvm/pull/14954

[Bindless][Exp] Image Array Sub-Region Copies

---

.github/workflows/e2e_level_zero.yml

Removes:
Unexpectedly Passed Tests (2):
SYCL :: DeviceCodeSplit/grf.cpp
SYCL :: KernelAndProgram/target_register_alloc_mode.cpp

update e2e L0 xfail

---

source/common/CMakeLists.txt

it includes the fix for missing/optional symbols.

Bump UMF version to the latest

---

source/adapters/level_zero/device.cpp
test/conformance/enqueue/enqueue_adapter_level_zero.match

Candidate for the v0.10.12 release tag

---

scripts/benchmarks/main.py
scripts/benchmarks/output_html.py

This patch is mostly a few minor changes to the bar charts to make them more legible.

[benchmarks] HTML output improvements

---

scripts/core/LEVEL_ZERO.rst
scripts/templates/index.rst.mako

- Add inital Level Zero Reference document with environment variable definitions.

[L0] Add Level Zero Reference Document

---

source/adapters/level_zero/v2/kernel.cpp
source/adapters/level_zero/v2/kernel.hpp
test/adapters/level_zero/urKernelCreateWithNativeHandle.cpp

Fixes handling optional program argument and kernel to device mapping.

[L0 v2] fix native kernel handle interop

---

source/common/CMakeLists.txt

It contains:
"Fix fetching L0 and CUDA headers and add UMF_CUDA_INCLUDE_DIR"
https://github.com/oneapi-src/unified-memory-framework/pull/832

Update UMF and add fetching CUDA

---

scripts/templates/queue_api.cpp.mako
source/adapters/level_zero/v2/context.cpp
source/adapters/level_zero/v2/event.cpp
source/adapters/level_zero/v2/kernel.cpp
source/adapters/level_zero/v2/memory.cpp
source/adapters/level_zero/v2/queue_api.cpp
source/adapters/level_zero/v2/queue_create.cpp

Needed once https://github.com/oneapi-src/unified-runtime/pull/2216 is merged and to support static linking.

[L0 v2] add try/catch to all API functions

---

scripts/benchmarks/benches/base.py
scripts/benchmarks/benches/compute.py
scripts/benchmarks/benches/llamacpp.py
scripts/benchmarks/benches/result.py
scripts/benchmarks/benches/syclbench.py
scripts/benchmarks/benches/test.py
scripts/benchmarks/benches/velocity.py
scripts/benchmarks/main.py

[Benchmarks] support CPU counter measurements

---

scripts/benchmarks/benches/compute.py

[Benchmarks] Add MemcpyExecute scenario with high ops count

---

README.md

Remove stale link, update third-party tools docs

---

test/adapters/cuda/urDeviceCreateWithNativeHandle.cpp
test/conformance/device/urDeviceGet.cpp
test/conformance/device/urDeviceGetSelected.cpp
test/conformance/memory-migrate/urMemBufferMigrateAcrossDevices.cpp
test/conformance/platform/CMakeLists.txt
test/conformance/platform/fixtures.h
test/conformance/platform/urPlatformCreateWithNativeHandle.cpp
test/conformance/platform/urPlatformGet.cpp
test/conformance/platform/urPlatformGetApiVersion.cpp
test/conformance/platform/urPlatformGetBackendOption.cpp
test/conformance/platform/urPlatformGetInfo.cpp
test/conformance/platform/urPlatformGetNativeHandle.cpp
test/conformance/source/environment.cpp
test/conformance/testing/include/uur/environment.h
test/conformance/testing/include/uur/fixtures.h
test/conformance/testing/include/uur/utils.h

This is another incremental step towards #2378

Enable platform CTS tests to run on all available platforms.

---

test/conformance/event/urEventGetInfo.cpp

Move urEventGetInfo success test from a switch to individual tests

---

scripts/benchmarks/benches/options.py
scripts/benchmarks/main.py

The new parameter reduces the number of loop iterations in standard deviation validity check.

Add a benchmark scripts parameter for faster testing

---

source/adapters/level_zero/command_buffer.cpp

Add barriers to the SignalCommandList that guarantee that resetting the WaitEvent is done at the right time.
This fixes a potential race condition where, if the SignalCommandList executes before the ComputeCommandList, the WaitEvent could be reset before the ComputeCommandList can wait on it and, consequently, create a deadlock.
intel/llvm: https://github.com/intel/llvm/pull/16697

Fix potential deadlock in the WaitEvent path of CmdBuffers

---

include/ur_api.h
include/ur_print.hpp
scripts/core/EXP-BINDLESS-IMAGES.rst
scripts/core/exp-bindless-images.yml
source/adapters/cuda/enqueue.cpp
source/adapters/cuda/enqueue.hpp
source/adapters/cuda/image.cpp

Extends bindless images copies to support device to device pitched copies and host to host copies

[CUDA][Bindless] Add support for device to device pitched copies and host to host copies

---

source/adapters/level_zero/v2/usm.cpp
source/common/ur_pool_manager.hpp

and fix potential memory leak when creating UMF params.

[L0 v2] support SYCL_PI_LEVEL_ZERO_DISABLE_USM_ALLOCATOR

---

source/adapters/level_zero/v2/api.cpp
source/adapters/level_zero/v2/command_buffer.cpp
source/adapters/level_zero/v2/command_list_manager.cpp
source/adapters/level_zero/v2/command_list_manager.hpp
source/adapters/level_zero/v2/queue_immediate_in_order.cpp

This PR implements urCommandBufferAppendUSMMemcpyExp call for level_zero v2 adapter

Add USMMemcpy to v2 command buffer

---

.github/workflows/benchmarks-nightly.yml
.github/workflows/benchmarks-reusable.yml
.github/workflows/benchmarks.yml

Plus minor cleanups and extra comments.
Mostly, the fixes for:
- https://github.com/oneapi-src/unified-runtime/actions/runs/14024319324/job/39260426386#step:19:75
- https://github.com/oneapi-src/unified-runtime/actions/runs/14024319324/job/39260426386#step:17:8

[CI][Bench] Fix for pip packages and fix md file path

---

.github/workflows/benchmarks-nightly.yml
.github/workflows/benchmarks-reusable.yml
.github/workflows/benchmarks.yml
.github/workflows/mirror-intel-llvm-commits.yml

Fix workflows default tokens
