oneapi-src/unified-runtime

include/zer_api.h, scripts/core/enqueue.yml
* `zerEnqueueMemBufferCopyRect` currently accepts a `srcOffset` argument that is of type `size_t`, but also takes a `srcOrigin` which is a struct of three `size_t`s representing a 3D offset and making the `srcOffset` argument redundant. The API also doesn't have a `dstOffset` argument, making it inconsistent with itself. Since `srcOffset` is redundant it is better to remove that than add a `dstOffset`. This also makes it more consistent with the `clEnqueueCopyBufferRect` OpenCL analogue, which doesn't have a `srcOffset` parameter.
=> Remove srcOffset parameter from zerEnqueueMemBufferCopyRect

include/zer_api.h, scripts/core/enqueue.yml
* `zerEnqueueMemBufferCopy` does a linear copy between two buffers viewed as 1D contiguous memory, the description: *The source and destination 2D or 3D rectangular regions can have different shapes.* makes no sense in this context.
=> Remove incorrect documentation from zerEnqueueMemBufferCopy

CMakeLists.txt, include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/YaML.md, scripts/config.ini, scripts/core/common.yml, scripts/core/context.yml, scripts/templates/api.py.mako, scripts/templates/conf.py.mako, source/CMakeLists.txt, source/zer_api.cpp
This patch replaces the zer/ZER namespace prefix with ur/UR to match the Unified Runtime naming of the project.
Fixes #6.
=> Rename API namespace to ur/UR

include/ur.py, include/ur_api.h, scripts/core/device.yml
* `UR_DEVICE_INFO_OPENCL_C_VERSION` is an OpenCL specific query. Unified Runtime devices will not consume OpenCL C, so this should be removed.
=> Remove UR_DEVICE_INFO_OPENCL_C_VERSION query

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/PROG.rst, scripts/core/context.yml, scripts/core/device.yml, scripts/core/event.yml, scripts/core/kernel.yml, scripts/core/memory.yml, scripts/core/module.yml, scripts/core/program.yml, scripts/core/queue.yml, scripts/core/sampler.yml
* UR uses the API `ur{object}GetReference` to increment the reference
count on an object and `ur{object}Release` to decrement the reference
count. This is inconsistent. We should make this consistent. To match
OpenCL (which uses Retain/Release) replace the
`ur{object}GetReference` APIs with `ur{object}Retain`.
=> Replace GetReference with Retain

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/device.yml
* The `SelectedBinary` out parameter of the `urSelectBinary` was missing a pointer in its type.
=> Add pointer to urSelectBinary out param

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/queue.yml
Add `zerQueueFlush` to Unified Runtime.
I've based the semantics from OpenCL, I'm not sure if we need something different for other runtimes.
Closes #41
=> [ur] Add zerQueueFlush

include/ur_api.h, scripts/parse_specs.py
Unified Runtime is a C API. There is no `nullptr` in C but the spec and
headers reference the `nullptr` value. Replace these reference with
`NULL` which is the correct null pointer value in C.
Fixes https://github.com/oneapi-src/unified-runtime/issues/11.
=> Replace nullptr references with NULL

include/ur_api.h, scripts/templates/api.h.mako
Fixes #49 by removing the section which forward declares typedefs in the `api.h.mako` template. First, the forward declarations are unnecessary because the types are already defined where they appear in the header. Second, when compiling with `clang` the following warning is emitted:
```
warning: redefinition of typedef 'ur_base_properties_t' is a C11 feature
```
=> Remove forward declaration of typedefs

include/ur_api.h, scripts/core/program.yml
This fixes a regression introduced in https://github.com/oneapi-src/unified-runtime/commit/46a649a448e3d7097662633c5d11e5086f0cd92a that broke loader scripts, range parameter is now required to properly parse phModules.
=> Add range to phModules

.gitignore, CMakeLists.txt, README.md, cmake/unified-runtime-config.cmake.in, source/CMakeLists.txt, source/ur_api.cpp
This patch adds files to the `install` target along with CMake package configuration files. The goal of these changes is to properly support `FetchContent`, via `find_package`, to ease the integration of unified-runtime into other projects.
The `install` target will now install the following files to the directory specified by the `CMAKE_INSTALL_PREFIX` option.
```
.
├── include
│   ├── ur_api.h
│   ├── ur_ddi.h
│   └── ur.py
└── lib
└── cmake
└── unified-runtime
├── unified-runtime-config.cmake
├── unified-runtime-config-version.cmake
└── unified-runtime-targets.cmake
```
It is now possible to use `find_package` with this install directory in a dependent projects `CMakeLists.txt`, as follows:
```cmake
find_package(unified-runtime 0.5.0 REQUIRED)
add_executable(example example.cpp) …
```
=> cmake: Support install, find_package, & FetchContent

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/templates/api.h.mako, scripts/templates/api.py.mako, scripts/templates/ddi.h.mako
Update the mako templates to stop using identifiers starting with `_` which are reserved for standard library use in both C and C++.
Fixes #18
=> Don't use reserved identifiers

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/misc.yml, scripts/core/platform.yml, source/ur_api.cpp
This makes it possible to have a simple passthrough implementation for this method in the loader. Otherwise we'd have to have a copy of the last error in the loader itself.
=> add platform argument to GetLastResult

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/memory.yml, source/ur_api.cpp
=> [ur] Add urMemImageGetInfo entry point

include/ur.py, scripts/templates/api.py.mako
This patch fixes all issues that were preventing the python bindings from initializing the loader.
=> fix UR_DDI python class init

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/event.yml, source/ur_api.cpp
OpenCL user events, which `urEventCreate` was an analogue of, allow the application to force a previously enqueued command to wait for the user event to be signalled before execution can begin. User events are also the only type of event that can synchronize across contexts, requiring a separate special case code path to implement. Lastly, there is no analogue to `clSetUserEventStatus` which actually enables the application to change a user events status, making this feature incomplete.
Until such a time as they are deemed absolutely necessary, with no viable alternative proposed, this patch removes support for user events.
Fixes #15.
=> ur: Remove user event creation

include/ur_api.h, scripts/core/platform.yml, source/ur_api.cpp
Fix a typo in the `urPlatformGet` documentation wihch references `urPlatform` rather than `urPlatformGet`.
=> ur: Fix undefined Doxygen reference to urPlatform

CMakeLists.txt, examples/CMakeLists.txt, examples/hello_world/CMakeLists.txt, source/CMakeLists.txt, source/common/CMakeLists.txt, source/drivers/CMakeLists.txt, source/drivers/null/CMakeLists.txt, source/loader/CMakeLists.txt, source/loader/linux/platform_discovery_lin.cpp, third_party/CMakeLists.txt
When unified-runtime is built as part of another CMakeProject (through add_subdirectory) the paths will not be correct. It's better to use relative paths.
CMAKE_SOURCE_DIR would point to the top level of the other project directory, not unified-runtime top level dir.
=> Fix include directories for loader

CMakeLists.txt
This patch fixes a couple of issues, first being this error:
```
$ ninja -C build
ninja: Entering directory `build'
ninja: error: '../scripts/*', needed by 'unified_runtime.json', missing and no known rule to make it
```
The error is caused by the use of a `*` wildcard which are not well supported in CMake as they only perform globing at configure time, not during the build which is usually the desired effect. This is resolved by merging the `add_custom_command` into the `generate` custom target.
Second, the `generate` target's `ALL` flag has been removed. While it may seem appealing to regenerate the source code by default this actually causes issues with build targets that depend on that generated code. Given there are no dependencies for e.g. the `loader` on the `generate` target, …
=> cmake: Don't add generate to the all target

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/device.yml, scripts/core/queue.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
=> [ur] support queue indices

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/device.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Add `urDeviceGetGlobalTimestamps` as an analogue of [`clGetDeviceAndHostTimer`](https://registry.khronos.org/OpenCL/sdk/2.2/docs/man/html/clGetDeviceAndHostTimer.html) and aligns with the existing level zero function [`zerDeviceGetGlobalTimestamps`](https://spec.oneapi.io/level-zero/latest/core/api.html#zedevicegetglobaltimestamps)
Closes #88
=> [ur] Add urDeviceGetGlobalTimestamps

include/ur.py, include/ur_api.h, scripts/core/queue.yml
Adds Queue Properties to unified runtime to support [`sycl_ext_oneapi_discard_queue_events`](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_discard_queue_events.asciidoc) & 
[`sycl_ext_oneapi_queue_priority`](sycl_ext_oneapi_queue_priority).
Closes #112
=> [ur] Add missing Queue Properties

.github/workflows/cmake.yml, CMakeLists.txt, include/ur.py, scripts/templates/api.py.mako, source/common/ur_util.h, source/loader/CMakeLists.txt, source/loader/windows/platform_discovery_win.cpp, test/python/CMakeLists.txt, test/python/basic.py
This is related to the task no. 1 from the issue #128.
This PR allows us to run the hello_world example with the null adapter library on Windows. Additionally, this PR makes it possible that some more adapters could be loaded in the future (with an env var) on Windows.
=> Search for known adapter library in the current working directory on Windows

source/loader/linux/platform_discovery_lin.cpp, source/loader/windows/platform_discovery_win.cpp
Rename it so the new name describes better what is it for and doesn't
mention 'drivers' as it's taken from level-zero loader.
=> Rename UR_ENABLE_ALT_DRIVERS env var

CMakeLists.txt, include/ur.py, scripts/templates/api.py.mako, source/common/ur_util.h, test/python/CMakeLists.txt
Removes extra env var UR_ADAPTERS_SEARCH_DIR and bumps the minimum required cmake version to 3.22.
=> Use PATH env var to pass .dll location to tests

include/ur_api.h, scripts/core/kernel.yml, source/loader/ur_libapi.cpp, source/ur_api.cpp
We have decided that unlike OpenCL the SetArg APIs in UR should be thread-safe. This was mostly completed before, but I've added an additional statement to make this clear.
Closes #14
=> [ur] Clearly specify that SetArg is thread safe

include/ur_api.h, scripts/core/kernel.yml, source/loader/ur_libapi.cpp, source/ur_api.cpp
Result enumerations for errors all begin with `$X_RESULT_ERROR_*`, this fixes remaining unresolved references due to this.
Closes #150
=> [ur] Fix ur_result_t references

include/ur_api.h, scripts/core/enqueue.yml, scripts/core/event.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
* `urEnqueue*` entry-points have an optional return event.
*  `urEventGetInfo` is fixed to allow optional return size and value
Closes #33
=> [ur] Mark non-required arguments as optional

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/enqueue.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
urEnqueueMemBufferCopy now has additional offset parameters to match the OpenCL analogue function `clEnqueueCopyBuffer`
Closes #8
=> [ur] urEnqueueMemBufferCopy is analagous to OpenCL

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/enqueue.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Introduces:
* `urEnqueueDeviceGlobalVariableWrite`
* `UrEnqueueDeviceGlobalVariableRead`
To match requirements from [intel/llvm/7797](https://github.com/intel/llvm/pull/7797)
Closes #150
=> [ur] Add entrypoints to support device globals

include/ur_api.h, scripts/core/device.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
We should make device and host timer parameters optional in `urDeviceGetGlobalTimestamps` to allow it to be used as an analogue of both `clGetDeviceAndHostTimer` and `clGetHostTimer`.
See more detailed comment in #88
=> [ur] Make host/device time parameters optional

.github/workflows/docs.yml
Currently gh-pages is broken for API documentation because doxygen was not installed as part of the build.
Current main: https://oneapi-src.github.io/unified-runtime/core/api.html#ur-result-t
My fix: https://veselypeta.github.io/unified-runtime/core/api.html#ur-result-t
=> [ur] Install Doxygen in GH pages workflow

.github/workflows/cmake.yml, .github/workflows/docs.yml
Apt index might be stale, which can sometimes break the build.
=> fix doxygen install on ubuntu

.github/workflows/cmake.yml, test/conformance/device/urDeviceGetGlobalTimestamps.cpp, test/conformance/device/urDeviceGetNativeHandle.cpp, test/conformance/device/urDeviceRelease.cpp, test/conformance/device/urDeviceRetain.cpp, test/conformance/device/urDeviceSelectBinary.cpp, test/conformance/platform/urInit.cpp, test/conformance/platform/urTearDown.cpp
We have decided that there is no purpose in running the conformance tests against the null adapter since it will never be a conformant implementation.
This MR:
* Removes the job to run tests against the null adapter
* Re-enables disabled tests
=> [ur] Disable testing against null adapter

include/ur.py, include/ur_api.h, scripts/core/enqueue.yml, scripts/core/event.yml
This MR adds the following missing required enumerations to the ur spec to match PI.
* `ur_command_t` which matches PI's [`pi_command_t`](https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/detail/pi.h#L443)
* `ur_event_status_t` which matches PI's [`pi_event_status_t`](https://github.com/intel/llvm/blob/8c244de9e34140651bdfc2e6ffb4c221a4de1f23/sycl/include/sycl/detail/pi.h#L148)
=> [ur] Add missing command type & exec status enums

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/PROG.rst, scripts/core/device.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/device/urDevicePartition.cpp, test/conformance/testing/uur/fixtures.h
Open to suggestions on this one. 
On the WG call we decided that we should just revert how we specify device properties to be just an `intptr_t` - so i've created a typedef for `ur_device_partition_property_t` to `intptr_t`. However I have added an additional enum to specify the partitioning options `ur_device_partition_t` - which maybe isn't ideal. We could specify the values with macros but I'm not sure what I prefer.
Closes #183 & #119
=> [ur] Clarify device partition properties

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/enqueue.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Renames `urEnqueueUSMMemAdvice` to `urEnqeueuUSMMemAdvise`
Closes #187
=> [ur] Correct name for urEnqueueUSMMemAdvise

.clang-format, CMakeLists.txt, README.md, cmake/helpers.cmake, examples/hello_world/hello_world.cpp, source/loader/ur_loader.h, source/loader/ur_object.h, test/conformance/testing/CMakeLists.txt
This PR adds code formatting using clang-format.
The .clang-format file was automatically generated and is based on the LLVM style so reviews about what to change/add are very welcome.
Clang-tidy will be added in the next PR for braces around single line statements since there's no such option in clang-format-10.
The rest of the cpp/header files will be formatted in another PR as well since they'd add too much clutter to this one. The hello_world.cpp file is left as a reference to how it looks after formatting.
Addresses #101
=> Add automatic code formatting

examples/hello_world/hello_world.cpp, include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/runtime.yml, scripts/templates/libapi.cpp.mako, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_lib.cpp, source/loader/ur_lib.h, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/platform/fixtures.h, test/conformance/platform/urInit.cpp, test/conformance/platform/urTearDown.cpp, test/conformance/source/environment.cpp
`ur_platform_init_flags` are now removed. Originally (I believe - we have little documentation of the ur spec before we got it) this was a flag to select the desired backend. However, this is now handled with the loader and the backend is selected through an environment variable. Moreover, the loader actually does nothing with these parameters [here](https://github.com/oneapi-src/unified-runtime/blob/main/source/loader/ur_lib.cpp#L25). This then also raises the question if we need `ur_device_init_flags_t`....
Closes #21
=> [ur] remove platform init flags for urInit

include/ur_api.h, scripts/core/memory.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
`hostPtr` argument in urMemBufferCreate is not required for all uses of this entry-point and is only required when specific flags are set such as `UR_MEM_FLAGS_USE_HOST_POINTER`.
This also clarifies the spec that `UR_RESULT_ERROR_INVALID_HOST_PTR` should be returned instead of `UR_RESULT_ERROR_INVALID_NULL_POINTER`
=> [ur] HostPtr should be optional in urMemBufferCreate

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/queue.yml, scripts/core/sampler.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
PR #189 fixed how we specify properties for entry-points and we moved away from using the prop-value struct so it makes sense to make this consistent with the other 2 remaining entry-points that used this style `urQueueCreate` and `urSamplerCreate`
=> [ur] Remove prop-value structs

.github/workflows/cmake.yml, CMakeLists.txt, README.md, examples/hello_world/hello_world.cpp, source/loader/ur_loader.cpp, source/loader/windows/platform_discovery_win.cpp, test/unified_memory_allocation/common/pool.c, test/unified_memory_allocation/common/provider.c
For now, the developer mode only turns warnings into errors, but over time it will also encompass other various checks that we don't want to happen in
normal builds.
I also did a small cleanup of the main cmake.
The UR_ENABLE_TESTS option is now BUILD_TESTS.
=> enable all warnings and add developer mode

include/ur.py, include/ur_api.h, scripts/core/device.yml
- Add missing `ATOMIC_MEMORY_SCOPE_CAPABILITIES` device query - this is needed for parity with PI to implement the matching SYCL device information descriptor
- Add `ur_memory_order_capability_flags` and `ur_memory_scopes_capability_flags` bit-fields so the results of these queries are well defined
Fixes #109 and #110
=> Add missing enums for atomic memory capability device queries

source/common/unified_memory_allocation/include/uma/memory_pool.h
for pool. This function can also be used if an allocation function returns NULL.
=> [uma] Extend umaPoolGetLastResult description

test/conformance/event/fixtures.h, test/conformance/event/urEventRelease.cpp, test/conformance/event/urEventRetain.cpp, test/conformance/event/urEventWait.cpp
Add urEventRetain and urEventRelease tests 
Update urEventWait tests to avoid allocating buffer when running negative tests
Addresses issue https://github.com/oneapi-src/unified-runtime/issues/215
=> Add urEventRetain and urEventRelease tests

include/ur_api.h, scripts/core/context.yml, scripts/parse_specs.py, scripts/templates/helper.py, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
For entry points `urContextSetExtendedDeleter` and `urEventSetCallback` they accept a function pointer. We should clarify that the spec expects these values to not be null and if so return the appropriate error code.
Additionally the userdata parameter should be optional in `urContextSetExtendedDeleter` - this was already the case is `urEventSetCallback`.
=> [ur] Add return code for nullptr function pointers

include/ur.py, include/ur_api.h, scripts/core/common.yml, scripts/core/device.yml, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
This PR clarifies some device entry-points and what error codes they should return.
* I added `UR_RESULT_ERROR_INVALID_DEVICE_PARTITION_COUNT` to be returned from `urDeviceParition` when by-counts paritioning is used and invalid counts are provided. (to match OpenCL)
* I added `UR_RESULT_ERROR_DEVICE_PARTITION_FAILED` to be returned from `urDeviceParition` when the paritioning scheme is supported but the device could not be futher paritioned. (to march OpenCL)
* Adds `UR_RESULT_ERROR_INVALID_VALUE` error code to `urDeviceGetInfo` & `urDeviceSelectBinary`
=> [ur] Clarify some device return codes

test/unified_memory_allocation/common/pool.c, test/unified_memory_allocation/common/pool.h, test/unified_memory_allocation/common/provider.c, test/unified_memory_allocation/common/provider.h
showed up on clang after enabling -Wpedantic
=> [uma] fix empty prototypes in uma c tests

cmake/helpers.cmake, include/ur_api.h, include/ur_ddi.h, scripts/core/context.yml, source/drivers/null/ur_nullddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Add `const` to the `phDevices` argument of `urContextCreate` to match up
with PI/OpenCL and avoid unnecessary potential for `const_cast` in
adapter implementations.
Fixes #273
=> Make array of devices passed to urContextCreate const

scripts/templates/ldrddi.cpp.mako, scripts/templates/nullddi.cpp.mako, source/drivers/null/ur_nullddi.cpp, source/loader/ur_ldrddi.cpp
The `-Wpedantic` option was added to the UR build - when building I get the following error.
```
[build] ../source/drivers/null/ur_nullddi.cpp:3404:2: error: extra ‘;’ [-Werror=pedantic]
[build]  3404 | };
```
This additional semicolon is unnecessary for `extern "C" {}` construct so I have removed it.
=> [ur] Remove semicolon from extern C

test/conformance/event/urEventCreateWithNativeHandle.cpp
Since we don't have a `native_handle` the only valid test we can write is for when we have a `nullptr` native handle. This PR adds the same test to `event`. `device`, `context`, `memory`, `queue` were completed previously. 
This Closes #222 & #224
=> [ur] Complete Native Handle Tests

include/ur_api.h, scripts/templates/helper.py
Enums generated in C or C++ files include an `<ENUM>_FORCE_UINT32`
enumeration to force the compiler to use the equivalent of `uint32_t`
for the underlying type. Unfortunately, this also made its way into the
Doxygen and therefore the generated HTML specification. This patch
unconditionally excludes the `<ENUM>_FORCE_UINT32` enumeration from the
Doxygen and thus also from the HTML specification.
=> Exclude `<ENUM>_FORCE_UINT32` from Doxygen

CMakeLists.txt, include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/Doxyfile, scripts/YaML.md, scripts/core/PROG.rst, scripts/core/common.yml, scripts/core/program.yml, source/drivers/null/ur_nullddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
The new `ur_program_properties_t` struct allows the provision of
additional metadata to be passed into the
`urProgramCreate`/`urProgramCreateWithBinary` entry points.
Additionally, it supports `stype` and `pNext` which enable extending
program creation without breaking ABI.
Fixes #95
=> Add ur_program_properties_t for program creation

CMakeLists.txt, README.md
This is consistent with intel/llvm: https://github.com/intel/llvm/blob/6761f0ef372a0e54b970d85241808339e9bcf077/llvm/docs/CMake.rst#L279
=> Set required C++ standard to 17

include/ur_api.h, scripts/templates/api.h.mako, test/conformance/context/urContextSetExtendedDeleter.cpp
UR spec defined 'fptr' as function types instead of actual pointers.
This is fine for function parameters but made it difficult to populate
params structs (e.g., `params.pfnNotify = &notify` didn't work).
> A function designator is an expression that has function type. Except when it is the
> operand of the *sizeof operator* or the unary *&* operator, a function designator with
> type "function returning type" is converted to an expression that has type "pointer to
> function returning type".
> C11 6.3.2.1-4
=> [ur] use explicit function pointers

include/ur.py, include/ur_api.h, scripts/core/common.yml, scripts/core/enqueue.yml, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/enqueue/helpers.h, test/conformance/enqueue/urEnqueueMemBufferCopyRect.cpp, test/conformance/enqueue/urEnqueueMemBufferReadRect.cpp, test/conformance/enqueue/urEnqueueMemBufferWriteRect.cpp, test/conformance/enqueue/urEnqueueUSMMemcpy.cpp, test/conformance/enqueue/urEnqueueUSMMemset2D.cpp
* Add tests for urEnqueueUSMMemset2D
* Update urEnqueueUSMMemset2D specification with to return UR_RESULT_ERROR_INVALID_SIZE
=> Add tests for urEnqueueUSMMemset2D

.clang-format, include/ur.py, include/ur_api.h, scripts/core/context.yml, scripts/core/device.yml, scripts/core/event.yml, scripts/core/kernel.yml, scripts/core/program.yml, scripts/core/queue.yml, scripts/core/sampler.yml, test/conformance/context/urContextRelease.cpp, test/conformance/context/urContextRetain.cpp, test/conformance/device/urDeviceRelease.cpp, test/conformance/device/urDeviceRetain.cpp, test/conformance/event/fixtures.h, test/conformance/event/urEventRelease.cpp, test/conformance/event/urEventRetain.cpp, test/conformance/queue/urQueueRelease.cpp, test/conformance/queue/urQueueRetain.cpp, test/conformance/testing/uur/utils.h
`urRetain*` and `urRelease*` entry-points should increase and decrease the reference count of an object respectivelly. We have getInfo queries that can query the reference count from each object. These queries have the caveat that their value cannot be used reliably, especially in a multithreaded context. However, they are useful in a testing scenario where we disallow multithreading and assert that the reference count has changed after a release/retain call. 
This PR:
* Extends object lifetime testing and asserts that the reference count has changed after each release/retain call
* Clarifies the spec that `REFERENCE_COUNT` queries cannot be used reliably in an application context, especially a multithreaded one.
Closes #248
=> [ur] CTS release/retain tests increment reference counts

test/conformance/enqueue/urEnqueueUSMMemcpy2D.cpp
#305 Was not rebased when merging and wasn't up-to-date with the changes from #307 which changed the signature of `urUSMDeviceAlloc`.
This will fix the build.
=> [UR] Fix urUSMDeviceAlloc calls

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/PROG.rst, scripts/core/common.yml, scripts/core/context.yml, scripts/parse_specs.py, source/drivers/null/ur_nullddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/context/urContextCreate.cpp, test/conformance/context/urContextSetExtendedDeleter.cpp, test/conformance/testing/uur/fixtures.h
Introduce the `ur_context_properties_t` struct to enable extending the
creation of context beyond the defaults. As there are currently no
context properties, the `ur_context_flags_t` in also introduced as a
placeholder which creation flags can be added to in future.
Fixes #97
=> Add ur_context_properties_t for context creation

include/ur.py, include/ur_api.h, scripts/core/device.yml
Fixes #316 by adding `UR_DEVICE_LOCAL_MEM_TYPE_NONE` to the
`ur_device_local_mem_type_t` enum, this brings UR in line with the SYCL
and OpenCL specifications for the describing the local memory support a
device is capable of.
=> Add UR_DEVICE_LOCAL_MEM_TYPE_NONE

test/conformance/enqueue/urEnqueueUSMMemAdvise.cpp, test/conformance/enqueue/urEnqueueUSMPrefetch.cpp, test/conformance/testing/uur/fixtures.h
=> Add test for urEnqueueUSMPrefetch

.github/workflows/cmake.yml, CMakeLists.txt, README.md, cmake/helpers.cmake, cmake/match.cmake, examples/CMakeLists.txt, examples/collector/CMakeLists.txt, examples/collector/README.md, examples/collector/collector.cpp, scripts/core/INTRO.rst, scripts/generate_code.py, scripts/json2src.py, scripts/templates/trcddi.cpp.mako, source/loader/CMakeLists.txt, source/loader/layers/tracing/ur_tracing_layer.cpp, source/loader/layers/tracing/ur_tracing_layer.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/ur_lib.cpp, test/layers/CMakeLists.txt, test/layers/tracing/CMakeLists.txt, test/layers/tracing/hello_world.out.match
... and an example demonstrating its use.
This patch adds a tracing layer to the loader that transparently enables users to trace and hook into any UR call. This is done directly by leveraging SYCL's XPTI instrumentation framework.
For now, this is disabled by default and only runs in CI.
Closes #143
=> add initial tracing layer integrated with xpti

source/common/unified_memory_allocation/src/memory_pool.c, source/common/unified_memory_allocation/src/memory_provider.c
I've added simple tests for initialization in: https://github.com/oneapi-src/unified-runtime/pull/322 but we might want to someday enable valgrind for those.
=> [uma] fix leaks in create methods

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/device.yml, scripts/core/kernel.yml, scripts/core/program.yml, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
The issue #269, and the PR intel/llvm#7946, outline a desire to enable adapters to opt-in to setting specialization constants on a kernel object rather than a program object. On these adapters it is not required to perform compilation or linking when setting specialization constants and as such they can be set immediately prior to `urEnqueueKernelLaunch` with very low overhead.
This patch:
* Adds the `UR_DEVICE_INFO_KERNEL_SET_SPECIALIZATION_CONSTANTS` device query to determine if `urKernelSetSpecializationConstants` is supported by the device.
* Adds `ur_specialization_constant_info_t` to represent the data required to set an individual specialization constant
* Adds `urKernelSetSpecializationConstants` entry point, which adapters can opt-in to supporting, which enables setting multiple …
=> ur: Introduce urKernelSetSpecializationConstants

include/ur_api.h, scripts/core/enqueue.yml, source/drivers/null/ur_nullddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Change inputRowPitch and inputSlicePitch be rowPitch and slicePitch as in other APIs.
=> Make names in urEnqueueMemImageWrite align with other APIs

test/conformance/CMakeLists.txt, test/conformance/source/environment.cpp, test/conformance/source/main.cpp, test/conformance/testing/uur/environment.h
Add  `KernelsEnvironment` which will load the appropriate kernel IR supported by the tested device and cache it to be used by the tests.
The main entry-point to load the kernel that is needed for the test is `LoadSource` function.
=> Add support for testing different devices

CMakeLists.txt, include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/generate_docs.py, scripts/run.py, scripts/templates/api_listing.mako, scripts/templates/conf.py.mako, scripts/templates/index.rst.mako, source/ur_api.cpp
Change version in preparation for oneAPI HW SIG to differentiate the current state of the specification from previous meetings.
=> ur: Update spec to v0.6

source/common/logger/ur_logger.hpp, source/common/logger/ur_sinks.hpp, source/drivers/null/ur_null.cpp, source/loader/ur_lib.cpp, test/unit/logger/logger.cpp
Replace extern logger object with a singleton one. Remove the need for initializing logger when logger is not used.
Add printing logger name at the beginning of messages.
=> [ur] Replace extern logger object with a singleton

.github/workflows/docs.yml, CMakeLists.txt, scripts/run.py
Following on from !331 this patch fixes an issue where running
`scripts/run.py` without the `--ver` argument would result in the wrong
version number being generated in the spec HTML. The default value for
the `--ver` argument is now read from the `project()` command in root
`CMakeLists.txt` file, making it the single source of truth for the
version.
=> Use root CMakeLists.txt as the default version

include/ur_api.h, scripts/core/enqueue.yml, scripts/generate_ids.py, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/enqueue/urEnqueueMemBufferCopy.cpp, test/conformance/enqueue/urEnqueueMemBufferFill.cpp, test/conformance/enqueue/urEnqueueMemBufferMap.cpp, test/conformance/enqueue/urEnqueueMemBufferRead.cpp, test/conformance/enqueue/urEnqueueMemBufferWrite.cpp
Define the conditions under which the `UR_RESULT_ERROR_INVALID_SIZE`
error code should be returned for the following entry points:
* `urEnqueueMemBufferRead`
* `urEnqueueMemBufferReadRect`
* `urEnqueueMemBufferWrite`
* `urEnqueueMemBufferWriteRect`
* `urEnqueueMemBufferCopy`
* `urEnqueueMemBufferCopyRect`
* `urEnqueueMemBufferFill`
* `urEnqueueMemBufferMap`
Fixes #19
=> ur: Add parameter valid usage for enqueue buffer commands

test/conformance/usm/CMakeLists.txt, test/conformance/usm/urUSMPoolCreate.cpp, test/conformance/usm/urUSMPoolDestroy.cpp
=> [CTS] Adds CTS tests for urUSMPoolCreate/Destroy

cmake/helpers.cmake
I encounter the problem when having local clang-format but it fails to run because of some missing library. Then in https://github.com/oneapi-src/unified-runtime/blob/main/CMakeLists.txt#L119 it calls https://github.com/oneapi-src/unified-runtime/blob/main/cmake/helpers.cmake#L9, which use the output of `clang-format --version`, which in my case is empty.
Then the empty output make `${cmd_ret}` empty, and without the quotes, it would be a missing argument to `STRING REGEX`(instead of a empty string with quotes).
=> [cmake] add quotes to cmd output, make it robust

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/memory.yml, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/memory/urMemBufferPartition.cpp
Enable extensibility of `urMemBufferCreate` and `urMemBufferPartition`
via `pNext` chained property structures. This also enables existing
functionality in PI relating to the `cl_intel_mem_channel_property` and
`cl_intel_mem_alloc_buffer_location` OpenCL extensions while also
enabling future extensions without ABI changes.
Fixes #98
=> [ur] Make creation of buffer objects extensible

include/ur.py, include/ur_api.h, scripts/core/memory.yml
Noticed there was no equivalent for `PI_IMAGE_CHANNEL_ORDER_ABGR` in UR so have added an ABGR option to the `ur_image_channel_order_t` enum list.
=> Add ABGR option to ur_image_channel_order_t enum list.

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/device.yml, scripts/core/program.yml, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/device/urDeviceSelectBinary.cpp
PI uses a `pi_device_binary` type which includes a bunch of additional metadata that is used by the program manager in SYCL. However the only place where this binary struct is used is with the `urDeviceSelectBinary` entry point. Every implemented plugin selects the correct device binary by comparing the correct `DeviceTargetSpec` within the plugin. The extra complexity inherited in PI from the program manager is unnecessary for UR and has been removed. I have left the option of extending this struct with the `ur_base_desc_t` class.
Closes #252 
Closes #118 
Closes #171 
Closes #114
=> [UR] `urDeviceSelectBinary` spec changes 

include/ur.py, include/ur_api.h, scripts/core/usm.yml
Right now, we have types that start with: `usm`, `usm_mem` and `mem`.
I think we should also rename `ur_mem_advice_t` to have `usm` prefix but I'm not sure if we want `ur_usm_mem_advice_t` or `ur_usm_advice_t`. `usm_mem` duplicates 'memory' but we already have USMMemAdvise functions.
=> [ur] Unify naming for usm related types.

include/ur.py, include/ur_api.h, scripts/core/usm.yml, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/testing/include/uur/checks.h, test/conformance/usm/urUSMGetMemAllocInfo.cpp
Closes: https://github.com/oneapi-src/unified-runtime/issues/326
=> [ur] extend ur_usm_alloc_info_t with pool info

include/ur.py, include/ur_api.h, scripts/core/usm.yml
The structure should be extended in future, accordingly to: https://github.com/oneapi-src/unified-runtime/issues/369
=> Remove non-generic paramers from ur_usm_pool_limits_desc_t

source/loader/ur_adapter_registry.hpp
The loader will segfault due to `altPlatforms` not having any values - this resulted in an empty string added to the list on known platforms which resulted in a segfault.
=> [UR] Prevent loader from segfaulting

test/conformance/event/fixtures.h, test/conformance/testing/include/uur/fixtures.h
The event testsuite has an entrypoint `urEventGetProfilingInfo` which requires a queue that has the `UR_QUEUE_FLAG_PROFILING_ENABLE` set when it's created.
Closes #377
=> [CTS] Fix event tests to use queue with profiling enabled

include/ur.py, include/ur_api.h, scripts/core/device.yml, test/conformance/testing/include/uur/utils.h, test/conformance/testing/source/utils.cpp
* Fixes #113 by introducing the `UR_DEVICE_FP_CAPABILITY_FLAG_SOFT_FLOAT`
enumeration to support `sycl::info::device::fp_config::soft_float`.
* Rename `ur_fp_capability_flag_t` to `ur_device_fp_capability_flag_t`
to be consistent with the other types describing device capabilities.
=> [ur] Add soft float device capability

include/ur_api.h, scripts/core/context.yml, scripts/core/device.yml, scripts/core/kernel.yml, scripts/core/memory.yml, scripts/core/program.yml, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
The names of properties-related (e.g., device info, context info, and similar) arguments in functions are all over the place. This makes it guesswork for developers to correctly use these APIs, but, maybe more importantly, it means it's impossible to programmatically find all property-related variables in mako templates.
=> [ur] normalize prop names

source/common/logger/ur_logger_details.hpp, source/common/logger/ur_sinks.hpp, test/unit/logger/fixtures.hpp, test/unit/logger/logger.cpp
Fix FileSink logger tests checks not running. These checks detected failures in setting up logger with the `setenv()` function. This was due to the fact that the global logger object is a static singleton, therefore it's configuration can be provided only once per test binary run. Replaced global logger in these tests with local logger objects. New tests for validation of logger configured with the env var are not part of this PR.
Cleaned up logger and logger tests code a bit.
=> [ur] Fix part of logger tests not running properly + cleanup

scripts/generate_code.py, scripts/json2src.py, scripts/templates/helper.py, scripts/templates/params.hpp.mako, source/common/ur_params.hpp, test/unit/CMakeLists.txt, test/unit/utils/CMakeLists.txt, test/unit/utils/params.cpp
UR defines `_params_t` structures for storing function arguments during tracing. Reading this struct programmatically is easy, but pretty printing it is not.
This patch implements stream insertion (<<) operators for param structs and all other ur types. This lets software easily (semi-)serialize function calls during tracing.
This doesn't support generic propreties (props, e.g., device info). The spec currently does not provide sufficient information to programmatically cast the `void *` prop pointers to the appropriate type specified by `*_info_t` enumerator value.
=> add human-readable (partial) serialization for ur types

include/ur.py, include/ur_api.h, scripts/core/usm.yml
Fixes `warning: explicit link request to '...' could not be resolved`.
=> [ur] fix docs references to usm advice flags

include/ur_api.h, scripts/parse_specs.py, scripts/templates/api.h.mako, scripts/templates/helper.py, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
The API generator has the ability to check that flags and enums are within range, however this does not apply to `[optional]` parameters. This then means that adapters will have to check if the value is within range. It would be great if we report this range as part of the API specification and avoid having the plugins compute what this value is - which could become outdated as additional enumerations are added/removed and is easily missed.
The adapter can then do the following:
```cpp
if(flags & UR_<ENUM>_MASK){
return UR_RESULT_ERROR_INVALID_ENUMERATION;
}
```
=> [UR] Generate a bit mask for `flags_t` parameter validation

.github/workflows/cmake.yml, CMakeLists.txt, README.md
when UR_FORMAT_CPP_STYLE is set. To make sure that CLANG_FORMAT_REQUIRED version is respected.
=> [ur] only add 'generate' and 'check-generated' targets

CMakeLists.txt, cmake/FindLibbacktrace.cmake, source/loader/CMakeLists.txt, source/loader/layers/validation/backtrace_libbacktrace.cpp, source/loader/layers/validation/ur_leak_check.hpp
Libbacktrace backtrace can be enabled using cmake option `VAL_USE_LIBBACKTRACE_BACKTRACE`, it is set to OFF by default.
Addresses: https://github.com/oneapi-src/unified-runtime/issues/368
Supersedes: https://github.com/oneapi-src/unified-runtime/pull/388
An example output from backtrace implementation using libbacktrace looks like this:
```
<VALIDATION>[ERROR]: #0 0x7fb0800bbf37 in (urContextRelease) (/home/kswiecic/dev/sycl_workspace/unified-runtime/source/loader/ur_libapi.cpp:745)
<VALIDATION>[ERROR]: #1 0x55d4bacd942f in (valDeviceTestMultithreaded_testUrContextReleaseLeakMt_Test::TestBody()::$_1::operator()() const) (/home/kswiecic/dev/sycl_workspace/unified-runtime/test/layers/validation/leaks_mt.cpp:40)
<VALIDATION>[ERROR]: #2 0x55d4bacd92ac in (void std::__invoke_impl<void, …
```
=> Add validation backtrace libbacktrace

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/queue.yml, source/common/ur_params.hpp, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/queue/urQueueCreate.cpp, test/conformance/queue/urQueueGetInfo.cpp, test/conformance/testing/include/uur/checks.h, test/conformance/testing/include/uur/fixtures.h
Move the optional queue creation properties into the
`ur_queue_properties_t` struct which enables extensibility via `pNext`
chains. Also make use of `pNext` chaining by moving the
`UR_QUEUE_PROPERTY_COMPUTE_INDEX` property, since it is used to enable
the sycl_ext_intel_queue_index extension, into the
`ur_queue_index_properties_t` struct.
=> [ur] Make queue creation extensible

include/ur.py, include/ur_api.h, scripts/core/platform.yml, source/common/ur_params.hpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
This allows users to select wanted adapter/platform.
=> Add platform info query to identify its backend adapter

CMakeLists.txt, source/common/logger/ur_sinks.hpp, test/conformance/source/environment.cpp
Fixes #439 by detecting if the `<filesystem>` header is available, if
not including `<experimental/filesystem>` instead making use of the
`__has_include` macro if available.
=> [ur] Use <experimental/filesystem> on older libstdc++

scripts/generate_ids.py
When trying to add a new entry-point the registry was allocating duplicate id's causing it to fail to compile. The reason is that when the existing values are read from the `registry.yml` file as strings and the `valid_ids` list contains `ints`. Therefore, no id's were being removed during this step.
* The fix converts strings to ints, which then correctly removes id's from the `valid_ids` list.
=> [UR] Fix registry id allocation

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/platform.yml, scripts/core/registry.yml, scripts/generate_ids.py, source/common/ur_params.hpp, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/platform/CMakeLists.txt, test/conformance/platform/urPlatformGetBackendOption.cpp
~~Hold-off merging this until intel/llvm#8763 is merged - in case there are additional changes.~~
Upstream PR has now been merged
Closes #427
=> [UR] Add backend option entrypoint

source/common/uma_helpers.hpp, source/common/unified_memory_allocation/CMakeLists.txt, source/common/unified_memory_allocation/include/uma/memory_pool.h, source/common/unified_memory_allocation/include/uma/memory_pool_ops.h, source/common/unified_memory_allocation/include/uma/memory_provider.h, source/common/unified_memory_allocation/src/memory_pool.c, source/common/unified_memory_allocation/src/memory_tracker.cpp, source/common/unified_memory_allocation/src/memory_tracker.h, test/unified_memory_allocation/common/pool.c, test/unified_memory_allocation/common/pool.hpp, test/unified_memory_allocation/common/provider.c, test/unified_memory_allocation/common/provider.hpp, test/unified_memory_allocation/memoryPool.hpp, test/unified_memory_allocation/memoryPoolAPI.cpp
This PR adds a `umaPoolByPtr` function. It's implemented on top of (internal) memoryTracker.
This PR also requires users to pass all memory providers to memory pool through `providers` array parameter in initialize method. This allows UMA to wrap each provider and register all allocations/deallocations.
=> [uma] memory tracking provider

scripts/templates/valddi.cpp.mako, source/loader/layers/validation/ur_valddi.cpp
This fixes a Coverity scan warning pointing to the fact that some parameters are dereferenced before being null-checked.
=> Sort validation layer param checks

include/ur_api.h, scripts/core/memory.yml, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Condition needs to check for pProperties not being null before dereferencing it.
=> Fix error in urMemBufferCreate validation layer

include/ur.py, include/ur_api.h, scripts/core/sampler.yml, source/common/ur_params.hpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Reorder the values of the `ur_sampler_addressing_mode_t` enum to match the values used in libclc. For the cuda adapter (and maybe others) this means we can use the enum values directly in the sampler properties field without having to remap them.
=> Reorder values in `ur_sampler_addressing_mode_t` enum

include/ur.py, include/ur_api.h, scripts/YaML.md, scripts/core/context.yml, scripts/core/device.yml, scripts/core/event.yml, scripts/core/kernel.yml, scripts/core/memory.yml, scripts/core/platform.yml, scripts/core/program.yml, scripts/core/queue.yml, scripts/core/sampler.yml, scripts/core/usm.yml, scripts/parse_specs.py, scripts/templates/helper.py, scripts/templates/params.hpp.mako, source/common/ur_params.hpp, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/event/urEventGetInfo.cpp, test/conformance/event/urEventGetProfilingInfo.cpp, test/conformance/usm/urUSMGetMemAllocInfo.cpp, test/unit/utils/params.cpp
[ur] introduce enum associated types and use it for props
Many UR functions use enum tags alongside opaque (typically void *)
pointers to construct an algebraic data type. This is useful because
it allows for creating function arguments that can be one of
several types of values. However, this approach, at least in C,
is not very typesafe. It's fairly easy to make a mistake that
can't be easily caught at compile time (and even at runtime).
To help with that a little bit, at least on the spec side of things,
this patch introduces optional 'typed_etor' and 'typename' qualifiers.
An enum with typed etor requires that all its values have specify
a type in their 'desc' field. The typename can be used to tag
opaque pointers with a tag field name.
Typed_etors are checked by codegen scripts, …
=> [ur][common] pretty printing for props

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/context.yml, source/common/ur_params.hpp, source/drivers/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/context/urContextCreateWithNativeHandle.cpp, test/conformance/context/urContextGetNativeHandle.cpp
Add needed members for PI:
NumDevices
Devices
OwnNativeHandle
=> Expand urContextGetNativeHandle

cmake/match.cmake, source/common/logger/ur_level.hpp, source/common/logger/ur_logger.hpp, source/common/logger/ur_sinks.hpp, source/common/ur_util.hpp, test/layers/tracing/CMakeLists.txt, test/tools/urtrace/CMakeLists.txt, test/unit/logger/CMakeLists.txt, test/unit/logger/env_var.cpp, test/unit/logger/fixtures.hpp, test/unit/logger/logger.cpp, test/unit/logger/logger_all_levels_msg_exact.out.match, test/unit/logger/logger_debug_msg.out.match, test/unit/logger/logger_debug_msg_exact.out.match, test/unit/logger/logger_error_msg.out.match, test/unit/logger/logger_error_msg_exact.out.match, test/unit/logger/logger_info_msg_exact.out.match, test/unit/logger/logger_no_debug_msg.out.match, test/unit/logger/logger_no_error_msg.out.match, test/unit/logger/logger_warning_msg_exact.out.match, test/unit/logger/no_logfile.cmake
Add tests for validation of the global logger object setup from
an environment variable. Improve logger env var handling.
=> [ur] Improve logger env var handling

include/ur_api.h, scripts/templates/api.h.mako
The original purpose of these callbacks was manual registration of explicit function callbacks in the tracing layer, similar to how it works with level-zero loader.
However, UR relies on the XPTI framework that allows software to transparently intercept all function calls, making the callbacks redundant.
=> [ur] remove unused function callbacks

source/common/unified_memory_allocation/include/uma/memory_pool.h, source/common/unified_memory_allocation/src/memory_pool.c, source/common/unified_memory_allocation/src/memory_provider.c, source/common/unified_memory_allocation/src/memory_provider_internal.h, source/common/unified_memory_allocation/src/memory_tracker.cpp, source/common/unified_memory_allocation/src/memory_tracker.h, test/unified_memory_allocation/common/pool.hpp, test/unified_memory_allocation/memoryPoolAPI.cpp
This functionality will be used in UR and possibly MPI to query memory properties (that are stored in a memory provider). To make it usable, I think we would also need to add the provider_type (that was initially part of the memory tracking PR) and limit the number of DATA memory providers to 1.
This functionality could also be helpful for lifetime management: the user no longer needs to keep track of memory provider handles to destroy them.
One thing I'm not sure about is whether we want to expose the original memory providers or the wrappers (tracking providers). Returning the original ones makes more sense to me - this way, we don't need to expose any other functions (like getUpstreamProvider).  Also, our memory tracking is done on per-pool basis, if we'd return a memory-tracking …
=> [uma] add function to retrieve providers

CMakeLists.txt
This patch replaces changes the logic used to specify linking against `libstdc++fs.a` required to use early iterations of `std::filesystem`. Previously CMake checked for the existence of the `<filesystem>` header to enable linking the static library, however in GCC 8 this header exists while still requiring manual linking against the static library. Now we check if we are compiling with `libstdc++` and always manually link against the static library. Fixes #451.
=> [ur] Fix linking against libstdc++fs

test/conformance/usm/urUSMPoolCreate.cpp, test/conformance/usm/urUSMPoolDestroy.cpp
The tests are parameterized so need the `TEST_P` macro.
=> [CTS] Fix urUSMPoolCreate/Destroy tests

include/ur.py, include/ur_api.h, scripts/core/usm.yml, source/common/ur_params.hpp
Fixes #423 by introducing the 6 missing `pi_mem_advice` to the `ur_usm_advice_flags_t`.
=> [ur] Add missing USM advise flags

source/common/uma_helpers.hpp, source/common/unified_memory_allocation/include/uma/base.h, source/common/unified_memory_allocation/include/uma/memory_provider.h, source/common/unified_memory_allocation/include/uma/memory_provider_ops.h, source/common/unified_memory_allocation/src/memory_provider.c, source/common/unified_memory_allocation/src/memory_tracker.cpp, test/unified_memory_allocation/common/provider.c, test/unified_memory_allocation/common/provider.hpp, test/unified_memory_allocation/memoryProviderAPI.cpp
for memory provider. They are similar to jemalloc 'purge' hooks. OS memory provider can implement those functions using madvise and MADV_FREE / MADV_DONTNEED.
I've also added a way to query (possible) page sizes for a given pointer so that we can require `ptr` and `size` parameters to `purge` to be page-aligned. I think it's better not to adjust those transparently within the provider. 
I'm not entirely sure how to handle this for transparent huge pages though. Right now the API allows returning an array of supported page sizes (sorted by size) from that function instead of a single value. This way an implementation can either just return an array of all possible page sizes for any given pointer or return a specific page size if it knows what it is. With this approach we can just return …
=> [uma] Add purge_[lazy|force] functions

include/ur.py, include/ur_api.h, scripts/core/device.yml, source/common/ur_params.hpp
Only use ur_bool_t in ur_device_info_t for consistency
=> Change bool to ur_bool_t in some places

test/conformance/memory/urMemBufferCreate.cpp, test/conformance/memory/urMemImageCreate.cpp
`UR_MEM_FLAG_ALLOC_HOST_POINTER` does not require a host ptr to be passed.
=> [UR] UR_MEM_FLAG_ALLOC_HOST_POINTER does not require a host ptr

include/ur.py, include/ur_api.h, scripts/core/usm.yml, source/common/ur_params.hpp, test/unit/utils/params.cpp
They were initially introduced for L0 compatibility but currently they are not used in SYCL/OpenMP.
=> [ur] remove ur_usm_flags_t

scripts/generate_code.py, scripts/json2src.py
Currently the generator for adapters is broken as the autogenerate driver is still placed in `source/drivers` instead of `source/adapters`. This PR fixes the path as well as renames functions from `driver` -> `adapter`.
=> [UR] Fix codegen to adapters directory

test/conformance/memory/urMemBufferCreate.cpp
We've chosen to disable a CTS test that attempts to allocate beyond the maximum allocation size since it's not generally applicable across adapters. The CUDA adapter cannot ahead of time determine it's maximum allowed allocation.
=> [UR][CTS] Disable CTS test to check max mem alloc size

source/common/unified_memory_allocation/include/uma/memory_pool.h, source/common/unified_memory_allocation/include/uma/memory_pool_ops.h, source/common/unified_memory_allocation/include/uma/memory_provider.h, source/common/unified_memory_allocation/include/uma/memory_provider_ops.h
Improve Unified Memory Allocator doxygen comments:
* sentences that start with a capital letter should end with a dot.
* add missing [out] parameters
* add missing return descriptions
=> [UMA] Improve the doxygen comments

CMakeLists.txt, source/common/CMakeLists.txt, source/loader/CMakeLists.txt
Target name can show up in a linker .map file.
Having appropirate prefixes makes it easier to
identify the component.
=> [ur] add ur prefix to target names

scripts/templates/libapi.cpp.mako, scripts/templates/nullddi.cpp.mako, source/adapters/null/ur_nullddi.cpp, source/common/ur_util.hpp, source/loader/ur_libapi.cpp
We don't catch all possible exceptions (especially std::bad_alloc when using std containers). This change adds checks to each API function and return appropriate status in case of any exception.
=> [ur] Handle exceptions in each API function

include/ur_api.h, scripts/core/platform.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/tools/urtrace/null_hello.match, test/tools/urtrace/null_hello_begin.match, test/tools/urtrace/null_hello_profiling.match
Fixup an `hDriver` parameter name in the `urPlatformGetApiVersion` entry
point which should be `hPlatform` since UR does not include the concept
of a driver object.
=> [ur] Replace hDriver param name with hPlatform

include/ur.py, include/ur_api.h, scripts/core/queue.yml, source/common/ur_params.hpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/queue/urQueueGetInfo.cpp
This is needed for compatibility with PI (`PI_EXT_ONEAPI_QUEUE_INFO_EMPTY`)
=> [UR] Add UR_QUEUE_INFO_EMPTY query

source/common/unified_memory_allocation/src/memory_tracker.cpp
glibc 2.37, gcc (GCC) 13.1.1 20230429
=> fix use of undeclared identifier 'malloc'/'free'

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/platform.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Introduces the `ur_platform_native_properties_t` struct which may be
passed into `urPlatformCreateWithNativeHandle`. This enables
extensibility of platform creation from native handles.
Relates to #392.
=> [ur] Make urPlatformCreateWithNativeHandle extensible

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/device.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/device/urDeviceCreateWithNativeHandle.cpp, test/conformance/device/urDeviceGetNativeHandle.cpp
Introduces the `ur_device_native_properties_t` struct which may be
passed into `urDeviceCreateWithNativeHandle`. This enables extensibility
of platform creation from native handles.
Relates to #392.
=> [ur] Make urDeviceCreateWithNativeHandle extensible

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/program.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Introduces the `ur_program_native_properties_t` struct which may be
passed into `urProgramCreateWithNativeHandle`. This enables
extensibility of platform creation from native handles.
Relates to #392.
=> [ur] Make urProgramCreateWithNativeHandle extensible

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/sampler.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Introduces the `ur_sampler_native_properties_t` struct which may be
passed into `urSamplerCreateWithNativeHandle`. This enables
extensibility of platform creation from native handles.
Relates to #392.
=> [ur] Make urSamplerCreateWithNativeHandle extensible

.github/workflows/codeql.yml
Add CodeQL scans to make it possible to catch issues during the PR refinement as opposed to Coverity scans, which can run on the main branch only.
A sample execution of this workflow: https://github.com/PatKamin/unified-runtime/actions/runs/5011460219/jobs/8982314529
=> [ci] Add CodeQL scans

source/common/logger/ur_logger.hpp, source/common/logger/ur_sinks.hpp
- use std::move() on strings in Logger where appropriate.
=> [coverity] Fix Coverity minor performance issues

source/common/ur_util.hpp, test/tools/urtrace/CMakeLists.txt, test/tools/urtrace/null_hello_json.match, tools/urtrace/README.md, tools/urtrace/collector.cpp, tools/urtrace/urtrace
This is to match a similar functionality in `sycl-prof` that's based on PI.
=> [urtrace] add json output support

.github/workflows/cmake.yml
Partially address #457 by adding Ubuntu 20.04 and Windows Server 2019 to
the testing matrix. These are the low hanging fruit, beyond these
additions we'll need to use container images.
=> [ci] Extend OS testing matrix

include/ur.py, include/ur_api.h, scripts/core/device.yml, source/common/ur_params.hpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/device/urDeviceGetInfo.cpp, test/conformance/device/urDeviceGetNativeHandle.cpp, test/conformance/device/urDevicePartition.cpp, test/conformance/device/urDeviceRelease.cpp, test/conformance/device/urDeviceRetain.cpp
- Update spec to show that MAX_WORK_GROUPS_3D returns an array of 3 elements
- Make it clear the urDeviceGetInfo can return UR_RESULT_ERROR_INVALID_ENUMERATION if the adapter does not support the query.
- Fix bug in urDevicePartition test
- Update urDeviceRelease and urDeviceRetain tests to take into account the differences betwen root devices and subdevices.
- Update the specification to make clear that the behaviour of urDeviceRelease and urDeviceRetain changes depending on the type of device.
=> [UR][CTS] Fix device tests

test/conformance/enqueue/urEnqueueUSMFill.cpp, test/conformance/enqueue/urEnqueueUSMFill2D.cpp, test/conformance/enqueue/urEnqueueUSMMemcpy.cpp, test/conformance/enqueue/urEnqueueUSMMemcpy2D.cpp, test/conformance/testing/include/uur/fixtures.h, test/conformance/testing/include/uur/utils.h, test/conformance/testing/source/utils.cpp, test/conformance/usm/urUSMDeviceAlloc.cpp, test/conformance/usm/urUSMFree.cpp, test/conformance/usm/urUSMHostAlloc.cpp, test/conformance/usm/urUSMSharedAlloc.cpp
https://github.com/oneapi-src/unified-runtime/pull/464 Changes memory access caps from bool to
ur_device_usm_access_capability_flags_t. CTS was still
using bool in several places which caused tests to fail
=> Fix how CTS gets memory access properties

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/queue.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/queue/urQueueGetNativeHandle.cpp
Add adapter-specific data in new ur_queue_native_desc_t
A high-level queue, like sycl::queue, could be translated into
different types of adapter streams. For instance, a sycl::queue
could be translated into an L0 command queue or an L0 command list.
So define a new descriptor for urQueueCreateWithNativeHandle and
urQueueGetNativehandle with an opaque pointer, which can be used to
pass adapter-specific data.
Resolves: https://github.com/oneapi-src/unified-runtime/issues/533
=> Add adapter-specific data in new ur_queue_native_desc_t

CMakeLists.txt, test/tools/urtrace/CMakeLists.txt, tools/urtrace/urtrace
- add Debug build type builds to a workflow
- use multiple threads to build, as $(nproc) would have no effect on
Windows, setting the number of cores to 2 as this is the current max
for Github Actions jobs
- hide message about libbacktrace not found on Windows builds.
- change the flush level of tracing messages in tracing tests to have certainty
for the order of messages
=> [ci] Add CI Debug builds

include/ur_api.h, scripts/core/sampler.yml, source/adapters/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/CMakeLists.txt, test/conformance/sampler/CMakeLists.txt, test/conformance/sampler/urSamplerCreate.cpp, test/conformance/sampler/urSamplerCreateWithNativeHandle.cpp, test/conformance/sampler/urSamplerGetInfo.cpp, test/conformance/sampler/urSamplerGetNativeHandle.cpp, test/conformance/sampler/urSamplerRelease.cpp, test/conformance/sampler/urSamplerRetain.cpp, test/conformance/testing/include/uur/fixtures.h
This MR:
* Makes `pPropSizeRet` & `pPropValue` optional parameters in `urSamplerGetInfo`
* Adds basic CTS tests for the sampler set of entry points
=> [UR] clarify sampler spec and add CTS

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/PROG.rst, scripts/core/common.yml, scripts/core/device.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/common/ur_pool_manager.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/device/urDeviceGetInfo.cpp, test/conformance/device/urDevicePartition.cpp, test/conformance/device/urDeviceRelease.cpp, test/conformance/device/urDeviceRetain.cpp, test/conformance/testing/include/uur/fixtures.h, test/conformance/testing/include/uur/utils.h, test/conformance/testing/source/utils.cpp, test/unit/utils/params.cpp
Discussion on the approach can be seen in #401
=> [UR] Refactor urDevicePartition to use desc struct

include/ur_api.h, scripts/core/kernel.yml, source/adapters/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/kernel/urKernelSetArgMemObj.cpp
This reverts #494
We need to support null argument values again because https://github.com/intel/llvm/pull/9634 implicitly allows them in PI
=> [ur] Make hArgValue optional again in urKernelSetMemObj

scripts/parse_specs.py, scripts/run.py
This PR:
* Re-throws exception from `__validate_params()` instead of swallowing the error
* Adds try/catch around spec generation to detect when failure occurs - return non-zero error to fail build
Closes #565
=> [UR] Fail build on spec generate

scripts/core/CONTRIB.rst
=> [UR] Documents generator and conformance tests

scripts/util.py
Re-raise the exception from writing mako templates. This will be caught by main() and fail the build
=> [UR] re-raise exception in makoWrite

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/common.yml, scripts/core/device.yml, scripts/core/event.yml, scripts/core/exp-command-buffer.yml, scripts/core/registry.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_ldrddi.hpp, source/loader/ur_libapi.cpp, source/loader/ur_libddi.cpp, source/ur_api.cpp
- Adds support for command-buffers experimental feature
- Add command-buffer desc type to common.yml
- Add device info query for command-buffer support
Porting the PI command-buffer extension added in https://github.com/intel/llvm/pull/9375 which is currently under review. The functions implemented do not cover all possible command types, only those that have actually been implemented in the linked PR.
Notes:
- As there's no way to extend existing enums from the command-buffer YAML file I've modified those directly where necessary.
=> [Experimental] Add command-buffers

source/common/unified_memory_allocation/include/uma/memory_provider.h
to support cases where ptr is NULL.
This is useful for adjusting allocation size based on alignment requirements.
=> [uma] extend umaMemoryProviderGetMinPageSize spec

source/common/uma_helpers.hpp, source/common/unified_memory_allocation/include/uma/memory_provider.h, source/common/unified_memory_allocation/include/uma/memory_provider_ops.h, source/common/unified_memory_allocation/src/memory_provider.c, source/common/unified_memory_allocation/src/memory_tracker.cpp, test/unified_memory_allocation/common/provider.c, test/unified_memory_allocation/common/provider.h, test/unified_memory_allocation/common/provider.hpp, test/unified_memory_allocation/memoryProviderAPI.cpp
To allow interacting with the underlying implementation directly. This will be needed to support returning native error codes (name can be used to figure out how to interpret those errors) and possibly to support provider-specific queries.
=> [uma] add a function to query name of a provider

scripts/parse_specs.py, scripts/templates/helper.py
A pointer to handle argument requires that a `[range(start, end)]` check is included as part of it's description. This is required for the loader to do some local conversion of it's types. This also leads to some confusion as without this check the script generator will match a different part of the description resulting in other parts of the description being included into the generated files.
=> [UR] Pointer to handle arguments require a range() check

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/EXP-BINDLESS-IMAGES.rst, scripts/core/common.yml, scripts/core/device.yml, scripts/core/event.yml, scripts/core/exp-bindless-images.yml, scripts/core/registry.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_ldrddi.hpp, source/loader/ur_libapi.cpp, source/loader/ur_libddi.cpp, source/ur_api.cpp
Experimental support for bindless images in Unified Runtime.
This feature is to add support for the [experimental implementation of bindless images extension #9665](https://github.com/intel/llvm/pull/9665) in DPC++ after [Port CUDA plugin to Unified Runtime #9512](https://github.com/intel/llvm/pull/9512) is merged.
=> [Exp][Bindless Images] Experimental Bindless Images

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/platform.yml, scripts/core/registry.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Remove the `urGetLastResult()` entry-point and replace it with
`urPlatformGetLastError()`. This primary difference is the addition of
the `pError` out parameter which returns an error code emitted from a
failed driver entry-point which resulted in a Unified Runtime
entry-point returning `UR_RESULT_ERROR_ADAPTER_SPECIFIC`.
Fixes #500.
=> [ur] Improve reporting of adapter specific errors

.github/workflows/cmake.yml, CMakeLists.txt, source/common/uma_pools/CMakeLists.txt, test/unified_memory_allocation/memoryPool.hpp
... and add gcc-7 build to avoid breaking it
in the future.
=> [usm allocator] add linking with pthreads

include/ur.py, include/ur_api.h, scripts/core/virtual_memory.yml, source/common/ur_params.hpp
Address [feedback](https://github.com/oneapi-src/unified-runtime/pull/525#discussion_r1234803903) and add `UR_VIRTUAL_MEM_ACCESS_FLAG_NONE` to allow specifying a no access.
=> [ur] Add NONE to virtual mem access flags

include/ur_api.h, scripts/parse_specs.py, source/loader/ur_libapi.cpp, source/ur_api.cpp
This PR:
* Add UR_RESULT_ERROR_ADAPTER_SPECIFIC as a possible return code to every function in the spec - as it is possible for any adapter to call into a specific API as part of its implementation.
Closes #636
=> [UR] Add adapter specific return code to every function

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/EXP-COMMAND-BUFFER.rst, scripts/core/exp-command-buffer.yml, scripts/core/registry.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
Add new command-buffer functions for appending read and write commands for one-dimensional and rectangular buffers
=> [EXP][CMD-BUFFER] Add read and write function definitions

include/ur.py, include/ur_api.h, scripts/core/common.yml, scripts/templates/exp_feat.rst.mako, scripts/templates/exp_feat.yml.mako
This PR:
* Clarifies `UR_RESULT_ERROR_UNINITIALIZED` to include unimplemented entry-points
* Adds documentation to each experimental feature about support.
Closes #619
=> [UR] Add documentation to experimental feature support

test/conformance/device/urDeviceGet.cpp, test/conformance/device/urDeviceGetInfo.cpp, test/conformance/device/urDeviceRelease.cpp, test/conformance/device/urDeviceRetain.cpp, test/conformance/device/urDeviceSelectBinary.cpp
Fixes some misc Device CTS tests
=> [UR] Device CTS fixes

test/conformance/kernel/urKernelSetArgPointer.cpp
These tests weren't updated after the API change in https://github.com/oneapi-src/unified-runtime/commit/6da20017f64f48813b98b68068b4f730420ec939
These tests aren't built by CI so we didn't catch the regression, see https://github.com/oneapi-src/unified-runtime/issues/650
=> [UR][CTS] Fix urKernelSetArgPointer tests

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/EXP-BINDLESS-IMAGES.rst, scripts/core/exp-bindless-images.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
- Added bindless images revision 4 API changes
- Fixed some errors from revision 3
=> [Exp][Bindless Images] Add BI revision 4 functionality

.github/workflows/cmake.yml
=> [UR] Install DPCXX

source/common/uma_helpers.hpp, source/common/uma_pools/disjoint_pool.cpp, source/common/uma_pools/disjoint_pool.hpp, source/common/unified_memory_allocation/CMakeLists.txt, source/common/unified_memory_allocation/include/uma/base.h, source/common/unified_memory_allocation/include/uma/memory_pool.h, source/common/unified_memory_allocation/include/uma/memory_pool_ops.h, source/common/unified_memory_allocation/include/uma/memory_provider.h, source/common/unified_memory_allocation/include/uma/memory_provider_ops.h, source/common/unified_memory_allocation/src/memory_pool.c, source/common/unified_memory_allocation/src/memory_provider.c, source/common/unified_memory_allocation/src/memory_provider_get_last_failed.cpp, source/common/unified_memory_allocation/src/memory_provider_internal.h, source/common/unified_memory_allocation/src/memory_tracker.cpp, test/unified_memory_allocation/common/pool.c, test/unified_memory_allocation/common/pool.hpp, test/unified_memory_allocation/common/provider.c, test/unified_memory_allocation/common/provider.hpp, test/unified_memory_allocation/memoryPoolAPI.cpp, test/unified_memory_allocation/memoryProviderAPI.cpp
Initially I wanted to implement the same `get_last_error` function for both memory pool and memory provider. However, I realized that the use cases are a bit different:
- for memory provider, we want to get the native code (e.g. to propagate from L0-provider to L0-adapter)
- for memory pool, we are mostly interested with UMA error code (why the allocation/de-allocation failed) - not necessarily with a native error code.
Becasue of that the interface for memory pool and provider is different.
Also, there is one problem with the current approach - return value from `umaPoolGetLastAllocationError` is meaningful only if the last allocation operation (malloc, aligned_malloc, etc.) failed (returned NULL). This means that it cannot be used to report errors from memory_pool::free() since that …
=> [uma] Improve reporting of pool/provider specific errors

test/loader/adapter_registry/CMakeLists.txt
Using `PROJECT_SOURCE_DIR` instead of `CMAKE_SOURCE_DIR` is more resilient as it will still resolve to the base of the unified runtime repository even if used as a sub-project.
I've ran into this issue in my DPC++ build, it's possible my configuration of cache is causing me to hit this when others may not, but it's sensible to replace the CMake variable used here.
=> Fix adapter registry test CMake

scripts/core/EXP-COMMAND-BUFFER.rst, scripts/core/PROG.rst, scripts/generate_docs.py
=> [UR] Support multi-line functions in rst files

scripts/generate_docs.py
In Summary:
* the code was stripping all the white-space around the line including the preceding `tab` characters which moved statement outside of the `code_block`.
Fixes #665
=> [UR] Fix code-block documentation rendering

test/conformance/testing/include/uur/fixtures.h, test/conformance/testing/include/uur/utils.h, test/conformance/virtual_memory/urPhysicalMemCreate.cpp, test/conformance/virtual_memory/urVirtualMemFree.cpp, test/conformance/virtual_memory/urVirtualMemGetInfo.cpp, test/conformance/virtual_memory/urVirtualMemMap.cpp, test/conformance/virtual_memory/urVirtualMemReserve.cpp, test/conformance/virtual_memory/urVirtualMemSetAccess.cpp, test/conformance/virtual_memory/urVirtualMemUnmap.cpp
=> [UR] Test remaining Virtual Memory entry-points

scripts/templates/api_listing.mako
=> [UR] Add macro definitions to API Listing documentation

scripts/templates/exp-features.rst.mako
Change the order of experimental features in the reStructuredText
`.. toctree::` to be alphabetically sorted. This align the order
experimental features are displayed in the *Experimental Features*
section with the *API Documentation* section.
=> [ur] Sort experimental feature toctree order

README.md, scripts/README.md
- add TOC to the top-level README file,
- order sections and group them together (incl. new Contrib section),
- clean and unify Markdown syntax a little,
- add new badges for CodeQL and Bandit,
- fix main GHA badge to point to a specific ('cmake') workflow.
// Preview: [README](https://github.com/lukaszstolarczuk/unified-runtime/tree/revamp-readme#unified-runtime) + [scripts/README](https://github.com/lukaszstolarczuk/unified-runtime/blob/revamp-readme/scripts/README.md)
=> [UR] Revamp README file a little

test/conformance/device_code/CMakeLists.txt, test/conformance/device_code/device_global.cpp, test/conformance/enqueue/CMakeLists.txt, test/conformance/enqueue/urEnqueueDeviceGlobalVariableRead.cpp, test/conformance/enqueue/urEnqueueDeviceGlobalVariableWrite.cpp, test/conformance/testing/include/uur/fixtures.h
=> [UR][CTS] Add tests for urEnqueueDeviceGlobalRead/Write

source/common/unified_malloc_framework/CMakeLists.txt, source/common/unified_malloc_framework/src/memory_tracker.cpp
instead of using a static variable.
In C++ no guarantee is made for initialization order of static variables across translation units.
This is problematic when an application (e.g. SYCL) wants to do some cleanup in it's library destructor. Such application might want to specify priority for it's destructor (to make sure it's executed before any other library desturctor) but it doesn't seem to work for static variables.
=> [umf] create/destroy memory tracker in lib ctor/dtor

include/ur.py, include/ur_api.h, scripts/YaML.md, scripts/core/device.yml, scripts/core/program.yml, scripts/parse_specs.py, scripts/templates/helper.py, scripts/templates/params.hpp.mako, source/common/ur_params.hpp, test/unit/utils/params.cpp
This PR:
* Introduces some new yaml syntax for handling unions.
* A union must specify a tag which is a type that will be used to access the union
* Each member of the union must also specify a `tag` which will refer to a value for which accessing this member is value.
* Use of a union as a member must include `tagged_by(param)` in the description to specify which parameter is used as the tag for the union.
* Safely prints union types in `ur_params.hpp`
~~[TODO] I will add some checks into the generator script to verify these conditions.~~
Closes #538
=> [UR] print unions correctly in ur_params

cmake/helpers.cmake, include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/EXP-COMMAND-BUFFER.rst, scripts/core/exp-command-buffer.yml, scripts/core/registry.yml, source/adapters/0001-SYCL-CUDA-remove-sycl-namespaces-from-ur-adapter.patch, source/adapters/CMakeLists.txt, source/adapters/level_zero/CMakeLists.txt, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/loader/adapter_registry/search_order.cpp
This PR:
- Merges in UR tag c7b0caf4e3ce5330bd0669db6e8e498b48e8ad27
- Applies rebased version patch from https://patch-diff.githubusercontent.com/raw/intel/llvm/pull/10135.patch
- Refactors cmake to support older versions of git
- `-b` option in `git init` is only supported from version `2.28.0`
- `--quiet` option in `git apply` is only supported from version `2.35.0`
Since this is a PR with lots of unrelated changes the files to consider are:
- [helpers.cmake](https://github.com/oneapi-src/unified-runtime/pull/707/files#diff-6db7226737579aec6c1e2537e53fc3c692eda5c93911a32eed3afab00c09e092)
- [cuda patch](https://github.com/oneapi-src/unified-runtime/pull/707/files#diff-87deb274925b8fa80cdf2de6e7b63f1994f1240be24af4d6d9a0375519bf3327)
- [adapters …
=> Update adapter branch with newer CUDA plugin version

CMakeLists.txt, cmake/helpers.cmake, examples/collector/CMakeLists.txt, examples/hello_world/CMakeLists.txt, source/adapters/null/CMakeLists.txt, source/common/umf_pools/CMakeLists.txt, source/common/unified_malloc_framework/CMakeLists.txt, source/loader/CMakeLists.txt, test/conformance/CMakeLists.txt, test/conformance/testing/CMakeLists.txt, test/layers/validation/CMakeLists.txt, test/loader/adapter_registry/CMakeLists.txt, test/loader/platforms/CMakeLists.txt, test/unified_malloc_framework/CMakeLists.txt, test/unit/CMakeLists.txt, test/unit/logger/CMakeLists.txt, test/usm/CMakeLists.txt, tools/urtrace/CMakeLists.txt
Currently, some of compile flags are set globally for the whole project and third-party libraries. Wrap all Unified Runtime CMake targets so that compile and linking flags can be added globally but without affecting third-party repositories' builds.
=> Set global compile flags for UR targets only

scripts/templates/api_listing.mako
Fix copy-pasta bug: Typdefs were listed under structures.
=> Fix API Listing typdef header

source/common/umf_pools/disjoint_pool.cpp
This change is needed to skip tests for a given operation if the pool doesn't support it.
=> [UMF] add handling unsupported functions for disjoint pool

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/EXP-BINDLESS-IMAGES.rst, scripts/core/exp-bindless-images.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
- Added new structs `ur_exp_interop_memory_desc_t` and `ur_exp_interop_semaphore_desc_t`.
- Updated `urBindlessImagesImportOpaqueFDExp` and `urBindlessImagesImportExternalSemaphoreOpaqueFDExp` to use the new structs.
=> [Bindless][Exp] Add bindless images interop resource handles

include/ur_api.h, scripts/core/context.yml, scripts/core/device.yml, scripts/core/event.yml, scripts/core/kernel.yml, scripts/core/memory.yml, scripts/core/platform.yml, scripts/core/program.yml, scripts/core/queue.yml, scripts/core/sampler.yml, source/adapters/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
We cannot make any assumptions about a `native_handle_t` type. For example in CUDA a device is an `int` and `0` is a valid device. This means that the check for `NULL` on native handle will fail.
=> [UR] Add nocheck to native handle types

source/common/umf_helpers.hpp, source/common/umf_pools/disjoint_pool.cpp, source/common/umf_pools/disjoint_pool.hpp, source/common/unified_malloc_framework/include/umf/memory_pool.h, source/common/unified_malloc_framework/include/umf/memory_pool_ops.h, source/common/unified_malloc_framework/src/memory_pool.c, test/unified_malloc_framework/common/pool.c, test/unified_malloc_framework/common/pool.hpp, test/unified_malloc_framework/umf_pools/disjoint_pool.cpp
This is needed in implementation of urUSMFree.
For most cases, the expectation is that the return value from umfPoolFree will be ingnored.
=> [umf] return umf_result_t from umfPoolFree

test/conformance/context/urContextCreateWithNativeHandle.cpp, test/conformance/context/urContextGetNativeHandle.cpp, test/conformance/device/urDeviceCreateWithNativeHandle.cpp, test/conformance/device/urDeviceGetNativeHandle.cpp, test/conformance/event/urEventCreateWithNativeHandle.cpp, test/conformance/event/urEventGetNativeHandle.cpp, test/conformance/kernel/urKernelCreateWithNativeHandle.cpp, test/conformance/kernel/urKernelGetNativeHandle.cpp, test/conformance/memory/urMemBufferCreateWithNativeHandle.cpp, test/conformance/memory/urMemGetNativeHandle.cpp, test/conformance/memory/urMemImageCreateWithNativeHandle.cpp, test/conformance/platform/urPlatformCreateWithNativeHandle.cpp, test/conformance/platform/urPlatformGetNativeHandle.cpp, test/conformance/program/urProgramCreateWithNativeHandle.cpp, test/conformance/program/urProgramGetNativeHandle.cpp, test/conformance/queue/urQueueCreateWithNativeHandle.cpp, test/conformance/queue/urQueueGetNativeHandle.cpp, test/conformance/sampler/urSamplerCreateWithNativeHandle.cpp, test/conformance/sampler/urSamplerGetNativeHandle.cpp, test/conformance/testing/include/uur/fixtures.h
Follow up from #720 where the `nocheck` option was added to the
`ur_native_handle_t` arguments of `ur<Object>CreateWithNativeHandle`.
This patch removes tests which assumed that `ur_native_handle_t` must
not be `nullptr` which is an incorrect assumption.
=> [ur] Update CTS to match native handle nocheck

source/common/ur_util.hpp
Due to possibly harsher compiler checks, the current usage of `GetEnvironmentVariable` causes a conversion error in the Unified Runtime L0 adapter implementation on the https://github.com/intel/llvm/ repo.
CI: https://github.com/intel/llvm/actions/runs/5577820648/jobs/10191589770?pr=10269
This fixes the following error: `error C2664: 'DWORD GetEnvironmentVariableW(LPCWSTR,LPWSTR,DWORD)': cannot convert argument 1 from 'const char *' to 'LPCWSTR'`.
=> Fix GetEnvironmentVariable encoding

test/layers/validation/fixtures.hpp
This patch removes a superflous call to `urLoaderConfigRelease` which resulted in attempting to release and already destroyed `ur_loader_config_handle_t`.
=> [ur] Fix leak validation test fixture

test/conformance/platform/fixtures.h, test/conformance/runtime/fixtures.h
- [coverity] Fix 1566353 Resource leak
- [coverity] Fix 1566354 Resource leak
=> Fix coverity issues from 19/07/2023

scripts/templates/valddi.cpp.mako, source/loader/layers/validation/ur_valddi.cpp
When validation is disabled and an adapter does not sets a DDI table
entry to null the loader returns `UR_RESULT_ERROR_UNINITIALIZED` however
when validation is enabled `UR_RESULT_ERROR_FEATURE_UNSUPPORTED` is
returned. This patch aligns the error codes return by the loader and
validation layer when a null DDI table entry is found.
=> [ur] Match null DDI table entry error code

test/conformance/platform/urPlatformGetNativeHandle.cpp
Do not fail the `urPlatformGetNativeHandleTest.Success` test if adapter
returns `UR_RESULT_ERROR_FEATURE_UNSUPPORTED` from
`urPlatformGetNativeHandle`.
=> [ur] Fix urPlatformGetNativeHandle test

include/ur.py, include/ur_api.h, scripts/core/device.yml, source/common/ur_params.hpp, test/conformance/device/urDeviceGetInfo.cpp
Introduce the missing `UR_DEVICE_INFO_VIRTUAL_MEMORY_SUPPORT`
enumeration for use with `urDeviceGetInfo` to determine if the device
supports the virtual memory interfaces.
=> [ur] Add missing virtual memory support query

source/adapters/CMakeLists.txt, source/adapters/adapter.def.in, source/adapters/adapter.map.in, source/adapters/cuda/CMakeLists.txt, source/adapters/hip/CMakeLists.txt, source/adapters/level_zero/CMakeLists.txt, source/adapters/null/CMakeLists.txt
This adds a version script to restrict visiblity of symbols in adapters. This is so that adapters don't use loader ur functions when populating proc tables...
Before:
```sh
piotrekpc :: unified-runtime/build/bin ‹adapters-ci*› » UR_ADAPTERS_FORCE_LOAD=../lib/libur_adapter_hip.so ./hello_world
AddressSanitizer:DEADLYSIGNAL
=================================================================
==84218==ERROR: AddressSanitizer: stack-overflow on address 0x7ffe394fefc0 (pc 0x7f843eac49b1 bp 0x7ffe394ff0d0 sp 0x7ffe394fefc0 T0)
#0 0x7f843eac49b1 in void std::call_once<urInit::$_0>(std::once_flag&, urInit::$_0&&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../include/c++/13.1.1/mutex:897
#1 0x7f843eac44d2 in urInit /home/piotrek/work/unified-runtime/source/loader/ur_libapi.cpp:48:5
#2 …
```
=> [adapters] only export get proc table symbols in adapters

source/common/unified_malloc_framework/include/umf/memory_pool.h, test/unified_malloc_framework/common/pool.hpp, test/unified_malloc_framework/memoryPool.hpp, test/unified_malloc_framework/memoryPoolAPI.cpp
Basic tests for UMA allocations. More will be added in the following PRs.
=> [UMA] add more tests for allocations

source/common/unified_malloc_framework/src/memory_pool_default.c, test/unified_malloc_framework/common/pool.hpp, test/unified_malloc_framework/memoryPool.hpp, test/unified_malloc_framework/memoryPoolAPI.cpp
- memory leak in memory_pool_default.c and tests
- allocating memory with alignemnt=8 and size%8 != 0
=> [umf] fix erors reported by ASAN

test/unified_malloc_framework/memoryPool.hpp
to make ASAN happy. By default we are using alignment == 8 and size needs to be a multiple of that.
We might consider adding extra tests, specifically for different sizes.
=> [umf] use alloc sizes that are multiples of 8 in tests

.github/docker/README.md, .github/docker/install_dpcpp.sh, .github/docker/install_libbacktrace.sh, .github/docker/ubuntu-22.04.Dockerfile
This image can be used in CI or as a development container.
// tested locally, it works like a charm.
=> Add first Docker image recipe

source/adapters/CMakeLists.txt
Use an absolute path instead of just the filename for the
`ur_adapter_<name>.map` files to resolve `/usr/bin/ld: cannot open
linker script file` errors.
=> [ur] Fix adapters linker script path on Linux

test/conformance/CMakeLists.txt, test/conformance/adapters/CMakeLists.txt, test/conformance/adapters/cuda/CMakeLists.txt, test/conformance/adapters/cuda/cuda_fixtures.h, test/conformance/adapters/cuda/cuda_urContextGetNativeHandle.cpp, test/conformance/adapters/cuda/cuda_urDeviceCreateWithNativeHandle.cpp, test/conformance/adapters/cuda/cuda_urDeviceGetNativeHandle.cpp, test/conformance/adapters/cuda/cuda_urEventCreateWithNativeHandle.cpp, test/conformance/adapters/cuda/cuda_urEventGetNativeHandle.cpp
This PR:
- Adds a new conformance target `test-adapter-cuda` which runs adapter specific CTS tests against the CUDA adapter.
- Currently I have only added CTS tests for 'Native Handle' entry-points, but further testing can easily be added.
I'm currently targeting this PR against the `adapters` branch, but perhaps we could have a separate branch in upstream to track changes separately.
=> [UR] Implement CUDA native handle tests

test/conformance/enqueue/urEnqueueKernelLaunch.cpp, test/conformance/testing/include/uur/fixtures.h
This tests that we can you a virtual memory pointer instead of a USM pointer. In this test we enqueue a kernel with a virtual memory pointer instead of a USM pointer and using several `urUSM` entry points.
Closes #669
=> [UR] Extend testing of virtual memory

include/ur.py, scripts/YaML.md, scripts/core/runtime.yml, scripts/templates/api.py.mako, scripts/templates/ddi.h.mako, scripts/templates/helper.py, scripts/templates/libapi.cpp.mako, scripts/templates/libddi.cpp.mako
This will make adding new loader-specific APIs easier.
=> [UR] add a loader_only flag to the spec

test/conformance/testing/CMakeLists.txt, test/conformance/testing/include/uur/fixtures.h, test/conformance/testing/source/fixtures.cpp, test/conformance/usm/urUSMDeviceAlloc.cpp, test/conformance/usm/urUSMGetMemAllocInfo.cpp, test/conformance/usm/urUSMHostAlloc.cpp, test/conformance/usm/urUSMPoolCreate.cpp, test/conformance/usm/urUSMSharedAlloc.cpp
Also fix a couple of minor issues in tests:
* check correct code for invalid size in GetMemAllocInfo test
* fix shadowing in urUSMPoolTestWithParam fixture
* ensure we allocate with a pool for UR_USM_ALLOC_INFO_POOL GetMemAllocInfo test
Addresses #738
=> Add parameterization to USM alloc tests for testing pools.

test/conformance/adapters/CMakeLists.txt, test/conformance/adapters/hip/CMakeLists.txt, test/conformance/adapters/hip/hip_fixtures.h, test/conformance/adapters/hip/hip_urContextGetNativeHandle.cpp, test/conformance/adapters/hip/hip_urDeviceGetNativeHandle.cpp, test/conformance/adapters/hip/hip_urEventGetNativeHandle.cpp
Adds HIP specific CTS for native handle entry-points
1. urContextGetNativehandle
2. urDevicGetNativeHandle
3. urEventGetNativeHandle
=> [ADAPTERS] HIP specific CTS

scripts/templates/params.hpp.mako, source/common/ur_params.hpp
This PR:
Adds a `is_handle_v` check which is necessary when we have tests (i.e. the CUDA/HIP) specific ones that link against the actual implementation of an adapter and the type is complete.
TODO - cherry pick this commit into the `adapters` branch
=> [UR] Check for if handle when type is complete

source/common/unified_malloc_framework/src/memory_provider_get_last_failed.cpp, source/common/unified_malloc_framework/src/memory_provider_internal.h
For some reason this isn't being caught by default cmake build...
=> [umf] fix a function declaration without a prototype

test/conformance/enqueue/urEnqueueMemBufferCopyRect.cpp, test/conformance/enqueue/urEnqueueMemBufferReadRect.cpp, test/conformance/enqueue/urEnqueueMemBufferWriteRect.cpp
Ref: #595
I've looked over all the non-experimental APIs where adapters can potentially do arithmetic to calculate buffer offsets/sizes for copying/allocation, and these three were missing relevant tests for invalid size checks or overflow. The rest of the functions have tests for either overflow or out-of-bounds access.
=> [cts] add integer overflow/bounds check tests for rect APIs

CMakeLists.txt, README.md, source/adapters/CMakeLists.txt, source/adapters/opencl/CMakeLists.txt
This is temporarily using a fork until https://github.com/intel/llvm/pull/10490 is reviewed and merged.
=> Add preview of the OpenCL adapter to the adapters branch

scripts/core/INTRO.rst, source/common/linux/ur_lib_loader.cpp
RTLD_DEEPBIND can help solve conflicts with shared library versions, but it interferes with overriding functions in shared objects through LD_PRELOAD and similar mechanisms.
Fixes #803
=> [loader] make RTLD_DEEPBIND optional when loading adapters

.github/workflows/cmake.yml, cmake/helpers.cmake, scripts/templates/params.hpp.mako, source/common/ur_params.hpp
Fix compilation of passing function pointers to `std::ostream`s when compiling with `clang-cl.exe` on Windows. Extend the GitHub Actions matrix on Windows to test both the `cl.exe` and `clang-cl.exe` compiler frontends.
Following on from #814.
=> [ur] Add support for clang-cl.exe on Windows

source/common/CMakeLists.txt, test/loader/loader_config/CMakeLists.txt
The recent hotfix in #800 requiring the v0.7.1 tag was fixing an instance of code not compiling when `-Werror` is specified. We do already specify `-Werror` with `UR_DEVELOPER_MODE=ON` in the GitHub Actions, however the `ur_common` library was not being compiled explicitly with this flag.
As setup prior to this patch `ur_common` was an interface library. This means the source files are not compiled into their own static library but instead included in any targets which "link" it.
This patch changes the `ur_common` into a static library that is always compiled into a static library avoiding recompiling the source files in each target which makes use of it. Adapters will now link with the static library instead of including its source files into their own targets build steps. Additionally, …
=> [cmake] Ensure code is compiled with -Werror in dev mode

test/conformance/context/urContextCreateWithNativeHandle.cpp
=> [UR] Fix urContextNativeHandle CTS

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/EXP-COMMAND-BUFFER.rst, scripts/core/exp-command-buffer.yml, scripts/core/registry.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
- Adds USM and Buffer fill append commands
- Update feature spec for new commands
- Aligns Append* naming conventions with core equivalents
=> [EXP][CMDBUF] Add fill commands to cmd buffer experimental feature

source/adapters/CMakeLists.txt
While attempting to enable the Level-Zero and OpenCL adapters at the same time git will report an error due to the OpenCL tag not existing in the intel/llvm clone use for the Level-Zero adapter. Furthermore, if I wanted to test separate bug fixes for the CUDA and HIP adapters from different sources, this would also not be possible.
This patch uses a separate FetchSource for each adapter to allow each adapters source to be fetched independently of the others and moves those clones into the build directory. This does result in additional git clones when enabling multiple adapters and again in multiple build directories but avoids conflicting remote URL's or multiple build configurations trampling on each others checked out tags.
=> [cmake] Use separate FetchSource's per adapter

scripts/ctest_parser.py
Credit: @martygrant 
We had used this parser script to measure the CTS pass rate of each adapter in our internal CI. Since UR holds all the CTS tests it makes sense to upstream it here.
I've modified martin's original parser such that we run conformance test suites individually. Instead of parsing the output from stdout we can use the `GTEST_OUTPUT` environment variable to specify that GTEST should output it's testing summary into a json file. We can then parse this and summarize the results. 
Example output:
=> [UR][CTS] Upstream CTS parser

scripts/generate_code.py, scripts/json2src.py, scripts/templates/tools-info.hpp.mako, tools/CMakeLists.txt, tools/urinfo/CMakeLists.txt, tools/urinfo/urinfo.cpp, tools/urinfo/urinfo.hpp, tools/urinfo/utils.hpp
`urinfo` is a command-line tool for inspecting the current execution
environment:
```console
$ build/bin/urinfo --help
usage: build/bin/urinfo [-h] [-v] [-V]
This tool enumerates Unified Runtime layers, adapters, platforms, and
devices which are currently visible in the local execution environment.
options:
-h, --help            show this help message and exit
--version             show version number and exit
-v, --verbose         print additional information
```
=> [ur] Introduce urinfo tool

.github/workflows/nightly.yml
Fuzz tests set up with cron don't run because cron scheduled workflows are triggered only for the default branch.
Add nightly workflow file to the default branch with fuzz tests specified to run on 'adapters' branch.
=> Move nightly CI tests to the main branch

source/common/umf_pools/disjoint_pool.cpp
To make debugging easier when `memoryProviderFree` in ~Slab fails.
We should also implement get_last_native_error` for adapters to set the error message correctly.
=> [umf] extend error message for disjoint pool

source/common/unified_malloc_framework/src/memory_tracker.c, source/common/unified_malloc_framework/src/utils/utils_posix.c
The AppleClang compiler emits warnings in C functions with zero arguments that are not specified as `f(void)`.
=> [umf] Fix macOS build

include/ur.py, include/ur_api.h, scripts/core/EXP-BINDLESS-IMAGES.rst, scripts/core/exp-bindless-images.yml, source/common/ur_params.hpp
To enable support for layered images, pass this struct via `pNext` when using the experimental feature to create an image. The struct is used to determine number of layers in the layered image.
=> [Bindless][Exp] Create layered image properties struct

cmake/helpers.cmake, source/common/unified_malloc_framework/src/utils/utils.h
When updating the tag of UR in SYCL I got the -Wempty-body warning emitted from UMF. This PR just places braces around the do statement to prevent emitting this warning.
=> [UMF] Fix -Wempty-body warning

include/ur_api.h, scripts/core/enqueue.yml, source/loader/ur_libapi.cpp, source/ur_api.cpp
Clarify the behaviour of urUSMMemAdvise and urUSMPrefetch when the hint is unsupported
=> Clarify the behaviour of urUSMMemAdvise and urUSMPrefetch

include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/EXP-COOPERATIVE-KERNELS.rst, scripts/core/exp-cooperative-kernels.yml, scripts/core/registry.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/loader/ur_libddi.cpp, source/ur_api.cpp
Add two new functions for working with cooperative kernels:
- `urKernelSuggestMaxCooperativeGroupCount`
- `urEnqueueCooperativeKernelLaunch`
=> Add cooperative kernels experimental feature

include/ur_api.h, scripts/core/device.yml, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/device/urDeviceGet.cpp
It should be invalid to pass a positive number for the number of devices and a null pointer for the device handle pointer. If this situation occurs we should return an invalid null pointer. Invalid size might also be a valid return code, but decided to use null pointer error to indicate that likely the device handle pointer is incorrect.
=> [UR] Add validation check to urDeviceGet

CMakeLists.txt, examples/CMakeLists.txt, examples/codegen/CMakeLists.txt, examples/codegen/codegen.cpp, examples/codegen/helpers.cpp, examples/codegen/helpers.h, scripts/deps.yml
I was able to come up with an end-to-end pipeline of code generation and execution that typically occurs in a JIT engine (our use case is the analytical query compilation in [HDK](https://github.com/intel-ai/hdk/tree/main)). It creates a simple function (adding +1 to an array and storing the result in a second one) via llvm api, converts it to spirv, and submits it to the runtime. 
The example is a bit complex in terms of dependencies: it uses llvm api, the spirv translator library, and intel gpu stack for execution. I found managing those in conda was the easiest way (I'm a bit biased though :) ). Nevertheless, I'm attaching the exact environment in `scripts/deps.yml` for reproduction simplicity (doesn't include the toolchain since any dev env for UR would already have it). Use as: …
=> End-to-end code generation example

include/ur.py, include/ur_api.h, scripts/core/EXP-BINDLESS-IMAGES.rst, scripts/core/exp-bindless-images.yml, source/common/ur_params.hpp
This MR adds a struct allowing for unique addressing modes per dimension
=> [Bindless] Struct for unique addressing modes per dimension

cmake/helpers.cmake, examples/collector/collector.cpp, examples/hello_world/hello_world.cpp, scripts/templates/params.hpp.mako, source/adapters/null/ur_null.cpp, source/common/unified_malloc_framework/src/memory_pool_default.c, source/common/unified_malloc_framework/src/memory_tracker_windows.cpp, source/common/ur_params.hpp, source/common/ur_singleton.hpp, source/loader/ur_lib.cpp, test/conformance/event/urEventSetCallback.cpp, test/conformance/source/environment.cpp, test/loader/platforms/platforms.cpp, test/unified_malloc_framework/common/pool.hpp, test/unified_malloc_framework/common/provider.hpp, test/unified_malloc_framework/memoryPoolAPI.cpp, test/unified_malloc_framework/umf_pools/disjoint_pool.cpp, tools/urtrace/collector.cpp
Since UR is imported as a library to different project, we should make sure we don't cause warnings with their compiler. A common warning is for unused parameters so we should ensure we don't raise this warning when compiling the code.
=> [UR] Check for unused parameters

include/ur.py, include/ur_api.h, scripts/core/exp-bindless-images.yml, scripts/templates/helper.py, scripts/templates/params.hpp.mako, source/common/ur_params.hpp, test/unit/utils/params.cpp
This PR:
* Adds support to type members of structs as c-style arrays
* Changes `ur_exp_sampler_addr_modes_t` to use array as requested in #863 
Closes #869
=> [UR] Support C style arrays

CMakeLists.txt
Fix issue where CMake ignores the Python interpreter specified by a virtual environment by default. This results in the generate targets failing when the Python package requirements are installed in a virtual environment but the system interpreter is found by CMake.
This patch replaces the use of `CMAKE_FIND_FRAMEWORK` with the more precise `Python3_FIND_FRAMEWORK`. It also sets the `Python3_FIND_STRATEGY` to `LOCATION` which stops searching once the first Python interpreter is found, i.e. the interpreter from an activated virtual environment, or the system interpreter otherwise.
=> [cmake] Respect Python virtualenv on macOS

test/conformance/enqueue/urEnqueueMemImageCopy.cpp, test/conformance/enqueue/urEnqueueWriteHostPipe.cpp, test/conformance/kernel/urKernelCreateWithNativeHandle.cpp, test/conformance/kernel/urKernelSetArgPointer.cpp, test/conformance/program/urProgramCreateWithNativeHandle.cpp, test/conformance/program/urProgramGetInfo.cpp, test/conformance/testing/include/uur/fixtures.h, test/conformance/virtual_memory/urVirtualMemGranularityGetInfo.cpp
* Remove null pointer tests for optional EnqueueWriteHostPipe and KernelCreateWithNativeHandle params
* Correct a few error code expectations
* Ensure virtual mem tests skip properly when there isn't support
=> Fix a few minor CTS issues

.github/workflows/cmake.yml
=> Temporarily disable running check-generated target in windows CI.

cmake/match.cmake, cmake/match.py
When a test fails a match, cmakes print both the
input file and the match file, so that it's easy to see why the failure happened and how to fix it. Unfortunately, cmake was inserting 3 newlines between every line of both input and match files, making things hard to read.
This patch fixes this by moving match and input files printing to the python script.
=> [test] improve match file error output

source/adapters/level_zero/ur_interface_loader.cpp
These symbols are required to be exported by the .def file on Windows
=> [L0] Add missing loader interfaces to L0 adapter

examples/codegen/README.md, examples/codegen/codegen.cpp, third_party/deps.yml
This PR is a follow up PR to address the rest of review [feedback](https://github.com/oneapi-src/unified-runtime/pull/610#pullrequestreview-1611102999) on [610](https://github.com/oneapi-src/unified-runtime/pull/610). It contains:
* readme file to instruct how to run the codegen example.
* filter out adapters that doesn't support spirv kernels from codegen example.
* print the input array to the spv kernel in the codegen example.
Fixes: [859](https://github.com/oneapi-src/unified-runtime/issues/859)
=> Followup review feedback on e2e codegen example

test/conformance/event/fixtures.h, test/conformance/kernel/urKernelCreateWithNativeHandle.cpp, test/conformance/queue/urQueueCreateWithNativeHandle.cpp, test/conformance/queue/urQueueGetInfo.cpp
Mostly these are consistency related:
* Add missing EventWait to event fixture
* Set isNativeHandleOwned to false in KernelCreateWithNativeHandleTest
* Use more commonly supported UR_QUEUE_INFO_CONTEXT query in QueueCreateWithNativeHandleTest
* Add UR_RESULT_ERROR_UNSUPPORTED_ENUMERATION path to QueueGetInfo test
=> Another small batch of CTS fixes

.github/workflows/bandit.yml, .github/workflows/cmake.yml, .github/workflows/codeql.yml
We have a limited number of runners for the adapter testing jobs, so this helps avoid congestion
=> CI: Cancel stale workflows when new commits are added to a PR

scripts/core/CONTRIB.rst
Now that adapter implementations are coming to live in this repo we need a process to ensure we maintain the quality of changes in dependent projects such as [intel/llvm](https://github.com/intel/llvm). This patch updates the contribution guide to include a section titled *Adapter Change Process* which details the process to follow when making changes which affect the API/ABI or UR or the behaviour of adapters.
=> [ur] Document the Adapter Change Process

third_party/requirements.txt
It cannot be found on a (bare metal) machine with Win Server 2022.
=> [UR] bump libxml requirement version

cmake/match.cmake, cmake/match.py
Input and match files were printed only on one error. Now, it will be printed in both places (where this makes sense).
This is an extension to commit: be85a494bd
=> [UR][Tests] Update match scripts

source/adapters/level_zero/CMakeLists.txt
On Windows we may build L0 using ICX , this is to revert changes to
check WIN32 instead of MSVC, to fix build failures with ICX on Windows.
=> [UR][L0][CMake] Disable warning for ICX on Windows

test/unified_malloc_framework/common/pool.hpp, test/unified_malloc_framework/memoryPool.hpp, test/unified_malloc_framework/memoryPoolAPI.cpp, test/unified_malloc_framework/umf_pools/disjoint_pool.cpp
It is the continuation of the previous out of memory test. This PR adds check for the disjoint pool if after reaching out of memory error from the provider and then freeing some memory, we are able to allocate again.
Based on #783
=> [umf] extend out of memory test for disjoint pool

.github/workflows/cmake.yml, source/adapters/level_zero/CMakeLists.txt
This patch addresses the portability of L0 cmake scripts and adds building L0 adapter in CI on Windows. There were a lot of conversion warnings in the L0 adapter itself, so I disabled these for now. I've also had to exclude windows 2019 from building the adapter because of these errors from level-zero loader:
```
2023-10-03T10:10:14.5073647Z   Building Custom Rule D:/a/unified-runtime/unified-runtime/source/adapters/null/CMakeLists.txt
2023-10-03T10:10:15.0383355Z D:\a\unified-runtime\unified-runtime\build\_deps\level-zero-loader-src\source\loader\windows\driver_discovery_win.cpp(37,69): error C2065: 'GUID_DEVCLASS_COMPUTEACCELERATOR': undeclared identifier [D:\a\unified-runtime\unified-runtime\build\_deps\level-zero-loader-build\source\ze_loader.vcxproj]
2023-10-03T10:10:15.0662878Z …
```
=> [L0] fix windows cmake scripts

source/adapters/level_zero/CMakeLists.txt
We allow reusing existing pre-built L0 Libs and Headers.
However, using LEVEL_ZERO_LIBRARY and LEVEL_ZERO_INCLUDE_DIR directly
may leak the path of shared folder.
This PR introduces two L0_LIBRARY and L0_INCLUDE_DIR ,
and copy L0 loader/headers locally to the build to avoid leaking their
location on a shared drive.
Originally authored by @smaslov-intel .
=> [UR][L0] Copy prebuilt L0 to avoid leaking shared folder path

scripts/templates/helper.py, scripts/templates/valddi.cpp.mako, source/loader/layers/validation/ur_valddi.cpp, test/conformance/enqueue/urEnqueueEventsWait.cpp, test/conformance/enqueue/urEnqueueEventsWaitWithBarrier.cpp, test/conformance/enqueue/urEnqueueKernelLaunch.cpp, test/conformance/enqueue/urEnqueueMemBufferCopy.cpp, test/conformance/enqueue/urEnqueueMemBufferCopyRect.cpp, test/conformance/enqueue/urEnqueueMemBufferFill.cpp, test/conformance/enqueue/urEnqueueMemBufferMap.cpp, test/conformance/enqueue/urEnqueueMemBufferRead.cpp, test/conformance/enqueue/urEnqueueMemBufferReadRect.cpp, test/conformance/enqueue/urEnqueueMemBufferWrite.cpp, test/conformance/enqueue/urEnqueueMemBufferWriteRect.cpp, test/conformance/enqueue/urEnqueueMemImageCopy.cpp, test/conformance/enqueue/urEnqueueMemImageRead.cpp, test/conformance/enqueue/urEnqueueMemImageWrite.cpp, test/conformance/enqueue/urEnqueueMemUnmap.cpp, test/conformance/enqueue/urEnqueueReadHostPipe.cpp, test/conformance/enqueue/urEnqueueUSMFill.cpp, test/conformance/enqueue/urEnqueueUSMFill2D.cpp, test/conformance/enqueue/urEnqueueUSMMemcpy.cpp, test/conformance/enqueue/urEnqueueUSMMemcpy2D.cpp, test/conformance/enqueue/urEnqueueUSMPrefetch.cpp, test/conformance/enqueue/urEnqueueWriteHostPipe.cpp
Adds checks in the validation layer for the case where the event wait list parameter in urEnqueue entrypoints contains a nullptr event.
- Also adds more tests because this behaviour was only being checked for urEnqueueDeviceGetGlobalVariableRead and urEnqueueDeviceGetGlobalVariableWrite
=> Add validation layer support for nullptr events

source/adapters/level_zero/usm.cpp
This change ensures that USM allocation APIs don't return `UR_RESULT_SUCCESS` when an error occurs within `USMAllocationMakeResident`.
=> [UR][L0] Propagate errors from `USMAllocationMakeResident`

test/conformance/enqueue/urEnqueueKernelLaunch.cpp, test/conformance/enqueue/urEnqueueMemBufferReadRect.cpp, test/conformance/enqueue/urEnqueueMemImageCopy.cpp, test/conformance/enqueue/urEnqueueMemImageRead.cpp, test/conformance/testing/include/uur/fixtures.h
Fixes [862](https://github.com/oneapi-src/unified-runtime/issues/862)
=> Add testing for memory management across multi-device contexts

.github/workflows/e2e_nightly.yml
This is the first approach to e2e testing.
The tests run on an internal runner with Nvidia Cuda Backend.
At this moment the workflow is adapted only for Cuda.
In the future, we plan to add support for L0 and HIP,
and optimize execution time by separating sycl compilation.
=> [UR][E2E][CUDA] Add E2E Cuda nightly workflow

source/adapters/hip/context.cpp, test/conformance/context/context_adapter_hip.match
Adapter-specific change from https://github.com/intel/llvm/pull/11344 .
=> [HIP] Re add extended deleters

.github/workflows/cmake.yml, include/ur.py, include/ur_api.h, include/ur_ddi.h, scripts/core/EXP-MULTI-DEVICE-COMPILE.rst, scripts/core/exp-multi-device-compile.yml, scripts/core/program.yml, scripts/core/registry.yml, source/adapters/null/ur_nullddi.cpp, source/common/ur_params.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/loader/ur_libddi.cpp, source/ur_api.cpp
piProgramBuild receives a list of devices, while urProgramBuild does not. This produces a series of issues when a UR program needs to be created for a specific device.
So define a new API, called urProgramBuildExp to pass this list.
Authored-by: jaime.a.arteaga.molina@intel.com
=> [UR][L0] Add support for passing device list to urProgramBuild

scripts/core/CONTRIB.rst
Since merging into the adapters branch imposes an ordering on changes which should be merged into intel/llvm, expand step 7 of the *Adapter Change Process* to include linking to dependent intel/llvm PR's to communicate this ordering to the maintainers.
=> Update contribution guide to link to dependent PRs

source/adapters/level_zero/usm.cpp
Reverts oneapi-src/unified-runtime#906 due to a regression in https://github.com/intel/llvm/pull/11312.
=> Revert "[UR][L0] Propagate errors from `USMAllocationMakeResident`"

.github/CODEOWNERS
Set @oneapi-src/unified-runtime-command-buffer-write as the codeowners of the command-buffer experimental feature. Including:
* Adapter implementations
* Specification document
* YML definition
=> Set command-buffer experimental feature codeowners

include/ur.py, include/ur_api.h, scripts/core/loader.yml, scripts/core/registry.yml, scripts/templates/trcddi.cpp.mako, scripts/templates/valddi.cpp.mako, source/common/ur_params.hpp, source/loader/CMakeLists.txt, source/loader/layers/tracing/ur_tracing_layer.cpp, source/loader/layers/tracing/ur_tracing_layer.hpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/ur_proxy_layer.hpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/layers/validation/ur_validation_layer.hpp, source/loader/ur_codeloc.hpp, source/loader/ur_lib.cpp, source/loader/ur_lib.hpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/layers/tracing/CMakeLists.txt, test/layers/tracing/codeloc.cpp, test/layers/tracing/codeloc.out.match, test/layers/tracing/test_collector.cpp
This addresses the gap between XPTI support in PI and UR, where UR implementation was unable to provide code location information in traces, by adding an optional callback that, when set, allows language runtimes to provide this information.
=> [ur][loader] add code location callback for tracing layer

source/common/umf_pools/disjoint_pool.cpp, source/common/umf_pools/disjoint_pool.hpp
Currently, for when the MinBucketSize parameter equals 1, sizes were generated with duplicates (such as 1,1,2,2,4,4...). Since such small sized buckets aren't needed anyway this PR changes the minimal value of MinBucketSize to 8.
=> [umf] change default MinBucketSize and ensure buckets are generated from the min size 8

README.md, source/adapters/hip/CMakeLists.txt, source/adapters/hip/common.cpp, source/adapters/hip/common.hpp, source/adapters/hip/program.cpp, source/adapters/hip/program.hpp, source/ur/ur.hpp
For kernel fusion support for hip, we need to finalize the kernels using comgr. The patch finalizes tagged binaries during buildProgram before handing it over to the hip runtime.
Initial / related PR https://github.com/intel/llvm/pull/11003
=> [UR][HIP] Enable kernel finalization using comgr

.github/CODEOWNERS
Add `unified-runtime-bindless-images-write` team
as code owners for anything related to images.
=> CODEOWNERS for Bindless Images

source/adapters/level_zero/command_buffer.cpp
The L0 events used to implement [UR sync-points](https://oneapi-src.github.io/unified-runtime/core/EXP-COMMAND-BUFFER.html#sync-points) in a command-buffer aren't reset after the first execution. Leaving them in a signaled state before subsequent submissions of the UR command-buffer.
This patch resets the L0 events used as UR command-buffer sync-points to the non-signaled state, by appending event reset commands to the end of the user defined command-list. There is also a reset added for the UR command-buffer wait event that is signaled when the wait list dependencies of `urCommandBufferEnqueueExp` are met.
Additionally this patch removes the host scope flag from being set on L0 events created by the UR command-buffer, as we never signal/reset them from host, only device.
Companion DPC++ …
=> [Command-buffer][L0] Reset sync-point events

.github/workflows/e2e_nightly.yml
GITHUB env vars are set only from the next step up, not right away.
=> [CI] Split E2E steps into two

include/ur.py, include/ur_api.h, include/ur_ddi.h, include/ur_print.hpp, scripts/core/EXP-MULTI-DEVICE-COMPILE.rst, scripts/core/exp-multi-device-compile.yml, scripts/core/program.yml, scripts/core/registry.yml, source/adapters/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/loader/ur_libddi.cpp, source/ur_api.cpp
Instead of relying on the list of devices used to create a context, provide interfaces which instead take a list of devices. This more closely aligns with PI and OpenCL. Introduced to workaround a regression. May be superseded in future.
Pull's in the changes in #919 to the main branch.
=> [UR][L0] Add the multi-device-compile experimental feature

source/adapters/cuda/enqueue.cpp, source/adapters/cuda/kernel.cpp, source/adapters/cuda/memory.cpp, source/adapters/cuda/memory.hpp, source/adapters/hip/enqueue.cpp, source/adapters/hip/kernel.cpp, source/adapters/hip/memory.cpp, source/adapters/hip/memory.hpp
Std::variant is safer than unions in the `ur_mem_handle_t_` class and it will make it easier to incrementally move to multi device ctx, which requires adding `std::vector`s to the MemImpl, which is not possible in a union.
=> [HIP][CUDA] Change unions in ur_mem_handle_t_ to stdvariant

test/conformance/enqueue/urEnqueueMemBufferFill.cpp, test/conformance/enqueue/urEnqueueUSMFill.cpp, test/conformance/enqueue/urEnqueueUSMFill2D.cpp, test/conformance/enqueue/urEnqueueUSMMemcpy.cpp, test/conformance/enqueue/urEnqueueUSMMemcpy2D.cpp
* Release a couple of events
* Check the output buffer for Fill2D row first instead of column first
* Change size of a pattern to match the size of a fill
=> Fix a couple of minor issues in the USM fill and memcpy tests

source/adapters/opencl/enqueue.cpp, source/adapters/opencl/program.cpp
Adds a version check to only look up the extension function pointer for urProgramSetSpecializationConstants if the platform or any attached device OpenCL version is < 2.2. Also fixes minor build error with missing namespace in enqueue.cpp.
intel-llvm PR - https://github.com/intel/llvm/pull/11720
=> [OpenCL] Add version check for urProgramSetSpecializationConstants 

source/adapters/cuda/device.cpp, source/adapters/cuda/device.hpp, source/adapters/cuda/enqueue.cpp
With this patch when the user asks for the amount of `localMemSize`, they receive the maximum amount available on the SM. Setting the maximum limit with the env variable still remains an option.
=> [UR] [CUDA] Changed the output of querying localMemSize

source/adapters/level_zero/adapter.cpp, source/adapters/level_zero/common.cpp, source/adapters/level_zero/common.hpp, source/adapters/level_zero/device.cpp, source/adapters/level_zero/kernel.cpp, test/conformance/runtime/runtime_adapter_level_zero.match
LLVM testing in https://github.com/intel/llvm/pull/11760
=> [UR][L0] Add support for urAdapterGetLastError in L0

source/adapters/level_zero/command_buffer.cpp, source/adapters/level_zero/device.cpp, source/adapters/level_zero/kernel.cpp, source/adapters/level_zero/platform.cpp, source/adapters/level_zero/queue.cpp
This fixes collision between min/max functions and macros on Windows.
=> [SYCL][UR][L0] Distinguish min/max calls from macros

.github/workflows/cmake.yml
When initializing conda few extra commands are added to user's profile. These commands make it impossible to log in as the test user to the machine, since conda may be missing.
We can safely remove the whole '.profile' after the job.
=> [CI] Clean up after conda init in cmake.yml

.github/workflows/coverage.yml
Preview: https://app.codecov.io/gh/pbalcer/unified-runtime
Codecov still needs to be enabled for the `oneapi-src` organization. Also, this workflow needs to run on the default branch on the repo, so until the adapter and main branches are merged, we won't see the adapter coverage.
=> [common] add codecov

source/adapters/opencl/enqueue.cpp, source/adapters/opencl/memory.cpp, source/adapters/opencl/program.cpp
Fix memory leak reported in #1034 
This bug was introduced when porting the original OpenCL plugin to UR. If the `clCreateBufferWithProperties` extension function exists, we should return even if it succeeds rather than continuing to the fallback call to `clCreateBuffer`.
Also add fixes from #1054:
> Address coverity issue with dodgy struct-to-array casts
>
> Also fix a similar issue coverity had with CreateProgramWithBinary which was passing array pointers straight through to the cl entry point by putting these params in local const arrays.
>
=> [OpenCL] Fix memory leak and coverity issue with struct-to-array casts

source/adapters/cuda/program.cpp, source/adapters/cuda/ur_interface_loader.cpp, source/adapters/hip/program.cpp, source/adapters/hip/ur_interface_loader.cpp, source/adapters/native_cpu/program.cpp, source/adapters/native_cpu/ur_interface_loader.cpp, source/adapters/opencl/program.cpp, source/adapters/opencl/ur_interface_loader.cpp
Ensure that all adapters have the correct signatures for the multi-device compile experimental feature entry points and that they entry points exist even when returning `UR_RESULT_ERROR_UNSUPPORTED_FEATURE`.
Fixes the failing checks in https://github.com/intel/llvm/pull/11464.
=> [CUDA][HIP][OpenCL][NATIVECPU] Fix multi-device compile

source/adapters/level_zero/adapter.cpp, source/adapters/level_zero/common.cpp, source/adapters/level_zero/common.hpp, source/adapters/level_zero/platform.cpp
Use a new environment variable, UR_L0_LEAKS_DEBUG, to check for leaks in the UR L0 adapter, instead of relying on a specific value being set in UR_L0_DEBUG.
LLVM testing: https://github.com/intel/llvm/pull/11820
=> [UR][L0] Add UR_L0_LEAKS_DEBUG key

.github/workflows/cmake.yml
Fixes issue #1111. Enable clang-cl test builds on Windows in the Github Actions workflow.
Also:
- Remove redundant '.exe' suffixes.
- Run Windows builds on the max available number of cpus.
=> [CI] Fix Clang on Windows builds

include/ur_print.hpp, scripts/templates/print.hpp.mako, source/common/logger/ur_sinks.hpp, test/loader/loader_lifetime/urLoaderInit.cpp, test/unit/utils/params.cpp
Put all printing operators in the global namespace where all API objects reside.
This PR is related to the issue #1086
=> [UR] Remove ur::print:: namespace

source/adapters/cuda/command_buffer.cpp
The code introduced in 74f42f8fdd3b92b355c5769bd13d4d982e839c78 uses the signature of `cuGraphInstantiate` from CUDA 12.x. In CUDA 11.4-11.8, the same function is called `cuGraphInstantiateWithFlags`, so we use it. In older CUDA, there is only the old version of `cuGraphInstantiate` which does not accept flags.
- https://docs.nvidia.com/cuda/archive/11.8.0/cuda-driver-api/group__CUDA__GRAPH.html#group__CUDA__GRAPH_1g433ae118a751c9f2087f53d7add7bc2c
- https://docs.nvidia.com/cuda/archive/12.0.0/cuda-driver-api/group__CUDA__GRAPH.html#group__CUDA__GRAPH_1g433ae118a751c9f2087f53d7add7bc2c
=> [UR][CUDA] Fix compatibility with CUDA 11.x

source/adapters/native_cpu/common.hpp, source/adapters/native_cpu/context.cpp, source/adapters/native_cpu/context.hpp, source/adapters/native_cpu/kernel.cpp, source/adapters/native_cpu/program.cpp, source/adapters/native_cpu/queue.cpp, source/adapters/native_cpu/queue.hpp
Some types in the Native CPU adapter didn't have correct reference counting semantics. This PR should fix it by providing correct implementations for the `retain` and `release` functions.
intel/llvm pull request: https://github.com/intel/llvm/pull/11947
=> [NATIVECPU] Implement correct reference counting for Native CPU adapter

source/adapters/hip/memory.cpp
`hipArray3DGetDescriptor` was introduced in HIP 5.6
=> [HIP] Ifdef entry point introduced in HIP 5.6

scripts/ctest_parser.py
Update the `scripts/ctest_parser.py` to work with the adapter branch changes.
=> [CTS] Update ctest_parser.py script

source/adapters/hip/context.cpp, source/adapters/hip/context.hpp, source/adapters/hip/device.hpp, source/adapters/hip/enqueue.cpp, source/adapters/hip/event.cpp, source/adapters/hip/event.hpp, source/adapters/hip/kernel.cpp, source/adapters/hip/kernel.hpp, source/adapters/hip/memory.cpp, source/adapters/hip/memory.hpp, source/adapters/hip/platform.cpp, source/adapters/hip/program.cpp, source/adapters/hip/program.hpp, source/adapters/hip/queue.cpp, source/adapters/hip/usm.cpp, source/ur/ur.hpp, test/adapters/hip/test_context.cpp, test/conformance/context/context_adapter_hip.match, test/conformance/memory/memory_adapter_hip.match
Moving https://github.com/intel/llvm/pull/11105 into UR repo with a few changes. Depends on https://github.com/oneapi-src/unified-runtime/pull/961
The getter func for ptrs/arrays/surfaces now allocates lazily if needed. This has made code a lot cleaner.
=> [HIP] Hip adapter multi dev ctx

include/ur_api.h, include/ur_print.hpp, scripts/YaML.md, scripts/core/enqueue.yml, scripts/parse_specs.py, scripts/templates/helper.py, source/adapters/hip/usm.cpp, source/adapters/null/ur_nullddi.cpp, source/adapters/opencl/enqueue.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/layers/validation/ur_validation_layer.cpp, source/loader/layers/validation/ur_validation_layer.hpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
This is accomplished with the various size queries for buffers, images and USM allocations. Since not all adapters have these queries implemented the bounds checking isn't entirely comprehensive on all platforms just yet.
Aims to address issues discussed in #926
=> Add bounds checking for enqueue operations to the validation layer.

source/adapters/hip/device.cpp
Needed for https://github.com/intel/llvm/pull/11626
=> Enable fp16 runtime support for hip

source/adapters/level_zero/device.cpp, source/adapters/level_zero/device.hpp, source/adapters/level_zero/program.cpp, source/adapters/level_zero/usm.cpp
Intel(R) GPUs have two modes of operation in terms of allocations:
Stateful and stateless mode.
Stateful optimizes memory accesses through pointer arithmetic.
This can be done as long as allocations used by the allocation
are smaller than 4GB.
Stateless disables such pointer-arithmetic optimization to
allow the kernel to use allocations larger than 4GB.
Currently, L0 adapter dynamically and automatically requests
the L0 driver large allocations if it detects an allocation size
is larger than 4GB. This creates a problem if a kernel has been
previously compiled for stateful access. This ultimately means
the adapter mixes stateful and stateless behavior, which is not
a user-friendly experience.
This patch aims at correcting this behavior by defining a default
one. On Intel(R) GPUs previous …
=> [UR][L0] Unify use of large allocation in L0 adapter

source/adapters/native_cpu/device.cpp
This should fix https://github.com/oneapi-src/unified-runtime/issues/1164 by using `static_cast` to silence warnings about values that are not yet part of the `ur_device_info_t` enum, similarly to what is done by the other adapters.
=> [NATIVECPU] Use static_cast in switch for ur_device_info_t

include/ur.py, include/ur_api.h, include/ur_print.hpp, scripts/core/registry.yml, scripts/core/usm.yml, source/adapters/opencl/usm.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/usm/usm_adapter_opencl.match
This is the equivalent ur_buffer_alloc_location_properties_t, it turns out the CL extension flag is applicable to both buffer creation and USM allocations.
Tested in https://github.com/intel/llvm/pull/12005
=> [OpenCL] Add ur_usm_alloc_location_desc struct and handle it in the CL adapter.

include/ur.py, include/ur_api.h, include/ur_print.hpp, scripts/core/EXP-BINDLESS-IMAGES.rst, scripts/core/exp-bindless-images.yml
This PR removes the additions from [!852](https://github.com/oneapi-src/unified-runtime/pull/852), which have been deemed unnecessary. Targeting `main` with this PR, as adapter changes were never implemented for the changes that this removes and no matching DPC++ PR should be necessary.
=> [Bindless][Exp] Layered Images Re-Work

source/adapters/level_zero/CMakeLists.txt
LLVM testing: https://github.com/intel/llvm/pull/11844
=> [UR][L0] Upgrade L0 loader to v1.15.1

source/adapters/cuda/command_buffer.cpp, source/adapters/cuda/command_buffer.hpp, source/adapters/cuda/device.cpp, source/adapters/cuda/event.cpp, source/adapters/cuda/event.hpp, source/adapters/cuda/image.cpp, source/adapters/cuda/memory.hpp, source/adapters/cuda/program.cpp, source/adapters/cuda/sampler.cpp, source/adapters/hip/device.hpp, source/adapters/hip/enqueue.cpp, source/adapters/hip/event.cpp, source/adapters/hip/event.hpp, source/adapters/hip/memory.hpp, source/adapters/hip/program.cpp, source/adapters/hip/sampler.cpp, source/adapters/opencl/program.cpp
LLVM PR https://github.com/intel/llvm/pull/12176
=> Fix coverity issues in OpenCL, cuda and hip adapters.

test/conformance/program/program_adapter_level_zero.match, test/conformance/program/program_adapter_opencl.match, test/conformance/program/urProgramCreateWithBinary.cpp, test/conformance/program/urProgramLink.cpp
We now no longer attempt to link two programs with duplicate definitions together (the SPIR-V dpc++ generates for us always contains a wrapper function with the same name and function signature)
We also now correctly query program binaries
=> CTS fixes for ProgramLink and ProgramCreateWithBinary

source/adapters/cuda/device.cpp, source/adapters/cuda/event.cpp, source/adapters/cuda/sampler.cpp, source/adapters/null/ur_null.cpp, source/common/ur_util.hpp
This should fix all non-test related coverity issues except for:
https://scan7.scan.coverity.com/reports.htm#v21214/p15954/fileInstanceId=155217701&defectInstanceId=19136875&mergedDefectId=1574236, which is a race in the HIP adapter - that looks like it might be a false positive, but I'm not sure.
=> [cuda][null][common] fix a few coverity issues

source/adapters/native_cpu/physical_mem.cpp, source/adapters/native_cpu/virtual_mem.cpp
The header does not exists for the Native CPU adapter.
=> [NATIVECPU] Remove event.hpp inclusion

source/common/ur_util.hpp, source/ur/ur.hpp
MSVC complains about it being insecure.
=> [common] remove the use of std::getenv from common code

.github/workflows/e2e_nightly.yml
=> [CI][OPENCL] adapt e2e workflow to opencl target

source/adapters/level_zero/usm.cpp, source/common/umf_pools/disjoint_pool_config_parser.cpp, source/common/umf_pools/disjoint_pool_config_parser.hpp
The disjoint_pool implementation distinguishes between a few different levels of logging (0-3). The argument should be an int, not bool.
=> Fix tracing param in disjoint_pool_parser

source/adapters/hip/common.hpp, source/adapters/hip/enqueue.cpp, source/adapters/hip/kernel.cpp, source/adapters/hip/usm.cpp
I see some unit test failures, but there were quite a lot of known issues with earlier ROCm versions too.
=> [HIP] Fix build with ROCm 6.0.0

scripts/core/EXP-COMMAND-BUFFER.rst, source/adapters/cuda/command_buffer.cpp, source/adapters/cuda/ur_interface_loader.cpp, source/adapters/hip/command_buffer.cpp, source/adapters/hip/ur_interface_loader.cpp, source/adapters/level_zero/command_buffer.cpp, source/adapters/level_zero/ur_interface_loader.cpp, source/adapters/opencl/command_buffer.cpp, source/adapters/opencl/ur_interface_loader.cpp
Note: This PR also includes changes from the `main` branch (commit 40a6846ec8c65f3ee3ee3fee97ea4c27859ef193) which add these commands to the UR specification, but are not present in the adapter branch yet.
- Adds implementation of command-buffer fill commands for the L0 adapter.
- Includes stubs for the CUDA and HIP adapters.
=> [EXP][CMDBUF] Implement Fill commands for L0 adapter

source/adapters/hip/CMakeLists.txt, source/adapters/hip/common.hpp, source/adapters/hip/program.cpp
The code object finalization for kernel fusion uses the AMD COMGR. The location of the corresponding header changed between ROCm version 4 and 5.
This PR fixes the include for ROCm version 4.
=> [UR][HIP] Fix include for AMD COMGR

source/adapters/hip/enqueue.cpp
Adds initial implementation for mem_advise to the HIP adapter.
=> [SYCL][HIP] Implement mem_advise for HIP

source/adapters/level_zero/platform.cpp
IGC only accepts three values for -ze-opt-level, 0, 1 and 2, however dpcpp has at least four options, O0, O1, O2 and O3.
Right now we decided to map O1 and O2 to -ze-opt-level=1, but we have determined that this is not the best for user experience and may defy user expectation, and actually produces worse code than specifying nothing because IGC uses ze-opt-level=2 if nothing is specified.
https://github.com/intel/llvm/pull/12023
=> [UR][L0] Make urPlatformGetBackendOption return -ze-opt-level=2 for -O1 and -O2

source/adapters/hip/CMakeLists.txt
ROCm installations prior to v6 don't respect the traditional installation layout and install the HSA headers to `$PREFIX/hsa/include/hsa` whereas in rocm6 it looks like they're putting it in the right place at `$PREFIX/include/hsa`.
That cleanup from AMD is good news, but it means that our workarounds now break and we need to check both places.
=> [hip] Fix HSA headers lookup

README.md, source/adapters/hip/CMakeLists.txt
Allow custom location of HIP/HSA include and HIP library directories using the following CMake variables:
* `UR_HIP_INCLUDE_DIR`,
* `UR_HIP_HSA_INCLUDE_DIR`,
* `UR_HIP_LIB_DIR`.
=> [HIP] Allow custom location of ROCm components

source/adapters/opencl/CMakeLists.txt
Fixes #1171 by replacing an explicit Linux path used as the value for the internal `OpenCLICDLoaderLibrary` CMake varaible and replacing it with the `OpenCL::OpenCL` target name. This is an target alias provided by the https://github.com/KhronosGroup/OpenCL-ICD-Loader.
=> [CL] Fix Windows CMake, remove explicit Linux path

source/adapters/hip/memory.cpp
Different compilers can change the linkage of symbols based on whether `inline` is used. This removes the `inline` specifier so it has external linkage and can be called from within another TU.
=> [HIP] Remove inline from helper

source/adapters/hip/enqueue.cpp, source/adapters/hip/program.cpp, source/adapters/hip/program.hpp
https://github.com/intel/llvm/pull/12165
=> [HIP] Add support for global variable read write

.github/docker/ubuntu-22.04.Dockerfile, .github/workflows/hadolint.yml
=> [CI] Add Dockerfiles linter - hadolint

source/adapters/level_zero/device.cpp, source/adapters/level_zero/device.hpp, source/adapters/level_zero/program.cpp, source/adapters/level_zero/usm.cpp
- Change the defaults from always allowing > 4GB allocations to making the user have to request > 4GB allocation support given the max allocation allowed on that system is less than 4GB.
- This ensures performance is maintained on systems that dont handle > 4GB allocations natively and avoids breaking Ahead of Time (AOT) binaries that were built without > 4GB resource support.
- By setting UR_L0_ENABLE_RELAXED_ALLOCATION_LIMITS=1 , the L0 Adapter will force the modules to be built with stateless or > 4GB support and will allow for the allocations to exceed the max single allocation size limit for that device.
=> [L0] Only Override max allocation limits given env

source/common/CMakeLists.txt, source/common/ur_lib_loader.hpp, source/common/ur_util.cpp, source/common/ur_util.hpp, source/loader/layers/validation/backtrace_win.cpp
Avoid transitively including Windows.h in headers which include ur_util.hpp.
=> [Common] Don't include Windows.h in ur_util.hpp

source/adapters/level_zero/event.cpp
L0 adapter makes optimizations based on whether an event has any external references. The adapter keeps track of this based on a reference count. This reference count wasn't being properly set when first creating an event based on a native handle, leading to code incorrectly assuming that the event was internal and had no external references, which ultimately led to segfaults.
This patch sets the refcount to 1 when first creating an event, solving the problem. It also adds a missing null-check to make user native handle events even work.
=> [L0] fix waiting on non-owned native handle events

scripts/generate_docs.py
`subprocess.run` returns [CompletedProcess][1]. When used in conjunction with `subprocess.PIPE` for `stderr` or `stdout` it also has a corresponding string or bytes parameter. They are not file-like objects as in the case of `subprocess.Popen` which supports streaming pipes.
[1]: https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess.stderr
=> [gen] subprocess.run result pipes are not files

source/adapters/cuda/CMakeLists.txt, source/adapters/cuda/adapter.cpp, source/adapters/cuda/tracing.cpp, source/adapters/cuda/tracing.hpp, source/common/ur_lib_loader.hpp
With these changes, `libcupti.so` is loaded dynamically when CUDA tracing is enabled. This enables XPTI tracing-enabled builds to work on systems that do not have `libcupti.so` or where that library cannot be located on the system.
The `enableCUDATracing` and `disableCUDATracing` functions have been changed to take a context pointer, rather than use global variables for tracing state.
There is a temporary `enableCUDATracing` variant with no parameter for compatibility until the relevant changes have been merged to https://github.com/intel/llvm.
=> [CUDA] Dynamically load the CUPTI library when tracing

source/adapters/opencl/context.cpp, source/adapters/opencl/sampler.cpp, test/conformance/context/urContextCreateWithNativeHandle.cpp, test/conformance/enqueue/urEnqueueEventsWait.cpp, test/conformance/enqueue/urEnqueueEventsWaitWithBarrier.cpp, test/conformance/enqueue/urEnqueueKernelLaunch.cpp, test/conformance/enqueue/urEnqueueMemBufferCopy.cpp, test/conformance/enqueue/urEnqueueMemBufferCopyRect.cpp, test/conformance/enqueue/urEnqueueMemBufferFill.cpp, test/conformance/enqueue/urEnqueueMemBufferMap.cpp, test/conformance/enqueue/urEnqueueMemBufferRead.cpp, test/conformance/enqueue/urEnqueueMemBufferReadRect.cpp, test/conformance/enqueue/urEnqueueMemBufferWrite.cpp, test/conformance/enqueue/urEnqueueMemBufferWriteRect.cpp, test/conformance/enqueue/urEnqueueMemImageCopy.cpp, test/conformance/enqueue/urEnqueueMemImageRead.cpp, test/conformance/enqueue/urEnqueueMemImageWrite.cpp, test/conformance/enqueue/urEnqueueMemUnmap.cpp, test/conformance/enqueue/urEnqueueReadHostPipe.cpp, test/conformance/enqueue/urEnqueueUSMPrefetch.cpp, test/conformance/enqueue/urEnqueueWriteHostPipe.cpp, test/conformance/memory/urMemBufferPartition.cpp, test/conformance/queue/urQueueFinish.cpp, test/conformance/queue/urQueueFlush.cpp, test/conformance/sampler/urSamplerCreateWithNativeHandle.cpp, test/conformance/usm/urUSMFree.cpp
This PR fixes some of missing release calls that could cause memory leak, in particular:
* Add `urEventRelease` to release event handle created from enqueue calls.
* Release the Context and Sampler handles that was created from native handles in `CreateWithNativeHandle` tests.
* Release Mem buffer that was created from partitioning a memory.
[Intel/llvm testing](https://github.com/intel/llvm/pull/12465)
=> Fix memory leak in UR CTS tests

test/conformance/device/urDeviceRelease.cpp, test/conformance/device/urDeviceRetain.cpp
Device CTS tests for testing subdevices would leak memory as they are retaining a subdevice then releasing it only one time, but they should release it twice to clear the memory as the created sub-device already have a refCount of 1 after they are created.
=> Fix device CTS tests for retain/release

source/adapters/native_cpu/enqueue.cpp, source/adapters/native_cpu/nativecpu_state.hpp
intel/llvm PR: https://github.com/intel/llvm/pull/11614
With https://github.com/intel/llvm/pull/11614 we start integrating the [oneAPI Construction Kit](https://github.com/codeplaysoftware/oneapi-construction-kit). If the OCK is enabled, it creates the work item loops in the compiler, so it is not necessary to execute the loops in the adapter.
=> [NATIVECPU] Handle oneAPI Construction Kit integration in runtime

source/adapters/native_cpu/command_buffer.cpp
Adds empty implementations for `urCommandBufferAppendMemBufferFillExp` and `urCommandBufferAppendUSMFillExp` on Native CPU.
intel/llvm PR: https://github.com/intel/llvm/pull/12379
=> [NATIVECPU] Empty implementation for command buffer fill

test/conformance/device_code/CMakeLists.txt, test/conformance/device_code/usm_ll.cpp, test/conformance/enqueue/enqueue_adapter_opencl.match, test/conformance/enqueue/helpers.h, test/conformance/enqueue/urEnqueueKernelLaunch.cpp, test/conformance/enqueue/urEnqueueUSMMemcpy2D.cpp, test/conformance/testing/include/uur/fixtures.h, test/conformance/testing/include/uur/utils.h, test/conformance/testing/source/utils.cpp
* Expand USMMemcpy2D testing to test all USM allocation types
* Add USM linked list kernel execution test
The linked list test is based on USM/smemll.cpp from the SYCL-E2E tests and checks that USM allocations are actually usable from a kernel.
=> [CTS] Add more USM testing

test/adapters/cuda/context_tests.cpp, test/adapters/cuda/kernel_tests.cpp, test/adapters/cuda/memory_tests.cpp, test/adapters/cuda/urEventCreateWithNativeHandle.cpp, test/adapters/cuda/urEventGetNativeHandle.cpp, test/adapters/hip/test_context.cpp, test/adapters/hip/urEventGetNativeHandle.cpp, test/conformance/context/urContextCreate.cpp, test/conformance/context/urContextSetExtendedDeleter.cpp, test/conformance/event/urEventCreateWithNativeHandle.cpp, test/conformance/memory/urMemBufferCreate.cpp, test/conformance/memory/urMemBufferPartition.cpp, test/conformance/queue/urQueueFinish.cpp, test/conformance/queue/urQueueFlush.cpp, test/conformance/sampler/urSamplerCreate.cpp, test/conformance/testing/include/uur/raii.h, test/conformance/virtual_memory/urPhysicalMemCreate.cpp, test/layers/tracing/codeloc.cpp
This patch introduces the `uur::raii::Wrapper<T>` object and per handle
aliases (`uur::raii::Context` for `ur_context_handle_t` etc.) to replace
instances of the following pattern in test bodies:
```cpp
TEST(Context, Example) {
ur_context_handle_t context = nullptr;
ASSERT_SUCCESS(urContextCreate(1, &device, nullptr, &context));
// potential resource leak as `ASSERT_*` returns from this function
ASSERT_TRUE(might_be_false);
urContextRelease(context);
}
```
With the following:
```cpp
TEST(Context, Example) {
uur::raii::Context context = nullptr;
ASSERT_SUCCESS(urContextCreate(1, &device, nullptr, context.ptr()));
// no leak because the destructor releases the context
ASSERT_TRUE(might_be_false);
}
```
=> [CTS] Fix resource leaks

include/ur_api.h, include/ur_ddi.h, include/ur_print.hpp, scripts/core/memory.yml, source/adapters/cuda/memory.cpp, source/adapters/hip/memory.cpp, source/adapters/level_zero/memory.cpp, source/adapters/native_cpu/memory.cpp, source/adapters/null/ur_nullddi.cpp, source/adapters/opencl/memory.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/memory/memory_adapter_hip.match, test/conformance/memory/urMemBufferCreateWithNativeHandle.cpp, test/conformance/memory/urMemGetNativeHandle.cpp, test/conformance/memory/urMemImageCreateWithNativeHandle.cpp
Add an extra param to `urMemGetNativeHandle` as suggested here https://github.com/oneapi-src/unified-runtime/pull/1199#discussion_r1440464125
=> [UR] Add extra param to urMemGetNativeHandle

.github/workflows/bandit.yml, .github/workflows/cmake.yml, .github/workflows/codeql.yml, .github/workflows/coverage.yml, .github/workflows/coverity.yml, .github/workflows/docs.yml, .github/workflows/nightly.yml, .github/workflows/prerelease.yml, .github/workflows/scorecard.yml
Silence warnings about using outdated version of Node.js due to using actions/checkout@v3.6.0.
=> [GHA] Bump actions/checkout to v4.1.1

source/adapters/opencl/program.cpp
If an OpenCL driver returns `CL_PROGRAM_BINARY_TYPE_INTERMEDIATE` (defined in the `cl_khr_spir` extension to enable SPIR 1.2 not SPIR-V) when querying `CL_PROGRAM_BINARY_TYPE` we should handle this gracefully. This patch maps the `CL_PROGRAM_BINARY_TYPE_INTERMEDIATE` to `UR_PROGRAM_BINARY_TYPE_NONE`. From the users perspective these are semantically equivalent as they both require compilation before the program can be used to create a kernel.
=> [CL] Handle INTERMEDIATE binary type

test/adapters/cuda/kernel_tests.cpp
Replace uses of `sizeof(const char*)` with `std::strlen(const char*)` in CUDA adapter specific kernel tests.
=> [CUDA] Fix sizeof(const char*) usage

scripts/core/CONTRIB.rst
These changes to the *Adapter Change Process* aim to bring the process up to date with current practice by describing how the *ready to merge* label is being used and also to move the undrafting of *intel/llvm* pull requests earlier in the process to garner approvals from code-reviewers sooner to alleviate a bottleneck in the merge pipeline.
=> [Docs] Update the Adapter Change Process

include/ur_print.h, scripts/generate_docs.py, scripts/templates/api_listing.mako, scripts/templates/print.cpp.mako, scripts/templates/print.h.mako, scripts/templates/print_helper.py, scripts/util.py, source/loader/ur_print.cpp
Generate HTML documentation for printing C API.
[preview](https://patkamin.github.io/unified-runtime/core/api.html#print)
=> [docs] Printing C API html docs

source/adapters/hip/usm.cpp
In ROCm 5.7.1 some USM allocations are reported as managed, these are freed in the same way as device allocations.
Testing in https://github.com/intel/llvm/pull/12380
=> [HIP] Support managed allocations in USM free

include/ur_api.h, include/ur_ddi.h, include/ur_print.h, include/ur_print.hpp, scripts/core/common.yml
Make queue handle a part of queue class. It's required by https://github.com/oneapi-src/unified-runtime/pull/1121 to correctly track the queue object handles.
=> [SPEC] Fix queue handle class

test/CMakeLists.txt, test/adapters/CMakeLists.txt, test/conformance/CMakeLists.txt, test/conformance/README.md
Some tests don't work on supermicro machine:
https://github.com/oneapi-src/unified-runtime/actions/runs/7559294673/job/20587325535
This PR fixes it.
=> Fix counting variables for CTS

source/adapters/cuda/image.cpp
This PR fixes 1D copies that uses USM pointers.
corresponding PR in https://github.com/intel/llvm/pull/12342 only for CI
=> [Bindless][exp] 1D Image copy fix

source/adapters/cuda/usm_p2p.cpp
Use camelCase naming convention.
This makes the naming convention consistent with the switch to camelCase in other files.
=> [CUDA] Use camelCase always (applied to usm_p2p.cpp).

.github/workflows/cmake.yml, source/adapters/level_zero/adapter.cpp, source/adapters/level_zero/adapter.hpp, source/adapters/level_zero/device.cpp, source/adapters/level_zero/platform.cpp, source/ur/ur.cpp, source/ur/ur.hpp
The platform cache is a global variable used exclusively by the L0 adapter, and it's protected by a loosely-associated spin lock. However, its destruction is associated with the lifetime of the adapter structure and is deleted the first time adapter refcount reaches 0. This was causing issues whenever the adapter was initialized and destroyed multiple time inside of a single process, which, for example, happens during tests.
This patch fixes the above problem by moving the platform cache from the global state into the adapter structure. This allows for a simpler implementation that no longer requires an explicit lock and instead uses lazy loading (std::call_once).
With this patch, all platform tests are now passing for L0. Closes #824
=> [L0] move platform cache into the adapter structure

source/adapters/level_zero/adapter.cpp, source/adapters/level_zero/adapter.hpp, source/adapters/level_zero/platform.cpp
This restores the old behavior where urAdapterGet was essentially a noop. Hopefully fixes the issue on intel/llvm (https://github.com/intel/llvm/pull/12658).
=> [L0] move adapter init into its constructor from urAdapterGet

source/adapters/level_zero/queue.cpp
- During UR Queue Release the command lists and command queue resources need to be reset and cleared regardless of the results from the execution of OpenCommandList.
- This prevents a Queue object from being left with invalid command lists and an invalid command queue internal handle that should have been cleared at release during high memory usage.
- Reset the command list upon execution failure and make the command list available to avoid keeping invalid command lists in the queue after failures before queue release.
=> [L0] Cleanup Queue at Release unconditionally and reset command list after failure

test/adapters/cuda/context_tests.cpp, test/adapters/cuda/urEventCreateWithNativeHandle.cpp
Fix issues missed by #1284:
* Use RAII wrapper for CUevent in `urCudaEventCreateWithNativeHandleTest.Success`.
* Use `uur::raii::Mem` in the `cudaUrContextCreateTest.ContextLifetimeExisting`.
=> [CUDA] Fix resource leaks in adapter tests

.github/workflows/cmake.yml, CMakeLists.txt, source/adapters/level_zero/adapter.cpp, source/adapters/level_zero/adapter.hpp, source/adapters/level_zero/command_buffer.cpp, source/adapters/level_zero/context.cpp, source/adapters/level_zero/context.hpp, source/adapters/level_zero/device.cpp, source/adapters/level_zero/event.cpp, source/adapters/level_zero/event.hpp, source/adapters/level_zero/kernel.cpp, source/adapters/level_zero/memory.cpp, source/adapters/level_zero/platform.cpp, source/adapters/level_zero/queue.cpp, source/adapters/level_zero/queue.hpp, source/ur/ur.cpp, source/ur/ur.hpp, test/conformance/platform/platform_adapter_level_zero.match
=> Candidate for the v0.8.7 release tag

source/adapters/CMakeLists.txt
Previously it was used to fetch adapters from llvm repo.
=> [Adapters] Remove redundant variable in CMake

source/common/logger/ur_logger.hpp, source/common/logger/ur_logger_details.hpp, source/common/logger/ur_sinks.hpp
Switching to the new logger changes API and log format, and requires changes in user code. To make the transition easier, this PR adds an option to the new logger that's print logs in the old format.
=> Add Legacy compatibility to Logger

.github/workflows/cmake.yml, .github/workflows/codeql.yml, .github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/scorecard.yml
There is a bunch of warnings related to deprecated Node.js 16 usage of some of the Github Actions used in CI that look like this:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20:
actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8,
github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
This PR bumps the versions of actions causing these warnings to appear to the newest ones.
=> [CI] Fix Node.js 16 CI warnings

source/adapters/level_zero/common.hpp
The file common.hpp contains two definitions of the UR_CALL macro, which only works because both definitions are exactly the same. This commit removes the second one.
=> Remove duplicate UR_CALL definition from common.hpp

source/common/CMakeLists.txt
Before https://github.com/oneapi-src/unified-runtime/pull/1216 adapters linked with disjoint_pool library that linked with Threads library.
PR #1216 replace disjoint_pool with a version from UMF library that does not link with Threads lib explicitly which leads to compilation error on xmain. Fix this by explicitly adding adding Threads to ur_common. 
Use the same logic as in https://github.com/oneapi-src/unified-runtime/blob/f15234d0b0932f7f1f5b0188b99c6d257ce2e5dd/source/common/umf_pools/CMakeLists.txt#L17
=> [UR] Add missing Threads library to common

source/adapters/opencl/memory.cpp
This should have been mapped to CL_MEM_ALLOC_BUFFER_LOCATION_INTEL.
=> Correct mapping of BUFFER_ALLOC_LOCATION_PROPERITES in CL adapter.

source/loader/layers/sanitizer/asan_interceptor.cpp, source/loader/layers/sanitizer/common.hpp, source/loader/layers/sanitizer/linux/san_utils.cpp
Try to demangle the kernel name in error reporting to improve user experience.
=> [DeviceSanitizerLayer] Demangle the kernel name in error reporting

source/adapters/level_zero/context.cpp, source/adapters/level_zero/context.hpp, source/adapters/level_zero/queue.cpp, source/adapters/level_zero/queue.hpp
- fix to address a multi device crash given many devices causing a stack overflow. Event Caches per device are now explicitly allocated.
=> [L0] Fix the multi device event cache to allocate lists as pointers

scripts/core/CONTRIB.rst
The original command does not run at all. I think `-B` is missing. Adding it in this PR.
=> [Docs] Adding a missing arg to example cmake command.

source/loader/layers/sanitizer/asan_interceptor.cpp, source/loader/layers/sanitizer/asan_interceptor.hpp, source/loader/layers/sanitizer/device_sanitizer_report.hpp, source/loader/layers/sanitizer/ur_sanddi.cpp
*Fix event lists are not correctly passed to KernelLaunch
intel/llvm PR: https://github.com/intel/llvm/pull/12753
=> [DeviceSanitizer] Support detecting out-of-bounds error on DeviceGlobals

source/adapters/hip/command_buffer.cpp, source/adapters/hip/command_buffer.hpp, source/adapters/hip/device.cpp, source/adapters/hip/enqueue.cpp, source/adapters/hip/enqueue.hpp, test/conformance/exp_command_buffer/buffer_fill_kernel_update.cpp, test/conformance/exp_command_buffer/buffer_saxpy_kernel_update.cpp, test/conformance/exp_command_buffer/fixtures.h
- command buffer functions for HIP.
- Some additional methods and refactoring to reuse existing adapter code.
(This code was mainly written by Andrey Alekseenko @al42and) 
Co-authored-by: Andrey Alekseenko andrey.alekseenko@scilifelab.se
=> [EXP][CMDBUF] HIP adapter support for command buffers

scripts/core/CONTRIB.rst
Fixes #1292
// Preview on my fork: https://lukaszstolarczuk.github.io/unified-runtime/core/CONTRIB.html#forks-and-pull-requests
=> CONTRIB: add info about workflows on forks

tools/urinfo/utils.hpp
We were putting null-terminated strings to std::string data, which made the terminator part of the string content.
=> [urinfo] Fix stray NULLs in stdout

source/adapters/level_zero/CMakeLists.txt, source/adapters/level_zero/device.cpp, source/adapters/level_zero/image.cpp, source/adapters/level_zero/image.hpp, source/adapters/level_zero/memory.cpp, source/adapters/level_zero/memory.hpp
Function zeMemGetPitchFor2dImage and zeImageGetDeviceOffsetExp from
L0 extension ZE_experimental_bindless_image are used.
In urBindlessImagesUnsampledImageCreateExp, if image description is
different from that of image allocated by urBindlessImagesImageAllocateExp,
an image view is created from the image.
=> [UR][L0] Implement bindless image functions from ZE_experimental_bindless_image

cmake/match.py
d6930c70bd7 introduced `Status.INPUT_END` but didn't introduce the means to handle that eventuality. It looks like the intention might have been to exit with success if we've got to the end of input. However, if we run out of input and still have matches pending, I'm treating this as a failure.
Infinite loop reproducer:
[_matchtmpfile.txt](https://github.com/oneapi-src/unified-runtime/files/14438706/_matchtmpfile.txt)
[input.txt](https://github.com/oneapi-src/unified-runtime/files/14438708/input.txt)
=> [test] Fix infinite loop when we run out of input

scripts/YaML.md
Fixes #1381 by adding a paragraph defining that etor/etors are abbreviations for enumerator/enumerators.
=> [Doc] Define the etor/etors abbreviations

include/ur_api.h, scripts/core/program.yml
Fixes #1384 by clarifying what the *list of devices associated with a program* means when the program is created in various ways.
=> [SPEC] Clarify the UR_PROGRAM_INFO_DEVICES query

.github/workflows/e2e_core.yml
Added missing skip for HW-related (E2E) jobs. They will always fail on forks without this `if`.
=> [CI] Skip E2E tests on forks

scripts/ctest_parser.py
The conformance tests skip tests when a devices returns `UR_RESULT_ERROR_UNSUPPORTED_FEATURE` and the feature under test is optional. As such, skipped tests count as passes because the device has exhibiting valid behaviour. This patch changes how CTS pass rates are calculated to match.
=> [CTS] Treat skipped tests as passes

CMakeLists.txt
I can't think of a valid reason not to generate compile_commands.json and several reasons why we should
1. I don't like typing configure options that much.
2. I like editor completion to work without me having to regenerate my build.
3. It's a good way to inspect final build flags without having to query the build system.
=> [cmake] Always generate compile_commands.json

source/adapters/cuda/command_buffer.cpp, source/adapters/cuda/command_buffer.hpp, source/adapters/hip/command_buffer.cpp, source/adapters/hip/command_buffer.hpp
Address issues in the CUDA adapter code added by https://github.com/oneapi-src/unified-runtime/pull/1089 which have been flagged by Coverity.
* Uninitialized struct member of `CUDA_KERNEL_NODE_PARAMS` struct
* copying instead of moving a shared pointer to a node when constructing a command-handle.
As well as issues flagged by coverity in the HIP adapter code added in https://github.com/oneapi-src/unified-runtime/pull/1254
* Initialize `NextSyncPoint`
* Move rather than copy node shared-pointers during sync-point registration
* Don't throw exceptions from a class destructor 
DPC++ PR https://github.com/intel/llvm/pull/12723
=> [HIP][CUDA][Command-Buffer] Fix Coverity issues in HIP/CUDA command-buffer code

source/adapters/cuda/command_buffer.cpp
- Default initialize CUDA_KERNEL_NODE_PARAMS which prevents errors from trying to set data members which are not present before version 12.0
DPC++ PR https://github.com/intel/llvm/pull/12989
=> [CUDA] Fix build issue with version < 12.0

source/adapters/level_zero/image.cpp
Tested in https://github.com/intel/llvm/pull/12965
=> [Coverity][L0] Remove overlapping mem copy in urBindlessImagesSampledImageCreateExp

source/loader/ur_lib.cpp, tools/urinfo/urinfo.cpp
Now that #740 is merged, actually use `urDeviceGetSelected` in the `urinfo` tool to mirror the behaviour of the `sycl-ls` tool.
=> [urinfo] Use urDeviceGetSelected

source/adapters/level_zero/device.cpp, source/adapters/level_zero/device.hpp, source/adapters/level_zero/event.cpp, source/adapters/level_zero/kernel.cpp, source/adapters/level_zero/queue.cpp
Have URT utilize L0 driver native implementation as opposed to L0 URT adapter implementation to ensure in-order semantics when creating inOrderQueues. 
Verified working with SYCL e2e in-order queue related tests locally, both with adapter implementation and L0 driver native implementation. One sample that tested it well:
```
-- Testing: 1 tests, 1 workers --
PASS: SYCL :: Basic/in_order_queue_status.cpp (1 of 1)
Testing Time: 6.93s
Total Discovered Tests: 1
Passed: 1 (100.00%)
```
LLVM Draft with all CI / SYCL e2e for this commit passing at: https://github.com/intel/llvm/pull/12833
=> [L0] Add support for in-order lists using L0 driver

source/adapters/cuda/image.cpp
Extends the CUDA adapter to allow for mipmap interop with bindless images
Corresponding DPC++ PR: https://github.com/intel/llvm/pull/12736
=> [Bindless][CUDA] Mipmap interop

source/adapters/level_zero/command_buffer.cpp, source/adapters/level_zero/command_buffer.hpp
Create a new command-list to reset all the events of the enqueued graph cmd. This allows us to move the enqueueing of reset commands from the command-buffer enqueue function to the finalize function, and allow us to perform this task only once. 
Move signal event reset from main cmd-list to reset cmd-list. 
Move the documentation to DPC++ design doc.
=> [EXP][CMDBUF] Move event reset commands to dedicated cmd-list

source/adapters/cuda/command_buffer.cpp
Adjustment of value pointer size according to pattern size. 
Large patterns are now broken into 1-byte chunks, as in the regular implementation.
=> [EXP][CMDBUF] Improve CUDA Fill op implementation

CMakeLists.txt, source/adapters/CMakeLists.txt
Allow the configuration of external source directory for any of the existing adapters. This is done via a CMake cache variable which if set will is used as the `source_dir` argument to `add_subdirectory()`, the `binary_dir` argument will also be set to the same location as a normal in-tree build. This is done via the addition of the new `add_ur_adapter_subdirectory()` helper function which also hoists the logic to enable/disable each adapter.
=> [CMake] Support external adapter source dirs

source/adapters/cuda/event.cpp, source/adapters/hip/event.cpp
There is no reason to not allow waits from native hip/cuda events in different sycl "contexts".
Even the sycl spec does not mandate such a thing. This constraint does not appear to be applied in L0 backend.
This also fixes scopedContext to set the per device (CU/HIP)context.
This is a fix for https://github.com/intel/llvm/issues/6749#issuecomment-1971875971
=> [cuda][hip] Removed bad event wait constraint / use scopedContext correctly.

.github/workflows/scorecard.yml
bump versions of actions in Scorecard workflow to fix it.
plus, a little cleanup in the workflow
// run in CI before:
https://github.com/oneapi-src/unified-runtime/actions/runs/8382714460/job/22957015241#step:4:1172
// run after (on my fork's main):
https://github.com/lukaszstolarczuk/unified-runtime/actions/runs/8388727658/job/22973510395#step:4:2151
=> Fix scorecard

source/adapters/level_zero/event.cpp
L0, when creating a list of events to wait on, in some cases was first grabbing a lock on a potentially completed event, and then tried to get a command list, which sometimes needs to cleanup all completed events. This caused a deadlock.
This patch moves getting a command list to before the event lock. But because the lock is required to decide whether this command list actually needed, we might be wasting time here.
=> [L0] fix a deadlock on a recursive event rwlock

.github/workflows/cmake.yml, .github/workflows/nightly.yml
Reverts oneapi-src/unified-runtime#1438
The runner issue is now fixed. Closes #1435.
=> Revert "Disable fuzz tests on ubuntu-22.04 runner"

source/adapters/cuda/device.hpp, source/adapters/cuda/enqueue.cpp, source/adapters/cuda/kernel.cpp, source/adapters/cuda/platform.cpp
Some logic for device initialization was split across platform init and device init. This duplicated some calls to get info for max block dim in Y and Z dimension. This rectifies that and makes sure the max block dims are only queried once, which is called from the device constructor.
=> [CUDA] Refactor device initialization

test/conformance/enqueue/helpers.h, test/conformance/enqueue/urEnqueueUSMMemcpy2D.cpp, test/conformance/testing/include/uur/utils.h, test/conformance/testing/source/utils.cpp
The `USMKind` and `USMKindToString` helper function is no longer needed as `ur_usm_type_t` can be used directly.
=> [CTS] Remove USMKind struct and replace usage with ur_usm_type_t in CTS tests

source/adapters/cuda/enqueue.hpp, source/adapters/hip/enqueue.hpp
These func prototypes are not needed as funcs are defined in enqueue.cpp before they are used. Addresses https://github.com/oneapi-src/unified-runtime/pull/1326#issuecomment-2008707282
=> [HIP][CUDA] Remove function prototypes from enqueue.hpp

source/adapters/opencl/device.cpp
This patch implements a workaround for the Intel FPGA driver which is currently an OpenCL 1.2 device which also supports `UR_MEMORY_SCOPE_CAPABILITY_FLAG_DEVICE` rather than the baseline for OpenCL 1.2 devices.
The workaround unconditionally queries for `CL_DEVICE_ATOMIC_FENCE_CAPABILITIES`, if it is successful the value is used. Otherwise the error code is ignored and the baseline capabilities are returned.
=> [CL] Atomic fence scope capability for Intel FPGA driver

scripts/verify_license.py
limit of 300 was preventing https://github.com/oneapi-src/unified-runtime/pull/1401 from passing the license verification test.
=> increase search characters limit for license verification

include/ur_api.h, include/ur_print.h, include/ur_print.hpp, scripts/core/EXP-BINDLESS-IMAGES.rst, scripts/core/exp-bindless-images.yml, source/adapters/cuda/device.cpp, source/adapters/cuda/image.cpp, source/adapters/cuda/sampler.cpp, source/adapters/cuda/sampler.hpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/loader/ur_print.cpp, source/ur_api.cpp, tools/urinfo/urinfo.hpp
Add enum to ur_mem_type_t to represent cubemap image type
Add device aspects for cubemap support:
- UR_DEVICE_INFO_CUBEMAP_SUPPORT_EXP
- UR_DEVICE_INFO_CUBEMAP_SEAMLESS_FILTERING_SUPPORT_EXP
Add structs/enums for cubemap sampling:
- ur_exp_sampler_cubemap_properties_t struct to enable seamless filtering between cubemap faces
- ur_exp_sampler_cubemap_filter_mode_t enum to enable distinguishing between cubemap seamless filtering options
Corresponding DPC++ PR: https://github.com/intel/llvm/pull/12996
=> [Bindless][CUDA] Add support for cubemaps

test/conformance/testing/include/uur/raii.h
It's only to silence errors, found on gcc in Ubuntu 20.04: `error: extra ';' [-Werror=pedantic]`
// ref: https://github.com/lukaszstolarczuk/unified-runtime/actions/runs/7845968200/job/21411580574#step:4:274
=> Remove redundant semicolons

test/conformance/usm/helpers.h
Fixes Coverity warnings 1584973 and 1584972.
=> [CTS] Fix Coverity warning: Add a & before auto so object is not copied unnecessarily

source/adapters/opencl/memory.cpp
This commit reverts the urMemBufferCreate changes for returning function lookup error in https://github.com/oneapi-src/unified-runtime/pull/1448 as the function had a fallback path which is no longer taken.
=> [OpenCL] Revert urMemBufferCreate extension function lookup error

source/adapters/hip/enqueue.cpp, source/adapters/hip/usm.cpp
This PR fixes detection of the pointer type for sycl pointer allocation info queries and USM copy2D for the HIP backend.
With regards to `urUSMGetMemAllocInfo` for `UR_USM_ALLOC_INFO_TYPE`:
Takes extra care identifying unknown/unregistered memory allocations since ROCm 6.0.0 introduces `hipMemoryTypeUnregistered`, which we now use to identify system allocations and the attributes query will still return success in this case.
With regards to `urEnqueueUSMMemcpy2D`:
This is a little awkward workaround. Ideally we'd just use `hipPointerGetAttribute` but it crashes when used on system / pageable host memory hence using `hipPointerGetAttributes` to first determine that and ideally use the memory type value. From ROCm 5.7.1 we cannot rely on the memory type member of the attributes struct to …
=> [HIP] Fix memory type detection in allocation info queries and USM copy2D

.github/labeler.yml, .github/workflows/labeler.yml
This workflow uses the [labeler](https://github.com/marketplace/actions/labeler) action to automatically add relevant labels to pull requests in order to make it easier to filter pull requests based on the files they make changes to.
Due to `pull_request_target` using the config from the base branch, this will need to be merged before it can be validated as working as stated in the [docs](https://github.com/marketplace/actions/labeler#notes-regarding-pull_request_target-event).
=> [GHA] Add "Pull Request Labeler" workflow

source/adapters/cuda/device.hpp
The SYCL specifiction inherits an OpenCL query for the maximum single allocaton that can be made, and requires that at least one-quarter of the device's reported global memory size can be allocated.
CUDA doesn't really have such a limitation as far as I can tell, and will happily allocate anything up to the total size of global memory in one go. This means returning that size is a reasonable guess for MaxAllocSize.
=> Return device total global memory for MaxAllocSize

.github/workflows/cmake.yml
This is for having more info about short fuzz tests failures while trying to fix #1435 .
It should be also nice to have a verbose output for future failure cases.
=> [CI] Update short fuzztest to include verbose output in CI

source/adapters/level_zero/context.cpp, source/adapters/level_zero/context.hpp, source/adapters/level_zero/queue.cpp, source/adapters/level_zero/queue.hpp
- Fix command lists cache usage such that given an inorder queue and in order lists is requested, then only in order lists can be used from the cache.
=> [L0] Fix regular in order command list reuse given inorder queue

source/adapters/cuda/enqueue.cpp, source/adapters/cuda/memory.hpp, test/conformance/enqueue/enqueue_adapter_cuda.match, test/conformance/enqueue/urEnqueueMemBufferMap.cpp
The CUDA adapter currently does not support multiple active mappings on the same buffer when using urEnqueueMemBufferMap. This change aims to add support for that feature.
However, the unsupported scenario of overlapping maps that were both created with the `UR_MAP_FLAG_WRITE` is not currently being checked. That's better done using validation layers for which I have created an issue:  https://github.com/oneapi-src/unified-runtime/issues/1221
intel/llvm: https://github.com/intel/llvm/pull/12285
=> [CUDA] Add support for multiple active mappings

source/adapters/opencl/event.cpp
This PR removes the workaround introduced in https://github.com/intel/llvm/pull/9944
intel/llvm: https://github.com/intel/llvm/pull/13024
=> [OPENCL] Remove EVENT_STATUS_QUEUED workaround

.github/CODEOWNERS, .github/labeler.yml
Adds a new entry to the labeler config to add a `command-buffer` label to any spec, adapter or conformance files relating to command buffers, requested by @EwanC
=> Add a new label and entry to labeler.yml for Command Buffers.

source/adapters/native_cpu/device.cpp, source/adapters/native_cpu/device.hpp, source/adapters/native_cpu/enqueue.cpp, source/adapters/native_cpu/kernel.hpp, source/adapters/native_cpu/nativecpu_state.hpp, source/adapters/native_cpu/queue.cpp, source/adapters/native_cpu/queue.hpp, source/adapters/native_cpu/threadpool.hpp, source/adapters/native_cpu/usm.cpp
This PR introduces a simple threadpool implementation that is used to execute work groups in parallel. 
DPC++ PR: https://github.com/intel/llvm/pull/13176
=> [NATIVECPU] Initial threadpool implementation for Native CPU

source/adapters/cuda/tracing.cpp, source/adapters/cuda/tracing.hpp
Following https://github.com/oneapi-src/unified-runtime/pull/1070 and https://github.com/intel/llvm/pull/12521, clean up the profiling code a bit by removing a now-unused function variant.
Run CI PR: https://github.com/intel/llvm/pull/12583
=> [CUDA] Remove unused function variant

source/adapters/hip/enqueue.cpp
There is an issue with `hipMemset2D` in ROCm prior to **6.0.0** version and this PR adds a workaround for it in `commonMemSetLargePattern`.
The issue appears only when using a pointer to host pinned memory from `hipHostMalloc`. I believe such a case hasn't been used until trying to refactor the USM fill (https://github.com/intel/llvm/pull/12702).
**Testing intel/llvm**: https://github.com/intel/llvm/pull/12898
=> [HIP] Implement workaround for hipMemset2D

source/adapters/native_cpu/enqueue.cpp
The urEnqueueUSMFill command should cover the filling for any arbitrary sizes of the pattern. 
I've been looking how it is implemented for all of the adapters while working on https://github.com/intel/llvm/pull/12702 and thought I'll make a PR.
**intel/llvm Testing:** https://github.com/intel/llvm/pull/13263
=> [NATIVECPU] Extended usm fill to bigger patterns than 1 byte

source/adapters/hip/event.cpp
An event made with a native handle will not have an initialized queue, which the event uses for `ur_event_handle_t::getDevice()`. So it is better to get the scoped context device through the context, which is always guaranteed to be initialized.
=> [HIP] Use context to get active device

source/adapters/level_zero/common.hpp, source/adapters/level_zero/queue.cpp
- Prevent Queue Lock deadlock while L0 queue sync or host sync is in progress.
=> [L0] Enable Disabling of Queue lock during L0 Sync calls

scripts/core/CONTRIB.rst
With the addition of the *Pull Request Labeler* job, add guidance on PR title prefixes to the contribution guide.
Fixes #956.
=> Document PR title conventions

source/adapters/cuda/memory.hpp
Issue was introduced in #1220 where a new allocation is created in a `std::unique_ptr` to enable buffer mapping. The `.get()` member function is called before the `std::unique_ptr` is passed into the `BufferMem` constructor. However, move semantics were not being explicitly followed. The `BufferMem` constructor was taking the `std::unique_ptr` by l-value refernece, then calling `std::move()` on it. This triggered a wrapper-escape, use-after-free defect in Coverity. This fix is to explicitly `std::move()` the `std::unique_ptr` into the `BufferMem` constructor, and also update the `BufferMem` constructor to take an r-value reference instead of an l-value reference.
=> Fix Coverity wrapper escape issue

source/ur/ur.hpp
The `isPowerOf2` utility function is only meant to work on _integrals_, so this change just disables other allowed specializations.
=> [UR] Restrict accepted types for the argument of isPowerOf2 to integral

include/ur_api.h, include/ur_print.hpp, scripts/core/EXP-BINDLESS-IMAGES.rst, scripts/core/exp-bindless-images.yml, source/adapters/cuda/device.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, tools/urinfo/urinfo.hpp
Added the following queries for device capabilities of fetching sampled images:
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D_USM_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D_USM_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D_USM_EXP
- DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D_EXP
=> [Bindless][Exp] Add device queries for sampled image fetch

source/adapters/level_zero/context.cpp, source/adapters/level_zero/event.cpp, source/adapters/level_zero/event.hpp, source/adapters/level_zero/queue.cpp, source/adapters/level_zero/queue.hpp, source/common/ur_util.hpp
Currently, for out-of-order immediate commandlists, each enqueued
operation creates an event on an internal vector to indicate
when that operation is completed. When that vector reaches
1k (by default) entries, each event is individually queried
for status and, if it completed, is cleaned up and removed.
This is causing latency spikes for enqueue operations and
reduces overall performance when using short-lived operations.
This patch introduces an event batching mechanism, where instead
of querying each event individually, the adapter will group
events in batches of 512 entries (by default) that will be
queried collectively with the use of a barrier.
Most of the credit goes to Michal Mrozek <michal.mrozek@intel.com>
for profiling the problem and proposing a solution.
This new mechanism is …
=> [L0] optimize # of event status queries through batching

source/adapters/level_zero/queue.cpp
- Address possible race in accessing the LastCommandEvent by storing the event in local variable for use while in unlock.
=> [L0] Store LastCommandEvent before unlock during queue sync

include/ur_api.h, include/ur_print.hpp, scripts/core/device.yml, scripts/templates/tools-info.hpp.mako, source/adapters/opencl/device.cpp, tools/urinfo/urinfo.hpp, tools/urinfo/utils.hpp
* Change the type returned by the `UR_DEVICE_INFO_UUID` query to `uint8_t` to match the type returned from Level Zero, CUDA, & HIP.
* Modify template to emit call to `printDeviceUUID()` instead of generic info printer to special case output formatting.
* Add `printDeviceUUID()` to print the device UUID in a human friendly format.
=> [urinfo] Fix printing of device UUID

.github/workflows/e2e_core.yml
Workaround an upstream LLVM change which does not play well with the default `-G"Unix Makefiles"` CMake generator by using `-GNinja` instead.
=> [GHA] Use `-GNinja` in nightly workflow

.github/workflows/e2e_core.yml
Use Ninja for building SYCL, and, instead of using SYCL_PREFER_UR, use SYCL_PI_UR_SOURCE_DIR for a in-tree-like build.
=> improve CUDA e2e workflow

source/adapters/cuda/image.cpp
This PR:
* Introduce support for device to device copy in 1D, 2D and 3D.
* target only `Cuarray`s
corresponding PR in https://github.com/intel/llvm/pull/12449
=> [Bindless][Exp] Add support for device to device copies between CuArrays

source/adapters/level_zero/adapter.hpp, source/adapters/level_zero/context.cpp, source/adapters/level_zero/queue.cpp
Fix build issues when using decoupled adapter fetch in intel/llvm by using relative include paths instead of longer explicit paths. This was causing redefinitions of objects. This patch also adds a missing `#pragma once` from the `adapter.hpp` header.
=> [L0] Use relative includes for adapter internals

source/adapters/level_zero/command_buffer.cpp, source/adapters/level_zero/context.cpp, source/adapters/level_zero/context.hpp, source/adapters/level_zero/event.cpp, source/adapters/level_zero/event.hpp, source/adapters/level_zero/memory.cpp, source/adapters/level_zero/platform.cpp, source/adapters/level_zero/platform.hpp, source/adapters/level_zero/queue.cpp, source/adapters/level_zero/queue.hpp
Counter-based events implementation.
Counter-based events can be enabled via the flag UR_L0_USE_DRIVER_COUNTER_BASED_EVENTS=1
Below are the three conformance tests that ensures that this implementation is working as expected:
```
PASS: SYCL :: InorderQueue/in_order_buffs.cpp (1 of 1)
Testing Time: 6.09s
Total Discovered Tests: 1
Passed: 1 (100.00%)
PASS: SYCL :: InorderQueue/in_order_kernels.cpp (1 of 1)
Testing Time: 6.29s
Total Discovered Tests: 1
Passed: 1 (100.00%)
PASS: SYCL :: Basic/in_order_queue_status.cpp (1 of 1)
Testing Time: 7.55s
Total Discovered Tests: 1
Passed: 1 (100.00%)
```
LLVM Draft with CI passing: https://github.com/intel/llvm/pull/12848
Rebased against Raiyan's in-order list [implementation](https://github.com/oneapi-src/unified-runtime/pull/1372/)
=> [L0] Support for counter-based events using L0 driver

include/ur_api.h, include/ur_print.hpp, scripts/core/EXP-COMMAND-BUFFER.rst, scripts/core/exp-command-buffer.yml, source/adapters/level_zero/command_buffer.cpp, source/adapters/level_zero/command_buffer.hpp, source/adapters/level_zero/event.cpp, source/adapters/level_zero/event.hpp, source/adapters/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp
- Adds command buffer property to explicitly enable profiling
- Add ability to enforce use of in-order command lists
Draft DPC++ PR: https://github.com/intel/llvm/pull/13565
=> [EXP][Command-Buffer] Optimize L0 command buffer submission

include/ur_api.h, scripts/core/program.yml, scripts/core/usm.yml, source/adapters/hip/program.cpp, source/adapters/native_cpu/context.cpp, source/adapters/null/ur_nullddi.cpp, source/loader/layers/tracing/ur_trcddi.cpp, source/loader/layers/validation/ur_valddi.cpp, source/loader/ur_ldrddi.cpp, source/loader/ur_libapi.cpp, source/ur_api.cpp, test/conformance/context/context_adapter_native_cpu.match, test/conformance/context/urContextGetInfo.cpp, test/conformance/device/urDeviceGetInfo.cpp, test/conformance/kernel/urKernelGetInfo.cpp, test/conformance/memory/urMemGetInfo.cpp, test/conformance/program/urProgramGetInfo.cpp, test/conformance/queue/urQueueGetInfo.cpp, test/conformance/testing/include/uur/fixtures.h, test/conformance/usm/urUSMGetMemAllocInfo.cpp
This PR fixes: 
* Some genInfo tests was only checking that the query was returning successfully, however wasn't validating the output. This PR add some validation to some of the queries to validate the output. Some queries like device queries couldn't be validated as they depend on the device properties that could be queried through UR backend, so the CTS won't be able to validate those. The queries that is validated in this PR is only the ones that their info was passed on the creation of the handle so the CTS should already have a copy of the output, like querying the context devices or the allocated buffer size.
* USM allocation UR entries was not mentioning in the spec that allocations could be bigger than the size that was specified, as different backends have different behaviour on …
=> Add output validation checks for getInfo tests and a small USM spec fix

.editorconfig, .github/workflows/build-hw-reusable.yml, .github/workflows/cmake.yml, .github/workflows/examples-hw-level-zero.yml
The goal of this patch is to make a failure of one HW build & test job only cancel jobs running on the same HW tag rather than all HW jobs for all adapters. It does this by moving the hardware jobs out of the `cmake.yml` workflow into the new `build-hw-reusable.yml` workflow, which as the name suggests is reusable. This reusable workflow is then used in by adapter specific jobs in the `cmake.yml` workflow to display jobs in a group which is collapsible.
=> [GHA] Separate out hardware workflows

test/conformance/CMakeLists.txt
The match files depend on the output from our GoogleTest test suites to not include ANSI color escape sequences but this setting can be controlled via environment variable `GTEST_COLOR=yes`. This can cause tests to fail even though they should not. This patch explicitly disabled color output by setting `GTEST_COLOR=no` in the test environment.
=> [CTS] Ensure GoogleTest does not output color

CMakeLists.txt, README.md, scripts/generate_docs.py, scripts/run.py, scripts/templates/api_listing.mako
The new `--fast-mode` option to the `run.py` script disables the print API section of the API listing mako template which causes the `generate` CMake target to take an order of magnitude longer to complete.
Before these changes:
```
ninja generate  199.22s user 1.80s system 99% cpu 3:21.67 total
```
After these changes:
```
ninja generate  37.63s user 1.00s system 99% cpu 38.893 total
```
This greatly improves the iterative spec writing experience and can opted by setting the CMake option `UR_ENABLE_FAST_SPEC_MODE=ON`.
=> Add option to enable spec generation fast-mode

source/adapters/level_zero/memory.cpp, source/adapters/opencl/usm.cpp
LevelZero changes:
- Extend the functionality of `enqueueMemFillHelper` to allow calling it with pattern sizes which are not powers of 2. In those cases filling is emulated with copying.
OpenCL changes:
- Add a condition of `isPowerOf2` to the USM fill function
Those changes are necessary for the PR: https://github.com/intel/llvm/pull/12702 which refactors `queue.fill()` to make use of the `urEnqueueUSMFill`. 
**intel/llvm** CI: https://github.com/intel/llvm/pull/12912
=> [L0][OpenCL] Emulate Fill with copy when patternSize is not a power of 2

source/adapters/level_zero/command_buffer.cpp, source/adapters/level_zero/common.hpp, source/adapters/level_zero/context.cpp, source/adapters/level_zero/context.hpp, source/adapters/level_zero/device.hpp, source/adapters/level_zero/event.cpp, source/adapters/level_zero/event.hpp, source/adapters/level_zero/image.cpp, source/adapters/level_zero/kernel.cpp, source/adapters/level_zero/memory.cpp, source/adapters/level_zero/queue.cpp, source/adapters/level_zero/queue.hpp
- Given a command being enqueued without dependencies or dependencies outside of a given batch of commands, then signal the event at the end of the command list allowing for parallel execution of the commands.
=> [L0] Enable Batching out of order commands without signal events

CMakeLists.txt, README.md, test/conformance/device_code/CMakeLists.txt
These can be passed as a space-separated list of options - analogous to `CMAKE_CXX_FLAGS` and co - and are passed to DPC++ when building device programs.
=> [CTS] Allow users to pass build flags to DPC++

scripts/ctest_parser.py
When trying to run the CTS from a directory with no tests then the total number of tests is 0, which was causing issues when summarizing results.
=> [CTS] Avoid division by zero (when there are no results)

CMakeLists.txt, README.md, test/conformance/CMakeLists.txt
This patch adds a new CMake option `UR_CONFORMANCE_ENABLE_MATCH_FILES`, defaulting to `ON`, which allows developers to disable the use of match files in order to discover the true state of conformance runs.
=> [CTS] Allow disabling the use of match files

source/adapters/level_zero/event.cpp
This fixes a race when creating queue events without acquiring the appropriate locks, and also fixes a deadlock when acquiring multiple queue locks.
The deadlock scenario is roughly this:
queue1 = ...;
queue2 = ...;
for (;;) {
queue1_event = urEnqueueKernelLaunch(queue1, ...);
// lock order: queue2->Mutex, queue1->Mutex
urEnqueueEventsWait(queue2, 1, [queue1_event], nullptr);
}
T2:
for (;;) {
queue2_event = urEnqueueKernelLaunch(queue2, ...);
// lock order: queue1->Mutex, queue2->Mutex
urEnqueueEventsWait(queue1, 1, [queue2_event], nullptr);
}
The solution in this patch is the simplest possible fix I managed to figure out, but I strongly believe this code requires a substantial refactor to better structure the synchronization logic. Right now it's a minefield.
=> fix queue locking behavior when creating event lists

source/adapters/level_zero/common.cpp, source/adapters/level_zero/queue.cpp, test/adapters/CMakeLists.txt, test/adapters/level_zero/CMakeLists.txt, test/adapters/level_zero/event_cache_tests.cpp, test/adapters/level_zero/zeCallMap.cpp, test/conformance/testing/include/uur/fixtures.h
in single-device scenario.
When event is an internal event (when using queue with discard events property) the UrQueue is set to nullptr. This means that inside addEventToContextCache the event will be added to a multi-device cache which is wrong. This causes unbounded growth of the multi-device event cache if there are no multi-device events requested from the cache.
=> Fix adding event to queue cache

source/adapters/level_zero/event.cpp
The current implementation of queue command batching appears to assume that getAvailableCommandList is followed by a single executeCommandList, and it's not allowed to, for example, create a list of CmdLists for later execution. And there's an assert to check for this.
This makes sense, since it doesn't really make sense to batch things across many different CmdLists. However, the implementation of urEnqueueEventsWaitWithBarrier was doing exactly that.
This patch disables batching in executeCommandList, fixing a assert failure during urEnqueueEventsWaitWithBarrier when many potentially open command lists are in use.
=> stop batching multiple CmdList execution when waiting for barriers

source/adapters/cuda/usm.cpp, source/adapters/cuda/usm.hpp, source/adapters/hip/usm.cpp, source/adapters/hip/usm.hpp, source/adapters/level_zero/usm.cpp
Flags are 32bit here and none of these implementations functions need modify their argument. Passing by reference is opaque, slower, and superfluous in this case, so let's just pass by value.
=>  [l0][HIP][CUDA] Prefer values over pointers-to

source/loader/ur_adapter_registry.hpp
This patch belatedly adds the Native CPU adapter to the list of known adapters in the adapter registry. It also reorders the adapters in the know list.
=> [Loader] Add Native CPU to adapter registry

source/adapters/level_zero/event.cpp
Reverts oneapi-src/unified-runtime#1555 due to intel/llvm SYCL e2e checks failing, see [here](https://github.com/intel/llvm/pull/13599#issuecomment-2093241342).
=> Revert "stop batching multiple CmdList execution when waiting for barriers"

test/conformance/CMakeLists.txt
Fix regression introduced in #1574 where `GTEST_COLOR=no` was no longer being set due to use of wrong CMake variable in if statement.
=> [CTS] Fix typo in add_test_adapter()

CMakeLists.txt, README.md
This matches the required version for llvm-project.
=> [CMake] Bump CMake version required 3.14 -> 3.20

README.md, test/conformance/device_code/CMakeLists.txt, test/conformance/program/urProgramBuild.cpp, test/conformance/program/urProgramCreateWithIL.cpp, test/conformance/source/environment.cpp, test/conformance/testing/include/uur/environment.h, test/conformance/testing/include/uur/fixtures.h
Some improvements to the device code generation cmake:
* Use `clang-offload-extract` instead of running the binary directly.
* Set up dependencies correctly so that re-running builds will generate missing IR files if they failed to build prior.
* Dynamically generate the list of device_code files - from now on, any .cpp file in the device_code directory will automatically be treated as device code and generate IR files.
This change drops CTS support for platforms that support multiple devices with different IR types, however the build system didn't support that anyway, nor do any of our adapters.
This change requires a `clang-offload-extract` binary to be available. By default it is assumed to be in the same directory as the provided DPC++ binary (which should work for most builds), …
=> Improve CTS device code generation

source/adapters/cuda/device.cpp
https://github.com/oneapi-src/unified-runtime/pull/1400 incorrectly removed some device info enumerator cases due to a fault merge conflict resolution. This commit adds them back.
=> [CUDA] Add back device info enums after merge mistake

source/adapters/level_zero/context.cpp, source/adapters/level_zero/event.cpp
This is another attempt to fix an issue where the L0 Adapter crashes when urEnqueueEventsWaitWithBarrier in presence of multiple active command queues with batched cmdlists.
The core issue is that the current queue implementation only allows for two command lists to be active open batches, one for copy and one for compute. If that assumption doesn't hold, the getAvailableCommandList function, when executed multiple times for a command queue of the same type, will override the active open command batch. So only the last retrieved command list can actually be batched. After this, when the code attempts to execute all the command lists it collected, with batching enabled. And this is where we hit an assert because the active open command list doesn't match what is being used.
The proper fix …
=> fix queue-wide barriers with multiple active command queues

source/adapters/level_zero/device.cpp
- Until usage of Driver In Order lists can be confirmed stable, disable the usage of the driver in order lists by default.
=> [L0] Disable Usage of Driver In order Lists by default

.github/scripts/get_system_info.sh, source/adapters/opencl/device.cpp, test/conformance/device/device_adapter_opencl.match
This patch does three things:
1. Removes the passing OpenCL test from the device match file `urDeviceGetInfoTest.Success/UR_DEVICE_INFO_HALF_FP_CONFIG`
2. Uses `UR_RESULT_ERROR_UNSUPPORTED_ENUMERATION` when half query is not supported
3. Adds the `--verbose` flag to `urinfo` step to provide more information when HW jobs fail.
=> [CL] Update device CTS match file

source/common/ur_util.hpp
This was causing a warning with -Wpedantic.
=> [NFC] Remove unnecessary semicolon

.github/scripts/get_system_info.sh, CMakeLists.txt, source/adapters/level_zero/context.cpp, source/adapters/level_zero/device.cpp, source/adapters/level_zero/event.cpp, source/adapters/opencl/device.cpp, test/conformance/device/device_adapter_opencl.match
=> Candidate for the v0.9.2 release tag

test/conformance/exp_command_buffer/buffer_fill_kernel_update.cpp, test/conformance/exp_command_buffer/exp_command_buffer_adapter_hip.match
CTS test assumes that backend will only require a single buffer accessor offset parameter, however the HIP backend requires 3.
This should fix [sporadic failures](https://github.com/oneapi-src/unified-runtime/actions/runs/8892452470/job/24416545313) in the `BufferFillCommandTest` tests.
=> Fix CTS test for HIP accessors

source/adapters/hip/device.cpp
When calling hipMemGetInfo, an internal problem querying the amount of available global memory causes the function to return hipErrorInvalidValue. This is indistinguishable from us doing something wrong, and it (rightly) causes an assertion failure. This is a particularly egregious issue because we query this property and crash during the execution of `sycl-ls --verbose`.
This architecture is not officially supported by HIP, so we can't file a bug and shouldn't expect an official fix for this issue any time soon. It is possible, however, that we'll need to extend this workaround with other architectures over time.
=> [HIP] Add a workaround for crashes on gfx1031

.github/scripts/get_system_info.sh, CMakeLists.txt, include/ur_api.h, include/ur_ddi.h, include/ur_print.hpp, scripts/Doxyfile, scripts/core/platform.yml, scripts/generate_docs.py, scripts/parse_specs.py, scripts/run.py, scripts/templates/helper.py, scripts/version.py, source/adapters/opencl/device.cpp, source/ur_api.cpp, test/conformance/device/device_adapter_opencl.match
Bumping to v0.10.0 exposed a bug in the spec generation scripts where versions were being converted to `float` and then used doing version comparisons. Converting `0.10` to `float` results in `0.1` which is an incorrect representation of that version. To address this the scripts have been updated, including the new `Version` class which handles version comparisons, to never use `float` to represent versions.
=> [NFC] Bump CMake verson to 0.10.0

scripts/core/INTRO.rst
This PR is supposed to be merged along/after logger changes in adapters.
(https://github.com/oneapi-src/unified-runtime/pull/1359; https://github.com/oneapi-src/unified-runtime/pull/1347; https://github.com/oneapi-src/unified-runtime/pull/1345; https://github.com/oneapi-src/unified-runtime/pull/1342; https://github.com/oneapi-src/unified-runtime/pull/1032)
To prevent merge conflicts between adapter changes, I have created this PR for the documentation update. Splitting this change into commits along with the logger changes would result in needing to rebase and resolve conflicts after each PR merge, what would become cumbersome to maintain. While this approach allows for merging all changes simultaneously without any conflicts.
=> Document adapter logging environment variables

source/adapters/native_cpu/device.cpp, source/adapters/native_cpu/enqueue.cpp, source/adapters/native_cpu/kernel.cpp, source/adapters/native_cpu/kernel.hpp, source/adapters/native_cpu/program.cpp, source/adapters/native_cpu/program.hpp
Adds support to the `reqd_work_group_size` kernel attribute. The metadata handling mechanism is similar to what is done in the CUDA adapter.
DPC++ PR: https://github.com/intel/llvm/pull/13175
=> [NATIVECPU] Support reqd_work_group_size on Native CPU

source/adapters/cuda/usm.cpp
Seeing an error in Windows debug build about corrupted stack memory around the `IsManaged` variable which goes away if I change its type to `unsigned int`.
=> [CUDA] Change `bool` variable type to `unsigned int` 

.github/workflows/e2e_core.yml
Use test filters only when they are set, which is for L0. Otherwise we get 'error: filter did not match any tests'.
=> [CI] Fix E2E workflow

.github/workflows/e2e_core.yml, .github/workflows/e2e_level_zero.yml
This job is running on a powerful system with 200++ cores. Letting llvm-lit run with default number of workers (equal to the number of cores), starves the system of other resources, leading to hangs.
=> reduce number of workers for the L0 E2E job

scripts/parse_specs.py
Python 3.8 shipped with Ubuntu 20.04 does not support using concrete types subscript in type hints, e.g. `list[Version]` caused `TypeError: 'type' object is not subscriptable`. This patch fixes #1625 by using the type hint classes provided by the typing module instead of concrete types.
=> Fix Python scripts on Ubuntu 20.04

scripts/generate_kernel_header.py
When running only the CTS it should be possible to do so without first installing the requirements for building the specification.
=> [CTS] Don't depend on Mako in tests

.github/workflows/e2e_core.yml, .github/workflows/e2e_level_zero.yml
LIT_OPTS is more generic, and also covers cases where there is no direct way to modify what CMake passes to llvm-lit command.
=> Limit # of workers in E2E job through LIT_OPTS

.github/workflows/e2e_core.yml, .github/workflows/e2e_level_zero.yml
This time I tested the change :)
=> fix passing LLVM LIT arguments in workflows
